### ISSUE TITLE
Low-resolution covers

### ISSUE THREAD

**Issue by MairusuPawa** [Vocaluxe/Vocaluxe#128]
Hello!

I noticed that Vocaluxe tends to load low-res covers when they are PNGs. I have a set of songs with 300x300 PNG covers, interlaced, and the UI only displays the degraded version of the picture. It doesn't look great.

Could this be improved?

**Comment by lukeIam** [comment]
Does something speak against changing the default cover resolution to 300x300?

I checked the file size of a test cover: 
.jpg: 8.57KB -> 22.0KB
.png: 61.9KB -> 167.0KB

~2.5 times bigger files but with the small KB sizes it should't be a problem, or?

**Comment by flokuep** [comment]
Should be okay
