### ISSUE TITLE
Something went wrong in the source

### ISSUE THREAD

**Issue by z3ro01** [Vocaluxe/Vocaluxe#147]
Hello!
I downloaded the source about a month ago. I corrected some bugs and i started to write a new feature. Everything worked fine with this code.
I wanted share my code, so i forked the latest source yesterday, but i noticed a new bug.

During the game if you sing to mic the bgvideo and singbars began freezing, but if you dont sing or turn off the mic it goes normally.
I have tested the code without my changes and the bug is still there.

Can anyone confirm this?

**Comment by flokuep** [comment]
I'm currently really busy, I will have a closer look on it in easter-week.
Maybe you could just start to upload to github.

**Comment by z3ro01** [comment]
Ok. now i'm found it: 
In old source, pitchtracker.dll size was around 50k. In new source the size is 233k.
If i replace pitchtracker.dll in new code with older dll it works perfectly. But, if i use 233k version i have fps drops and freezes in sing screen.  (tested on two windows x64)

**Comment by lukeIam** [comment]
@z3ro01 could you determinate the versions of  `pitchtracker.dll` ?

**Comment by flokuep** [comment]
Or do a bisect on this? Pitchtracker is build by ourself, so there is maybe a bug... Would be nice to know where.

**Comment by z3ro01** [comment]
I cant properly. Working pitchtracker.dll (both x64 amd x86) copied from an older Vocaluxe install i think.
Install folder name is Vocaluxe v0.2.1 Final (0073), but version number in config.xml is Vocaluxe "Shining Heaven" v0.3.1 (x64) Beta (0000).

**Comment by z3ro01** [comment]
I cant do bisect. When rebuild pitchtracker with old source, the size is 233k, so no difference in sources.
Can be a build problem? Im using Visual Studio 2013 on win7.
I reinstalled all dependecies (and visual studio), but the result is the same.

**Comment by flokuep** [comment]
Don't know, but a little morning idea: build pitchtracker as release instead of debug? Or is there no option?

**Comment by z3ro01** [comment]
Ok. that was. When im build in release mode build size is around 50k and works perfectly! :)
Thank you!

**Comment by flokuep** [comment]
Nice to hear this :)
