### ISSUE TITLE
Playlist UI broken

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#148]
In the current develop branch the playlist control seems to be broken:
The `Load`, `Save` and `Play` buttons have no function

EDIT: Renaming the playlist is also not possible

**Comment by flokuep** [comment]
I will have a closer look to this in the next week - I'm trying to switch to a linux-system. Very exited :D

**Comment by flokuep** [comment]
Okay. This is really annoying. Still don't know what's really happening there. Navigating through buttons works with keyboard (after pressing TAB), but pressing enter has no effect.

**Comment by lukeIam** [comment]
fixed
