### ISSUE TITLE
Video "BG_Video": ([Blue]BG_Video.mp4) not found!

### ISSUE THREAD

**Issue by Erikson** [Vocaluxe/Vocaluxe#149]
Hi,

i compiled the most recent (8d3eb2c395c9e41d2feae3ca0a7b85defc396211) vocaluxe source and got the following errors on start:

Video "BG_Video": ([Blue]BG_Video.mp4) not found!

Failed to load skin Ambient:Blue! Removing...

The same again with green, red and yellow.

It occours on 64 and 32 bit version. I compiled from clean, fresh downloaded repository.
I hope you can help me!

Erikson

**Comment by z3ro01** [comment]
You can download an installer version from http://vocaluxe.sourceforge.net.
Install (or extract) it to somewhere and copy theme videos back to your source folder.

**Comment by flokuep** [comment]
Or you download them directly on github: https://github.com/Vocaluxe/Vocaluxe/releases/download/0.3.0.83/Themes.zip - The reason for this: they are just too big for pushing them on git.

**Comment by Erikson** [comment]
Thanks! It would be good to leave a comment in readme or on startpage of repository for people like me. ;)
