### ISSUE TITLE
Feature: Multi Monitor for Song Playback

### ISSUE THREAD

**Issue by minigraphx** [Vocaluxe/Vocaluxe#153]
Multi Monitor Support would be great, to allow playing the Song on a 2nd Screen, while having Menu and Configuration on he 1st Screen only

**Comment by flokuep** [comment]
Using a second monitor is a lot of work I guess. Maybe we could use our webserver for this. So you could add via smartphone/browser/tablet or anything else next rounds with song, player and so on.
But this still needs a lot of work...

**Comment by Flamefire** [comment]
Use the browser for that.
Multi-Monitor would however be good for song playback. E.g. 8 Players, 4 on first screen, 4 on 2nd. (or 4 players with 2 on each monitor)

**Comment by lukeIam** [comment]
Some basic multi monitor support was added to the develop version (big thanks again to @Jiiniasu) -> closing this
