### ISSUE TITLE
Support #DUETSINGER1, #DUETSINGER2 and #DUETSINGER3 tags.

### ISSUE THREAD

**Issue by skyli91** [Vocaluxe/Vocaluxe#159]
All songs that I download have these tags and not #P1 #P2 #P3. I can edit these txt's but it would be nice to support it. 
![image](https://cloud.githubusercontent.com/assets/7442913/11335898/eed22e8e-91e0-11e5-9d1e-c3d3cd44f551.png)

**Comment by flokuep** [comment]
We already support these tags; Check https://github.com/Vocaluxe/Vocaluxe/blob/develop/VocaluxeLib/Songs/CSongLoader.cs#L349

**Comment by derivator** [comment]
This line: `if (identifier.StartsWith("P")) // fix for missing "P"` seems to be missing a `!` though, doesn't it?

**Comment by BenKmann** [comment]
Derivator i agree, there is a ! missing in Line 352:
https://github.com/Vocaluxe/Vocaluxe/blob/develop/VocaluxeLib/Songs/CSongLoader.cs#L352

**Comment by lukeIam** [comment]
Agree
