### ISSUE TITLE
Problems compiling Linux dependencies

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#162]
Moved from here:
https://github.com/Vocaluxe/Vocaluxe/issues/31#issuecomment-122662857

**Comment by lukeIam** [comment]
https://github.com/Vocaluxe/Vocaluxe/issues/31#issuecomment-122662857 by @Vittelius
> Hi, I tried to compile Vocaluxe with Ubuntu 15.04. I managed to fix all the linking-errors, but I still get this:
> make -C PitchTracker
> make[1]: Entering directory '~/git/Vocaluxe/PitchTracker'
> gcc -shared -o libPitchTracker.dll.so -fPIC compatibility.o dywapitchtrack/dywapitchtrack.o dywapitchtrack/ptDyWa.o FFT/FFT.o FFT/RealFFTf.o Helper.o performous/pitch.o ptAKF.o PitchWrapper.o
> strip libPitchTracker.dll.so
> cp libPitchTracker.dll.so ../Output/
> make[1]: Leaving directory '~/git/Vocaluxe/PitchTracker'
> make -C Vocaluxe/Lib/Video/Acinerella
> make[1]: Entering directory '~/git/Vocaluxe/Vocaluxe/Lib/Video/Acinerella'
> gcc -c -fPIC acinerella.c -I /usr/local/include
> acinerella.c: In function ‘ac_get_stream_info’:
> acinerella.c:201:67: error: ‘AVStream’ has no member named ‘r_frame_rate’
> (double)((lp_ac_data)pacInstance)->pFormatCtx->streams[nb]->r_frame_rate.num /
> ^
> acinerella.c:202:67: error: ‘AVStream’ has no member named ‘r_frame_rate’
> (double)((lp_ac_data)pacInstance)->pFormatCtx->streams[nb]->r_frame_rate.den;
> ^
> acinerella.c: In function ‘ac_free_package’:
> acinerella.c:256:7: warning: ‘destruct’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:994) [-Wdeprecated-declarations]
> if (pkt->destruct){pkt->destruct = av_destruct_packet; pkt->destruct(pkt);} //FIXME: workaround for deprecation of AVPacket::destruct
> ^
> acinerella.c:256:7: warning: ‘destruct’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:994) [-Wdeprecated-declarations]
> acinerella.c:256:7: warning: ‘av_destruct_packet’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3294) [-Wdeprecated-declarations]
> acinerella.c:256:7: warning: ‘destruct’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:994) [-Wdeprecated-declarations]
> acinerella.c: In function ‘ac_create_video_decoder’:
> acinerella.c:309:2: warning: ‘avcodec_alloc_frame’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195) [-Wdeprecated-declarations]
> pDecoder->pFrame = avcodec_alloc_frame();
> ^
> acinerella.c:310:2: warning: ‘avcodec_alloc_frame’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195) [-Wdeprecated-declarations]
> pDecoder->pFrameRGB = avcodec_alloc_frame();
> ^
> acinerella.c: In function ‘ac_decode_audio_package’:
> acinerella.c:467:3: warning: ‘avcodec_alloc_frame’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3195) [-Wdeprecated-declarations]
> if (!(decoded_frame = avcodec_alloc_frame())) {
> ^
> acinerella.c:471:9: warning: ‘avcodec_get_frame_defaults’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3205) [-Wdeprecated-declarations]
> avcodec_get_frame_defaults(decoded_frame);
> ^
> acinerella.c:500:52: error: ‘AV_CH_LAYOUT_STEREO’ undeclared (first use in this function)
> av_opt_set_int(swr_ctx, "out_channel_layout", AV_CH_LAYOUT_STEREO, 0);
> ^
> acinerella.c:500:52: note: each undeclared identifier is reported only once for each function it appears in
> acinerella.c:511:84: error: ‘AV_ROUND_UP’ undeclared (first use in this function)
> decoded_frame->nb_samples, dst_sample_rate, (pDecoder->pCodecCtx)->sample_rate, AV_ROUND_UP);
> ^
> makefile:2: recipe for target 'acinerella' failed
> make[1]: *** [acinerella] Error 1
> make[1]: Leaving directory '~/Vocaluxe/Vocaluxe/Lib/Video/Acinerella'
> makefile:4: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by lukeIam** [comment]
https://github.com/Vocaluxe/Vocaluxe/issues/31#issuecomment-122672259 by @derivator 
> @Vittelius I strongly suspect this is because Ubuntu ships with libav instead of ffmpeg. For example, the libav people helpfully decided that r_frame_rate is useless and should be removed. I think you would need the package ffmpeg and some/all of the lib*-ffmpeg-dev packages. I don't know if just installing them is sufficient, I think they may have their header files in different locations to avoid conflicts with libav, so you may have to change the gcc options in the makefile to -lavformat-ffmpeg, etc. Try how far you can get, and if you have any problems, post here and I'll try to help. If you get it running, please tell us what steps you had to take, so others won't have to duplicate this work.

**Comment by lukeIam** [comment]
I thought that the real ffmpeg has returned in the official repo with Ubuntu 15.04
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

**Comment by astoeckel** [comment]
As the author of acinerella I'd like to let you know that there is a new version available at

https://github.com/astoeckel/acinerella

the old version did not compile any longer on modern Linux systems.

**Comment by Flamefire** [comment]
Thanks @astoeckel.

@Devs: Please note, that the acinerella version in Vocaluxe differed from the original one. As far as I can remember @flokuep made some changes when he introduced it long time ago and it diverged from the upstream. So a drop-in update is not possible at all. However I'd recommend to check these changes (maybe @flokuep can help here) and see, if we can switch to the upstream version by doing required changes on the C# side only. This way updates will be much easier.

**Comment by flokuep** [comment]
Can't remember any changes... Maybe it was someone other?
But yeah, we should update.

**Comment by lukeIam** [comment]
Thanks for updating @astoeckel !

I tried to build it on my windows machine with VS2015 but got stuck on a ffmpeg problem:
Some symbols of `swresample.h` could not be resolved (it seems that the `swresample.h` does not fit to the `swresample.lib` in the current ffmpeg windows release)

```
1>acinerella.obj : error LNK2019: unresolved external symbol "swr_init" in function "ac_create_audio_decoder".
1>acinerella.obj : error LNK2019: unresolved external symbol "swr_alloc_set_opts" in function "ac_create_audio_decoder".
1>acinerella.obj : error LNK2019: unresolved external symbol "swr_free" in function "ac_free_audio_decoder".
1>acinerella.obj : error LNK2019: unresolved external symbol "swr_convert" in function "ac_decode_audio_package".
```

**Comment by astoeckel** [comment]
@lukelam The dependency on swresample is new (it is now needed as ffmpeg diversified the way in which decoded audio data) -- did you probably just forget to link against the corresponding library (libswresample)?

**Comment by lukeIam** [comment]
Ah - that makes sense. Thanks @astoeckel ! I'll try it this evening...

**Comment by lukeIam** [comment]
There must have been some changes on the acinerella used in Vocaluxe - it seems that all the callback handling was done there.
Do we have this source code somewhere?

@astoeckel: my windows build works now with the demo application (with some little changes)

**Comment by flokuep** [comment]
Mhm. Quite dont know. You may check history of Vocaluxe/Lib/Video...

**Comment by astoeckel** [comment]
@lukeIam feel free to send a PR or to open an issue for any change necessary to run acinerella on Windows. Regarding the callback handling: I've added a method ac_open_file to the API which should resemble your previous usage of acinerella without callbacks.

**Comment by lukeIam** [comment]
> @lukeIam feel free to send a PR or to open an issue for any change necessary to run acinerella on Windows.

I will - at the moment my changes are a bit ugly and would most likely break the linux build.
I'll refactor may changes first.



> Regarding the callback handling: I've added a method ac_open_file to the API which should resemble your previous usage of acinerella without callbacks.

Wow - thank you very much!
I'm just talking about a problem we have and you immediately offer a solution in your lib :+1: 

At the moment I'm debugging the problems in Vocaluxe to integrate the new lib - mostly some struct changes.
Unfortunately I didn't found much time this weekend.

**Comment by lukeIam** [comment]
> But yeah, we should update.

First step is done:
https://github.com/lukeIam/Vocaluxe/commit/165abd5fe6791f3325c6ebce9e7f22dbd7a7f6a2#commitcomment-15785946

But it's not fully working yet...

**Comment by lukeIam** [comment]
is fixed the the upgraded acinerella version.
