### ISSUE TITLE
Freeze/Lag on SongScreen

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#167]
... occurs if the selected song is changed fast.

Seems to be caused by the video or/and audio preview...

reported here: http://forum.ultra-star.de/viewtopic.php?f=91&t=11170

**Comment by lukeIam** [comment]
Problem occurs because our video decoder lib wrapper is single threaded (while the lib itself seems to support multithreading)

I'm working on a solution...

**Comment by flokuep** [comment]
Seems to be fixed. What we could improve: Start fading to video-preview when video-loading is finished.

**Comment by lukeIam** [comment]
@flokuep 
> What we could improve: Start fading to video-preview when video-loading is finished.

sorry, but I didn't get the point.
Can you explain me what you meant?

**Comment by flokuep** [comment]
Just merge my preview fix from vocaluxe/dev. You will notice that song cover fades out to first frame of video, and then you see this until video playes.
