### ISSUE TITLE
Crash after starting a second challenge mode

### ISSUE THREAD

**Issue by mandark** [Vocaluxe/Vocaluxe#169]
hi there!

first of all many thanks for your work on Vocaluxe! in my opinion it is the best and greatest singing game for the PC out there! it has provided me, my family and friends with countless hours of joy. i can't thank you enough for that! :D although it is already great as it is, i hope Vocaluxe will continue to improve and be maintained.

i'm having a particular problem with the challenge mode, and i think i've found a way to reproduce it. the problem seems to occur, if a challenge mode game has been completed, and a new one is started.

here are the steps to reproduce the problem:
1. start Vocaluxe
2. start a challenge mode (2 players and 1 round are enough to reproduce the problem).
3. you can abort the song immediately after starting it, since the error occurs also then.
4. the challenge mode is finished.
5. now start a new challenge mode.
6. the game crashes immediately after clicking "next" at the challenge mode options screen. you can find a screenshot of the error here: http://imgur.com/Y3bg6UC

after restarting Vocaluxe, a new challenge mode game can be started and completed without a problem. but when trying to start another go, the game crashes again.

i'm using the most current version i could find: Vocaluxe "Shining Heaven" v0.3.0 (x64) Beta (0.3.0.83-536-g378b9e6)
downloaded from here: https://ci.appveyor.com/project/lukeIam/vocaluxe/build/job/8dtvqdo1jax21g71/artifacts

but the error has been occuring since some other versions, i have tried.

maybe you can fix this problem. please let me know, if you need any more info.

many thanks and best wishes
gerald

**Comment by flokuep** [comment]
Thanks for your report! I think this commit 50c19ff85df3e459e2d36c3b8d50aff6cd1a549e should fix it, still need to look into all changes by this dev and maybe fix one or two things...

**Comment by mandark** [comment]
@flokeup
thanks for the info! i'm looking forward to the merging of this fix.

**Comment by lukeIam** [comment]
Sorry - used wrong issue number first...
(ignore https://github.com/lukeIam/Vocaluxe/commit/4b9bfac1d9edc193c4d2a453082e94cc67966527 it is already removed from the branch)

**Comment by mandark** [comment]
FYI: i've merged the changes from  z3ro01/develop to the current vocaluxe/develop branch in my local repo and compiled it. everything seems to be working fine and the challenge mode bug seems to be gone.

**Comment by lukeIam** [comment]
should be fixed, or?
see https://github.com/Vocaluxe/Vocaluxe/commit/dc375de63200230531c7062af6b292864ad096fa

**Comment by mandark** [comment]
yes, i didn't encounter the problem anymore with the newest version. thank you!
