### ISSUE TITLE
Links in the App (Wiki, Youtube, ...) do not longer work

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#172]

**Comment by Domani89** [comment]
The question is why do you need that? If you don't know a song, you don't like sing it. Best is the audio preview, than you have no traffic from internet.

**Comment by derivator** [comment]
Should this be in the .3 milestone?

**Comment by lukeIam** [comment]
As the new youtube api doesn't allow any requests without api key I will remove the buttons as suggested.
