### ISSUE TITLE
Bidirectional communication for the Webserver?

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#176]
Should we add a channel for server->client?

Some time ago I implemented something like that: the server can send messages to single players:
https://github.com/Vocaluxe/Vocaluxe/wiki/HowTo:-Use-'PlayerCommunication'-(bidirectional-server-communication)
Code with a demo (Current song screen):
https://github.com/lukeIam/Vocaluxe/tree/newPlayerComCurrentSongDemo

Maybe we could reuse some of that code or just use it as inspiration...

**Comment by Shiroi** [comment]
I vote for yes.

This could be really useful to send notifications to players. For example to show them who sings next. Also PartyModes could make use of it to get input from some or all players.

**Comment by lukeIam** [comment]
I've invested some time to get the branch up to date again:
https://github.com/lukeIam/Vocaluxe/tree/newPlayerComCurrentSongDemo

Test by going to the "current song screen" in the app and play different songs in Vocaluxe.

**Comment by lukeIam** [comment]
The bidirectional communication part is pretty much untested as I stopped the development on the webserver part (as it was not really used at that time).

**Comment by lukeIam** [comment]
The webserver will be rewritten some time (including a better bidirectional communication)
