### ISSUE TITLE
Should we keep the installable apps? -> No

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#180]
Atm Vocaluxe displays some qr codes to the installers of the app on https://build.phonegap.com.
The Idea for an app was to have a easy accessible interface for interacting with Vocaluxe:
no browser needed, no urls (app has auto discovery), just open the app...

During more than a year the apps weren't propagated public and there was no development on that part.

So I did a **stocktake** - the current problems with the installable apps (not the Website):  
* the app on build.phonegap.com was originally only a test thing on a dummy account   
(luckily I found the credentials)
* there is no auto pull configured and there was no manual update for a long long time (but it could be configured)
* what happens if the server version does not match the app version   
There should be an automatic fall back to the website version (displayed in the app) - but untested so far
* we are currently using phonegap 2.9.0 (recommended is 5.2.0)   
-> I do not know what impact this has
* **Android:** The apk could only be installed if untrusted sources are enabled.   
Does anyone has a google developer account that could be used for publishing in the play store?
* **Windows Phone:** The app could only be installed if the device is in developer mode - needs registration in Win8 mobile, settings unlock with Win10 mobile.   
Does somebody has a Microsoft store developer account (I think they are free for students)?
* **IPhone/IPad:** We can't create a IPhone/Ipad app, as we do not have a developer certificate.   
If nobody has a apple developer membership and would publish our app - I would say browser only on apple devices...
* I do not know if the current files result in a running app
* There is a version tag injected at Vocaluxe build time - this wouldn't be in the repo that phonegap build pulls.
Would need some build process magic.

**Questions**:   
* Do we still want to have apps?   
or should we just have the website version?
* How to handle those developer membership problems?
* Should we still use phongap build (was pretty easy so far) and configure it to pull the changes from github?

**Comment by derivator** [comment]
I would say the website version is sufficient. It works without installation on any device, which is much more convenient than having your guests install an app.

What benefit does an installable app offer?

**Comment by lukeIam** [comment]
> It works without installation on any device, which is much more convenient than having your guests install an app.

The app would be a addition to the browser version.

> What benefit does an installable app offer?

* We have an app :wink:  ( + maybe some advertisement through an appstore)
* The app has a symbol on the home screen and is easy to lunch
* The app discovers a server in the same subnet automatically (nor url or port needed)
* Maybe a little bit faster as the (few) icons do not have to be loaded
* Full screen - in the browser you might see the address bar when scrolling
* using a native camera plugin for photos - the web app have to use the camera possibilities which the browser offers

=> many small things
But in my opinion none of them is very important

**Comment by lukeIam** [comment]
Should we keep/repair the apps or just drop app support and recommend the webapp?

**Comment by flokuep** [comment]
I think we could drop app support; It's easier for us to manage and the webapp provides all features we need.

**Comment by derivator** [comment]
:+1: for dropping.

**Comment by lukeIam** [comment]
> webapp provides all features we need.

:+1: for dropping the installable apps

**Comment by lukeIam** [comment]
Todo:
- [ ] Remove the app qr codes and make the one with the server address (middle) bigger
- [ ] Delete app at phonegap build
- [ ] Change (new) Readme :wink:

**Comment by Domani89** [comment]
If you need it, I can make a developer account so i will pay the registration fee

**Comment by lukeIam** [comment]
@z3ro01 thanks for changing  the qr code screen

@Domani89 thanks for your offer - but as the webapp supports all features it is easier to have only one system to supoort
