### ISSUE TITLE
Unique Player-IDs

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#183]
At the moment players has a incrementing player id that depends on the profile loading order (alphabetic?). Just to clarify: there is no id stored.

It would be good to have an id which stays the same over time and even over systems (maybe useful in the future).

Problem: there are so many places in the Vocaluxe code where the id is used for integer operations.
I tried four times to change the player id to a guid - but I screwed up each time.

So here is my suggestion:
give each player an **additional** guid next to the integer id (update existing profiles on load).

**Advantages**:   
- we do not break any existing code
- we create a doubtless possibility to identify a user if situation needs it
- we are creating a basis for a potential central profile system in the future

**Disadvantages**:   
- not that nice because we have two ids

**Comment by flokuep** [comment]
What was the problem with guid?

**Comment by lukeIam** [comment]
I would really like  to have only a guid - but many places in the Vocaluxe
code assumes that ids are integers.

So my idea was to add a guid additionally.

If someone could replace the int id completely - even better.
Am 22.12.2015 08:52 schrieb "Florian Küpper" <notifications@github.com>:

**Comment by flokuep** [comment]
I will have a look on it.

**Comment by flokuep** [comment]
Please have a look at this, test, and review code: https://github.com/flokuep/Vocaluxe/tree/player-guid

**Comment by lukeIam** [comment]
> I will have a look on it.
> Please have a look at this, test, and review code: https://github.com/flokuep/Vocaluxe/tree/player-guid

Thanks for your work!

I haven't had the time for a deep test yet, but I found a little problem:
- 3 default profiles 
- Edit Profile name of Guest 3 in Voacluxe
- As you delete the name of Guest 3 all other names get deleted too
- If you save the name it will be saved as new name for Guest 1 (Guest 2 and Guest 3 names are now empty )

**Comment by lukeIam** [comment]
other short question: as I can remember guest accounts could be selected for playing multiple times, right?

atm they also disappear after the first selection.

**Comment by lukeIam** [comment]
The profile features of the webapp are also broken.
I thing there will be a little refactoring required.

**Comment by flokuep** [comment]
>other short question: as I can remember guest accounts could be selected for playing multiple times, right?
Yeah, still works as expected in my tests? There is only one minor thing: Guest3 isn't a guest... Could you tell me how to reproduce this

>I haven't had the time for a deep test yet, but I found a little problem:
Oh yeah. I've suspected something like this... The Problem is: I've saved the guid of a profile according to his select-slide-tag (an internal int-number). Renaming profiles changes the order of profiles and we run into a situation where saved selectedProfile doesn't match the select-slide-tag anymore. As a solution we maybe need to change SelectSlide so that it could hold different values as tag... But this would be very complicated... Other ideas?

>The profile features of the webapp are also broken. I thing there will be a little refactoring required.
Haven't tested it right now...

**Comment by lukeIam** [comment]
> Yeah, still works as expected in my tests? There is only one minor thing: Guest3 isn't a guest... Could you tell me how to reproduce this

ahh - ok if guest 3 is a guest everything works ;)

**Comment by flokuep** [comment]
Yep, done.

I've found a solution for the problem with renaming/adding players. Easier than expected. Please test.

**Comment by flokuep** [comment]
Tried to look into server-problem and noticed: Never worked with it :D Could you try to describe the problem? Quite don't know where to start debugging...

**Comment by z3ro01** [comment]
In webapp go to Administration menu. You cannot edit any profiles (got bad request)
I think the problem is here: 
https://github.com/flokuep/Vocaluxe/blob/player-guid/Vocaluxe/Website/js/main.js#L975
parseInt need to be removed

**Comment by flokuep** [comment]
Yeah, I've noticed the problem; Starting in main.js is a good point, thanks.

**Comment by flokuep** [comment]
Hm. This didn't fixed the problem... Still don't know how to find the bug... Maybe @lukeIam could have a look at it?

**Comment by z3ro01** [comment]
i have tested it. but you need remove parseint in two lines: 949 and 976

**Comment by flokuep** [comment]
Yeah, I've done this too, but don't worked for me. :/

**Comment by z3ro01** [comment]
Please test: 
https://github.com/z3ro01/Vocaluxe/commit/79efa21772003a1bddd59d5f3f487ef924be05a9

**Comment by lukeIam** [comment]
> Maybe @lukeIam could have a look at it?

I'll try but I can't promise it - unfortunately I have to work between Christmas and New Year...

**Comment by lukeIam** [comment]
@z3ro01 

> Please test: 
> z3ro01@79efa21

Looks good!

**Comment by lukeIam** [comment]
> I've found a solution for the problem with renaming/adding players. Easier than expected. Please test.

Also looks good.
Everything I tried was working :smiley:

**Comment by lukeIam** [comment]
Party modes will need refactoring too...

eg. https://github.com/lukeIam/Vocaluxe/blob/player-guid/PartyModes/PartyModeChallenge/CChallengeRounds.cs#L145

**Comment by flokuep** [comment]
No, I think this should work. It's easier to store here just the number of player instead of guid, using guid is done here for example: https://github.com/lukeIam/Vocaluxe/blob/player-guid/PartyModes/PartyModeChallenge/CPartyModeChallenge.cs#L365

**Comment by lukeIam** [comment]
> No, I think this should work. It's easier to store here just the number of player instead of guid, using guid is done here for example: https://github.com/lukeIam/Vocaluxe/blob/player-guid/PartyModes/PartyModeChallenge/CPartyModeChallenge.cs#L365

ok
