### ISSUE TITLE
Android/FireTV support

### ISSUE THREAD

**Issue by t-oster** [Vocaluxe/Vocaluxe#193]
Hi,

this project would be really great running on android based set-top-boxes like the FireTV or Odroid.
I am a linux guy, but not familiar with mono and also not with mono on android. There seem to be some projects, so it is not impossible, but will be not easy either.
On the other hand, getting this project out into the PlayStore/Amazon App store would be a great success. 
I do not have time to do any porting, but if anyone is fiddling with that, this issue could be the point to collect information on the current status.

**Comment by lukeIam** [comment]
In my opinion porting Vocaluxe to Android would be a huge bunch of work.
There is a "mono-for-android" called [Xamarin.Android](https://xamarin.com/platform#android) which is even [free for open source projects](https://resources.xamarin.com/open-source-contributor.html) but nevertheless there would be a lot of things to change and some dependencies to replace.

At the moment we barely find the time for fixing bugs in Vocaluxe and for some small additions from time to time. Don't get me wrong: I would really appreciate having an android support for Vocaluxe (would open great new use cases), but I don't see a realistic chance for that in the near future...

**Comment by derivator** [comment]
I agree with @lukeIam, it's not feasible with the amount of manpower available to us.

**Comment by t-oster** [comment]
I am aware that it will neither be easy nor do you have the power. I opened this issue in case any volunteer/fan/android guru stumbles upon this software and thinks "challenge accepted"... 
I will also try to dig into that, but since my development experience is from totally different systems/languages I do not think I have will have much success.

**Comment by marwin89** [comment]
I close this issue. It's not likely to have this feature implemented in vocaluxe the next years. There are other fundamental things to do. Try Melody Mania or UltraStar Play. They support Android, cause they're build with unity engine. They also planned iOS Support for end of 2023.
