### ISSUE TITLE
Change prioritization of GStreamer installations

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#199]
Currently we are preferring a system installation over the version we ship with the (nightly) releases.
This can lead into problems if the system GStreamer installation is a unsupported version or is missing components (plugins).

If we change to preferring the version in the Vocaluxe lib folder we would have better control over the GStreamer dependency and would make Vocaluxe easier to use.

**Comment by derivator** [comment]
On linux the system version is used anyway, so no change there... On windows, maybe prefer whichever is newer? Can we detect if plugins are missing?

**Comment by lukeIam** [comment]
> On windows, maybe prefer whichever is newer?
I don't know if it would be a good idea - what happens on breaking changes or id just some plugins are missing.

> Can we detect if plugins are missing?
Not easily - We could check for all the plugin files...
