### ISSUE TITLE
Include VocaluxeProblemSolver into releases

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#200]
Just an idea: How about including VocaluxeProblemSolver.exe in the nightly releases - so if someone is missing something it can be directly fixed.
http://forum.ultra-star.de/viewtopic.php?p=68551#p68551

**Comment by derivator** [comment]
Apart from checking for missing .NET, couldn't this functionality be integrated into Vocaluxe itself?

**Comment by lukeIam** [comment]
@derivator: would be an option but we would have to assure that the tests are done before the first native lib is loaded.
It would be nice to have it integrated but I see some problems:

We need to check if the checks can be done without administrative privileges and we would need a second process for applying the fixes or there will be an UAC prompt for every change.
And I'm not sure how to get the SingStar-Mic-Config part in a process with administrative privileges without an additional exe.

Other idea: leave the exe as it is and offer to call it from Vocaluxe if an error occurred.

**Comment by marwin89** [comment]
Hi @lukeIam 👋 Is there still a VocaluxeProblemSolver.exe? Or is it already integrated in the game? I can't find it in vocaluxe 0.4.1 nor in latest nightly (10 Jan 2024).

**Comment by lukeIam** [comment]
was never integrated nor further developed: (I don't know if it still working)
https://github.com/lukeIam/VocaluxeProblemSolver

**Comment by marwin89** [comment]
It still works 🙂  here is a screenshot:
![Vocaluxe-Problem-Solver-Test](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/258ac304-759c-4288-af52-c28afa8de6bd)
- Could you include: https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 (then it's ready for the future)
- Only gstreamer didn't work ❌ 
- I didn't use any singstar mics but looks fine too ✔️ 
- I will do a pull request for merging this into nightly (if you don't have time)

**Comment by marwin89** [comment]
Close this issue as won't do because ProblemSolver ist not active developed anymore. Re-open if needed.
