### ISSUE TITLE
Karaoke mode (center channel suppression)

### ISSUE THREAD

**Issue by skyli91** [Vocaluxe/Vocaluxe#208]
Hi!

I'd like to request this function as i like it from ultrastar deluxe (I'm not sure, maybe the cmd or the normal version has it) and Performous also has it (Ctrl+C).

Thank you! :)

**Comment by lukeIam** [comment]
As it seemed not too difficult (for gstreamer) so I tried implementing it:
[lukeIam:KaraokeMode](https://github.com/lukeIam/Vocaluxe/tree/KaraokeMode)

But it needs further improvement:

- [ ] Disable the audiokaraoke element when KaraokeMode is disabled - atm I just set the effect to `0f` 
-> seems to have performance impacts
- [ ] Create options to adjust the effect
- Only gstreamer is supported atm (using a gstreamer plugin) -> maybe a gstreamer only feature?

**Comment by skyli91** [comment]
Thank you very much! :) can you merge it to the master? :)

**Comment by lukeIam** [comment]
> can you merge it to the master? :)

I thing it will needs improvement before we can merge it to the master brach.
-> the performance problems (even with Karaoke mode turned off) are a dealbreaker

**Comment by lukeIam** [comment]
any gstreamer expert here?
I'm a total beginner here and changing the pipeline dynamically seems to be not that trivial.

I want to add/remove the karaoke element to/from the audio pipeline.
Here is my try (freezing):

```c#
if (!karaokeActive)
{
	_Element.SetState(State.Ready);
	_Pad.AddProbe(PadProbeType.BlockDownstream, (pad1, info) =>
	{
		pad1.RemoveProbe(info.Id);

		_Audiokaraoke.SetState(State.Null);
		_Convert.SetState(State.Null);
		_Audiosink.SetState(State.Null);
		
		_Convert.Link(_Audiosink);
		_Audiokaraoke.Unlink(_Audiosink);
		_Convert.Unlink(_Audiokaraoke);

		_AudioSinkBin.Remove(_Audiokaraoke);

		_Element.SetState(State.Playing);

		return PadProbeReturn.Remove;
	});
}
else
{
	_Element.SetState(State.Ready);
	_Pad.AddProbe(PadProbeType.BlockDownstream, (pad1, info) =>
	{
		pad1.RemoveProbe(info.Id);
		_AudioSinkBin.Add(_Audiokaraoke);
		_Convert.Unlink(_Audiosink);

		_Audiokaraoke.Link(_Audiosink);
		_Convert.Link(_Audiokaraoke);

		_Audiokaraoke.SetState(State.Null);
		_Convert.SetState(State.Null);
		_Audiosink.SetState(State.Null);

		_Element.SetState(State.Playing);

		return PadProbeReturn.Remove;
	});

	_Audiokaraoke["level"] = level;
	_Audiokaraoke["mono-level"] = level;
}
```

**Comment by derivator** [comment]
As an alternate solution, maybe just decide ahead of time if we want karaoke, via a menu or something?

**Comment by lukeIam** [comment]
> As an alternate solution, maybe just decide ahead of time if we want karaoke, via a menu or something?
Good (and simple) idea! I'll implement this and if we find a better solution we can change.

Single contra point: gstreamer only as the effect is done with a gstreamer plugin.

**Comment by derivator** [comment]
> Only contra point for the whole thing: gstreamer only, as the effect is done with a gstreamer plugin.
It would probably be best to not even show the menu option if another backend is selected, otherwise there might be complaints why karaoke isn't working.

**Comment by lukeIam** [comment]
> It would probably be best to not even show the menu option if another backend is selected, otherwise there might be complaints why karaoke isn't working.

FullAck - but is this possible at the moment?

**Comment by flokuep** [comment]
Yeah. Should be. You can check current choosen playback lib from config. If this is Set to gstreamer, show menu entry, otherwise not.

**Comment by lukeIam** [comment]
First implementation: https://github.com/lukeIam/Vocaluxe/commit/49b971d126271d1c3994601e85820d6df1206995

But now to effect is applied globally to all audio out put if active.
Need to get the "this is a song playback for sinning" information" or "apply karaoke" to the audio output.

**Comment by lukeIam** [comment]
Working version (karaoke effect only while playing a song): https://github.com/lukeIam/Vocaluxe/commit/3275aa091eba7aff9d7f4c972fcca91653c26ec6

Todo:

- [ ] Add Translation for the new entry 
- [ ] Increment theme version number?

(if we are touching this we could also some settings for the webserver)

**Comment by flokuep** [comment]
Yes, please increase screen version number and add a hint to changelog.

**Comment by lukeIam** [comment]
@flokuep: can yo help me finding the best way to add TR_SCREENOSOUND_KARAOKEEFFECT to the language files (just changing the files or adding them in some tool?)

**Comment by flokuep** [comment]
When you add it to English.xml, Transifex import it (I guess every night). After this, translator could add a translation... There is a little tool for fetching translations from transifex-server. Config for this is in our git repository (.tx folder)... But this tool had some problems with special chars so we need to manually fix some strings after using it.
