### ISSUE TITLE
"Disable" some nuget packges for linux build

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#212]
as some dependencies are not needed there.

From:
https://github.com/Vocaluxe/Vocaluxe/issues/197#issuecomment-188361685

**Comment by lukeIam** [comment]
Old conversation:

> > Is the code in Vocaluxe/Lib/Video/Acinerella not the right version?
> 
> :grimacing: That would might has helped writing the functions...
> Maybe we should also test if that implementation is even faster then mine (I just tried to get it working).
> 
> > By the way, we should think about adding the customized version to the Vocaluxe repository again, either directly or (preferably, I think) as a git submodule (more complex but also more elegant).
> 
> I would vote for using the direct files.
> Git submodules are not so easy to [handle](https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/)

> > Upgraded version is working on linux, but could we get the dependencies separated by platform? 
> 
> As far as I know there is no possibility to have different nuget dependencies in one single solution.
> 
> >The error conditions won't even let me build unless I have nuget download prebuilt windows only acinerella dlls, which is very annoying in case of a server outage.
> 
> At least under Windows nuget is caching the packages in the (untracked) folder `packages`. So I'm loading every package only once (actually I'm working here with a 3G connection)
> 
> What I can do is:
> - do not copy the files from `packages` to `lib` folder to keep the `lib` folder cleaner
> - add a condition to that error statements - but I'm not sure if then nuget does not recognize them anymore and creates new ones
> 

> > What I can do is:
> > 
> > do not copy the files from packages to lib folder to keep the lib folder cleaner
> > add a condition to that error statements - but I'm not sure if then nuget does not recognize them anymore and creates new ones
> 
> > This also applies to hidapi, gstreamer, ffmpeg, PitchTracker, of course...
> 
> @derivator Please try: https://github.com/lukeIam/Vocaluxe/tree/nugetNoLinuxCopy
> 
> I disabled copying the files to the lib folder and disabled the error on missing this packages:
> 
> - hidapi
> - gstreamer
> - ffmpeg
> - acinerella
> - PitchTracker (this nuget package is currently not used -  windows also builds it from source)
> 
> As already told the nuget packed is always loaded on a restore (but normally from cache) and there is no way around this besides creating an other project.

**Comment by derivator** [comment]
> @derivator Please try: https://github.com/lukeIam/Vocaluxe/tree/nugetNoLinuxCopy

Works, files are not copied to lib folder and although "nuget restore" loads them, they can be deleted without causing errors. :+1: for merge.
