### ISSUE TITLE
Feature Request: Medley Mode

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#219]
It seems like each title in medley mode is being played for about 30sec. (just a feeling).
It would be nice to be able to configure this time. Or can it be steered already in a config file?

**Comment by flokuep** [comment]
There are two ways on settings medley variants: Directly per song with two tags (medleystartbeat and medleyendbeat) and a fallback if these tags aren't set. For this, Vocaluxe trys to figure out the most important part of a song (in best case: refrain) - These are parts that were repeated some times in song. For these parts there is a minimum and maximum length set in vocaluxe itself.
