### ISSUE TITLE
Feature Request: Tic-Tac-Toe

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#220]
Right now there seems to exist just only one joker per team, which cannot be reused after a battle.
It would be nice to be able to configure this like in challenge mode: 
- Amount of jokers
- reset amount of jokers after each turn

Or can it be defined already in a config file?

**Comment by flokuep** [comment]
Currently it isn't cofigurable. Joker-number (and type) increases with number of fields yet. This seems to be the most fair and balanced version.

**Comment by Michri** [comment]
Will it be hard to get it adjusted?

**Comment by flokuep** [comment]
No. If you had some basic ideas of programming concepts and c# (or another high-language like java) you could try it yourself. I could help and give you some first points to look at, if you luke,

**Comment by Michri** [comment]
We had a Vocaluxe session with 6 people and all were wondering about having more jokers.
Maybe it is at least good to think about it again.
