### ISSUE TITLE
Vocaluxe crashes in Medley Party Mode

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#226]
We played with 6 people the Medley mode, but always after a few turns Vocaluxe crashed and was closed. 
When playing with just 2 people we haven't noticed that problem.
Is that a known issue?

**Comment by flokuep** [comment]
Currently not, please give us the error.log after a crash. There might be some hints why this crash happend.

**Comment by Michri** [comment]
Is that error log stored in Vocaluxe folder?

**Comment by flokuep** [comment]
Yes.

**Comment by lukeIam** [comment]
@Michri Any update on this?

**Comment by Michri** [comment]
Sorry, we didn't played again right now. I will try to simulate a session.

**Comment by Michri** [comment]
Yesterday we played again. Then I had a look at the logfile:

Error-Log Vocaluxe "Blue Sunrise" 0.4.0.beta1 (x64) Beta (0.4.0.beta1-19-gafc9172)
...
250) Could not query position
251) Could not query position
252) Could not query position
253) Could not query position
254) Unhandled exception: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.   bei Gst.Element.get_TargetState()
   bei Vocaluxe.Lib.Sound.Playback.GstreamerSharp.CGstreamerSharpAudioStream._Dispose(Boolean disposing)
   bei Vocaluxe.Lib.Sound.Playback.CAudioStreamBase.Finalize()

We played several hours. Medley Mode seems to be problematically. Other modes run more stable.

**Comment by Michri** [comment]
Gerade ist Vocaluxe noch einmal abgestürzt. Leter Log-Eintrag:
Error opening video file (can't find decoder): C:\Songs\DoesYourMotherKnow.avi

**Comment by Michri** [comment]
Gibt's zu diesem Problem etwas Neues?

Hier mal wieder ein Auszug (Error.log):
Error-Log Vocaluxe "Blue Sunrise" 0.4.0.beta1 (x64) Beta (0.4.0.beta1-19-gafc9172) 29.07.2017 23:42:25
----------------------------------------
1) Warning: Automatic changes have been made to C:\!Daten\Singstar Derivate\Songs-SingStar-Session\A-Teens - Mamma Mia\A-Teens - Mamma Mia.txt Please check result!
Adjusted 1 line breaks (Overlapping previous note: 1, No length: 0)
...
651) Could not query position
652) Could not query position
653) Error opening video file (can't find decoder): C:\!Daten\Singstar Derivate\Songs-SingStar-Session\Buggles - Video Killed The Radio Star [VIDEO]\Buggles - Video Killed The Radio Star [VD#0].avi
654) Could not query position
655) Could not query position
656) Could not query position
657) Could not query position
658) Could not query position


Und, wann gibt's eigentich mal eine aktuelle Version?
Die nightly builds sind ja schon sehr alt. Hat sich gar nichts mehr getan?

**Comment by flokuep** [comment]
Aktuell ist leider wenig bis gar keine Zeit für die Weiterentwicklung meinerseits. Nur @lukeIam und @hendrikbl schaffen es hin und wieder ein bisschen am Code oder der Webseite zu arbeiten.

Du kannst es mit der aktuellen Nightly probieren; Dort wurde etwas an der Video-Lib geschraubt; auch wenn da steht, dass die Version von 2015 ist: Der Merge müsste Anfang Juni stattgefunden haben.
