### ISSUE TITLE
Little scrolling bug in PartyModeChallenge*

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#231]
The `1)` stays at the same position while scrolling:
![image](https://cloud.githubusercontent.com/assets/5115160/20537698/5bd1837c-b0ee-11e6-90df-ed9617dde793.png)

**Comment by lukeIam** [comment]
`_RoundsTable[i].Number.Text` looks good and is changed as expected...

**Comment by lukeIam** [comment]
There is definitely an other object with `1)` but I don't know where...

**Comment by flokuep** [comment]
`<Text Name="TextRoundNumber">` has `1)` as default value (lines 178ff in `PartyScreenChallengeMain.xml`. I guess we use this element to get style informations for this table, but it seems to be drawn? You could try to remove `1)` from theme file...

**Comment by lukeIam** [comment]
> You could try to remove 1) from theme file...

You where right: that solves the problem. Thanks!
