### ISSUE TITLE
Theme-Videos in Releases?

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#237]
Currently the videos of the ambient theme are not included in Nightly and all other builds.
But Vocaluxe looks much nicer with the videos 😎 

**Vocaluxe release size without videos**: 116/122MB
**Video size**: 48MB

### Options:

1. Ship no Videos (leave it as it currently is) -> But most people won't download them separately
2. Ship ambient videos with all builds
3. Ship ambient videos only with builds for tags (only for releases, exclude PR/Nightly/...)
 -> But at least atm many people are using the Nightly...
4. Add an Additional-Files-Url to the theme and ask the user if he wants to download the missing files/videos (white listed urls)

What do you think?

**Comment by lukeIam** [comment]
@flokuep @derivator

**Comment by flokuep** [comment]
I prefer option 2. 50 MB more or less isn't a big problem anymore... Earlier versions of vocaluxe were smaller, so shipping videos or not was a important question...
