### ISSUE TITLE
Sporadic crashes when loading video

### ISSUE THREAD

**Issue by Jiiniasu** [Vocaluxe/Vocaluxe#241]
Hello.

This is probably the source of the crashes reported in #206.

In one of my branches I've (in the most ugly way) made a custom build for a LANparty where one of the modifications was instant previews when browsing (removing the need of pressing enter to start preview of song). This lead to more frequent crashing of Vocaluxe logging the error **Error opening video file (can't find decoder): <filename>**.

I've been digging a bit and have come to the following conclusion:

Below line somehow, sometimes, seemingly at random, throws a nullReferenceException. Occasionally, it can be recovered by running the same line again. Other times, it won't.

`decoder = (SACDecoder)Marshal.PtrToStructure(_Videodecoder, typeof(SACDecoder));`
(https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Lib/Video/Acinerella/CDecoderThread.cs#L277)

**Edit:** The _Videodecoder variable also seemed to have a valid pointer when it crashes. All I can say is that it wasn't 0.

Have anyone got any ideas on how to figure out a solution for this bug or any plausable theories on why this happens?

This crash has been observed mostly during previews when browsing songs, but has also occurred as early as when loading the intro videos.

**Comment by lukeIam** [comment]
Hi @Jiiniasu ,
thanks for reporting 😃 

Hmm sounds like a bug in the unmaged Acinerella-part.  
Can you please provide some addition information?
- Does it always occur with the same files? same format? some none ASCII chars in the path to the file? length of these files?
- The whole exception (with innerexceptions) would be helpful

Also worth the try:
- remove the return false from the exception handler
- set a break point to the exception handler
- On breakpoint hit:
  - step out of the exception handler
  - `Set the next statement` to the begin of the try block
  - See if the exception occurs again

**Comment by lukeIam** [comment]
if you have time you can also try out https://github.com/Vocaluxe/Vocaluxe/issues/197 and see if it is also occurring there...

**Comment by Jiiniasu** [comment]
The crash occurs with any file. I have not noticed any pattern. Videos located in paths with only ascii chars are also affected. (Such as the loading screen intro videos.)

Couldn't get it to build when only removing return false;, but adding throw e; in place of it gave me the stuff below.

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Vocaluxe
  StackTrace:
       at Vocaluxe.Lib.Video.Acinerella.CDecoderThread._OpenVideoStream() in C:\Users\Jiiniasu\Source\Repos\Vocaluxe\Vocaluxe\Lib\Video\Acinerella\CDecoderThread.cs:line 284
       at Vocaluxe.Lib.Video.Acinerella.CDecoderThread._Execute() in C:\Users\Jiiniasu\Source\Repos\Vocaluxe\Vocaluxe\Lib\Video\Acinerella\CDecoderThread.cs:line 406
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

Trying to set the next statement fails, and I am clueless as I have no idea how this works. =D

![image](https://cloud.githubusercontent.com/assets/1884464/21157831/2bc46724-c17b-11e6-9604-d57389a1fd8b.png)

I'll give #197 a shot to see if it also crashes.

**Comment by Jiiniasu** [comment]
I've given #197 a quick spin and interestingly enough it does not seem to crash (yet?), although it does instead have video artifacts (blocks/glitches) every now and then.

**Comment by lukeIam** [comment]
> Trying to set the next statement fails, and I am clueless as I have no idea how this works. =D

In some situations it just do not work 😁 
Especially in try-catch-blocks.


> I've given #197 a quick spin and interestingly enough it does not seem to crash (yet?), although it does instead have video artifacts (blocks/glitches) every now and then.

It uses newer lib version, but it was build by Trial & Error...

**Comment by lukeIam** [comment]
@Jiiniasu Can you share your modified version? And maybe a song the problem is occurring with?
![e2b27f7c94c1f1237a8d7f17417cc6fa](https://cloud.githubusercontent.com/assets/5115160/21221735/d95cbb18-c2be-11e6-82de-aaec35874050.png)

**Comment by Jiiniasu** [comment]
@lukeIam Well, the modified version is [https://github.com/Jiiniasu/Vocaluxe/tree/develop-dodgy-bodgy](https://github.com/Jiiniasu/Vocaluxe/tree/develop-dodgy-bodgy), but it's full of other irrelevant and ugly modifications. (Code may cause tears of blood, but hey, it's a bodge-build for a **very** specific use.)

You can however make the error easier to reproduce by just lightly modifying [CSongMenuList.cs](https://github.com/Vocaluxe/Vocaluxe/blob/develop/VocaluxeLib/Menu/SongMenu/CSongMenuList.cs). Just add `_PreviewNr = _SelectionNr;` after _SelectionNr has been altered [in the keypress handling](https://github.com/Vocaluxe/Vocaluxe/blob/develop/VocaluxeLib/Menu/SongMenu/CSongMenuList.cs#L396-L443).

With this modification you'd experience crashes after some browsing in the songs list as the amount of videos it will load will skyrocket. The procedure to provoke the error is usually just holding an arrow key to flick through the entire library and reverse if you manage to get to the bottom.

Unmodified you'd have to press enter after every selection change for the same result, but with a lot more manual labour.

Regarding specific songs, I don't think I'd be able to isolate specific extra troublesome songs. Happens randomly across all my ~680 songs (with exception of the few ones without video I guess). But if you want I could of course provide you the files of which I know Vocaluxe has crashed at least once.

**Comment by lukeIam** [comment]
@Jiiniasu Thanks for the input 
(I will try to reproduce, but I only have about 5 Test songs here on my laptop 😉 )

Just an Idea: does it happen while fast browsing? It could be that we my reach some limit of concurrent decoders (they need some time to setup and destroy).

I think that we already talked about a auto-preview feature (but I can't really remember when and where).
The conclusion was to start it after ~0.5 sec after the cursor is moved on the song - so fast browsing does not span so many decoders.  

P.S.: I don't know what happened to that (optional) auto-preview feature... It should not be much work and it is nice to use.

**Comment by Jiiniasu** [comment]
Hi,
I don't think it is directly connected to fast browsing as it has crashed even when browsing slowly and without the instant preview modification.

Also I am most curious on what makes #197 not crash. (I applied the previous mentioned mod to it as well.) Looking at the differences between develop and newAcinerella branches it makes me suspect that the issue may be in Acinerella...

**Comment by lukeIam** [comment]
@Jiiniasu 
tried your branch with the autoselect modification but the only thing I can achieve is a serious lag/freeze.
But no crash at all.
Maybe I would need more different videos (I try to get my hands on some more songs)

> makes me suspect that the issue may be in Acinerella...

I fear...
Sadly I'm not deep enough in acinerella/ffmpeg to finish newAcinerella (#197) on my own.

**Comment by Jiiniasu** [comment]
I just realised you can "easily" provoke the error without any modifications by holding Ctrl + R down to let it randomly pick a song ad infinitum in the song selection screen. Was able to reproduce the error in the latest nightly build binaries.

**Comment by lukeIam** [comment]
> I just realised you can "easily" provoke the error without any modifications by holding Ctrl + R down to let it randomly pick a song ad infinitum in the song selection screen. Was able to reproduce the error in the latest nightly build binaries.

Thanks!
I was able to reproduce the crash with your version (but while deleting a decoder)

@derivator @flokuep 
Which ffmpeg version do I need to build "our" current Acinerella version?
(I need a windows build with debug symbols)

**Comment by derivator** [comment]
> Which ffmpeg version do I need to build "our" current Acinerella version?

If by "current" you mean the non-updated one (as opposed to the one from the newAcinerella branch), honestly, I don't know... I had to merge newAcinerella to get it to build on linux with the newest ffmpeg.

**Comment by lukeIam** [comment]
> If by "current" you mean the non-updated one (as opposed to the one from the newAcinerella branch), honestly, I don't know... I had to merge newAcinerella to get it to build on linux with the newest ffmpeg.

Should be something around 1.1.16-1.2.12 but I can't get it working (I can compile Acinerella but Vocaluxe is not showing any video).
Maybe it would be better to try to get newAcinerella ready for production.

**Comment by lukeIam** [comment]
@Jiiniasu  
I dived deep in ffmpeg and tried to get newAcinerella ready (see #197)
If you find time can you please test if you still have those artifacts (or other bugs)?

**Comment by Jiiniasu** [comment]
@lukeIam I've given the new stuff a spin (hopefully in the correct way). Unfortunately I still have artifacts which covers from little/none to lots of the frame and the videos seems to be off-sync with the audio. =(
(The sync was apparently off in the previous build as well.)

Example of the artifacts:
![2016-12-16](https://cloud.githubusercontent.com/assets/1884464/21278551/2460b9ac-c3dc-11e6-8a8c-4b1cfef4a994.png)

**Comment by Jiiniasu** [comment]
@lukeIam Not sure if I'm stupid or anything, but I tried this again with the provided binaries in #197 and chucked the newer DLLs into it. This works fine in contrast to my build of the same. No artifacts and no sync problems...

**Comment by lukeIam** [comment]
@Jiiniasu 
Could be my mistake: I forgot to write that you have to rebuild to copy those injected files to the output.

The other option is to use the binary build and copy all files to `\libs\unmanaged` (without folder structure).
Was that your approach?  
(Technically there should be no difference to the first option + rebuilding.)

> This works fine in contrast to my build of the same. No artifacts and no sync problems...

That sounds good 😃

**Comment by Jiiniasu** [comment]
@lukeIam Yeah, it worked for me when I did the "other option". Also confirmed working well with a proper clean and rebuild this time. =)

**Comment by lukeIam** [comment]
Created nuget packages for the new version and updated [lukeIam/Vocaluxe:newAcinerella](https://github.com/lukeIam/Vocaluxe/tree/newAcinerella) to use them.

There are also a compiled test-versions (so please test 😉 ):
https://ci.appveyor.com/project/lukeIam/vocaluxe/build/49

**Comment by lukeIam** [comment]
@flokuep @derivator @Jiiniasu 
The question now is how to proceed with this issue
(as we are having some kind of code freeze till the release):

1. Fix it with #248 before the release - it's fixes the Bug but it's more than that 
(Tests look good so far but I don't know how stable it is)
2. Don't fix it, just try to prevent the crash of the whole program: catch the exception and continue without the video in case the bug occurs
3. Do nothing (maybe not the best option 😉 )

**Comment by flokuep** [comment]
Just tested a bit... Seems to work nice (and better than before?)- So why not, I go with 1...

**Comment by Jiiniasu** [comment]
Tested for a little while and it seems to work great. I'd aim for option 1.

**Comment by lukeIam** [comment]
Thanks for testing! 
btw: Are there any other bugs preventing a Christmas release?

**Comment by Jiiniasu** [comment]
Just wanted to throw in a word regarding stability of the preferred fix; It seems rock solid on Windows. I've run a build which included #248 and the modification to instantly play previews when browsing. It was free from crashes for the entire duration of a ~12-hour long session with lots of browsing.

**Comment by flokuep** [comment]
Thanks for your feedback!

**Comment by AlecScudder** [comment]
I did not see this thread before and I actually tried making the very same modification (instant preview) on my own. My friends have been clamoring for this feature when we play. But the code changes I made result in a big increase in crashes as well. 

So I found this thread and it sounds like there is a version of Vocaluxe with this feature available without crashing based on the last few comments. And I have seen comments before about "nightly builds" yet it seems the most recent code is from last December. I thought I had the latest version of the project code from Github. How can I get auto-preview without causing it to crash all the time?

**Comment by lukeIam** [comment]
Hi @AlecScudder 

we are all very busy at the moment, so unfortunately we don't have time to work on Vocaluxe. 😞 
If you want you can checkout my work in progress code (for this issue) here: https://github.com/lukeIam/Vocaluxe/tree/newAcinerella
Or just try the automatic build based on that code here: https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/build/105-mpvbybxt/job/0d5uh0bed52qado5/artifacts

Is that what you have been looking for?

**Comment by AlecScudder** [comment]
@lukeIam  - thanks. Unfortunately, I cannot use your build as is because I have made changes to my version (see #255) to allow me to mimic the SingStar "Co-Op" mode which is how my friends prefer to play. And quick attempts to get your code to build result in an error for me that causes Vocaluxe.exe not to be created:

_The specified version string does not conform to the required format - major[.minor[.build[.revision]]]_

I will try to play around with it when I get more time. If I can get your code to build, my change for #255 is extremely simple so I'll get the best of both worlds.

I appreciate any/all efforts you guys can make to work on Vocaluxe. I only discovered it recently and it is the greatest!!!

**Comment by lukeIam** [comment]
> The specified version string does not conform to the required format - major[.minor[.build[.revision]]]

Try to reset the `AssemblyInfo.cs` file:
https://github.com/Vocaluxe/Vocaluxe/blob/ae656ba7273a90b1b9f21122a9e07017018a2062/Vocaluxe/Properties/AssemblyInfo.cs

> I appreciate any/all efforts you guys can make to work on Vocaluxe. I only discovered it recently and it is the greatest!!!

Thanks! I hope I will find more time for it in the future...

**Comment by flokuep** [comment]
According assembly message: is git installed correctly? We use it to generate our version number (add latest commit hash)...

**Comment by AlecScudder** [comment]
Got it working and it seems more stable with brief testing. Thanks!

**Comment by AlecScudder** [comment]
OK, now it is not working again and I have no idea how I got it to work the first time. Every time I try to build I get that error. I don't get this on the main Vocaluxe solution. Just the one Luke published. I even tried re-starting in a new folder and new solution following the Vocaluxe wiki instructions for getting a project off Github. It pulls everything from Github, but I still get that error when I try to build. 

6 things build successfully and 2 fail due to the error above. I compared the AssemblyInfo.cs file luke posted separately and it is the same as the one in the project. Unfortunately, I cannot just take Luke's build because I have my own change that I make to the code to make duets easier.  

The ability to preview the songs like this would be a HUGE bonus for my friends, and I'm having people over for a party this weekend!

Any suggestions?

**Comment by Jiiniasu** [comment]
@AlecScudder I previously had issues like that when trying to setup the dev environment on my laptop. In my case I just had to make sure [git](https://git-scm.com/download/win) was installed properly on the machine.

**Comment by AlecScudder** [comment]
I don't understand. Git seems built into Visual Studio (I tried 2015 and 2017). I am using Git to download the code from this site. I tried uninstalling VS 2015, installing 2017 - no luck. Reinstalling 2015 now. Is there something extra that needs to be installed for git? How do I know if it is installed correctly?

**Comment by Jiiniasu** [comment]
@AlecScudder Try install git from [https://git-scm.com/downloads](https://git-scm.com/downloads). If you are able to run the command _git_ in a command line without getting _'git' is not necognized as an internal or external command, operable program or batch file._ then you should be set I believe.

**Comment by AlecScudder** [comment]
Yes, I am able to run it command line. I have tried uninstalling VS 2015. Installing VS 2017 which had more errors. So I removed that and re-installed VS 2015 from scratch, plus git (tried both 32 and 64 bit versions). Each time, I'm re-cloning the project into a new repo. And I *still* get the same error with the AssemblyFileVersion and 2 of the 8 things fail to build. Is there some other way around this?

**Comment by AlecScudder** [comment]
I want to repeat, also, that the main Vocaluxe project builds fine each time so I don't think the issue is just Git.

**Comment by Jiiniasu** [comment]
@AlecScudder 

Is the "main Vocaluxe project" you refer to the **develop** branch?

What do you get if you open a powershell prompt, change directory to the repository and run `git describe --long`?

This is what I get from a machine which compiles just fine:
```
PS C:\Users\Jiiniasu> cd C:\Users\Jiiniasu\Source\Repos\Vocaluxe\
PS C:\Users\Jiiniasu\Source\Repos\Vocaluxe> git describe --long
0.4.0.beta1-15-gf7c3a31
```

Have you also tried **Build > Clean Solution** and **Build > Rebuild Solution** in Visual Studio?

**Comment by AlecScudder** [comment]
Yes, tried Build>Clean and Build>Rebuild several times. Along with reinstalling git.

OK, tried on a second computer just to be sure. When I run git describe on main vocaluxe (develop) it shows:

0.4.0.beta1-19-gafc9172f

When I run the same command on your repo I get this:

_fatal: No annotated tags can describe 'afc9172f97480a2d52b603b4efb3dfab53120203'. 
However, there were unannotated tags: try --tags._

When I install git, I am just leaving the defaults... are there perhaps some settings in there that I need to change/choose differently to make yours work that the "regular" Vocaluxe doesn't need?

![image](https://cloud.githubusercontent.com/assets/24832425/26476075/1e331512-418a-11e7-9716-88009b95b071.png)

![image](https://cloud.githubusercontent.com/assets/24832425/26476083/28d088b0-418a-11e7-8b68-be7076a3f187.png)

![image](https://cloud.githubusercontent.com/assets/24832425/26476090/35d1d7b2-418a-11e7-9c43-f8f00b71b49f.png)

![image](https://cloud.githubusercontent.com/assets/24832425/26476094/3eaeb0c6-418a-11e7-869f-085a9f1836c2.png)

![image](https://cloud.githubusercontent.com/assets/24832425/26476101/47ae738c-418a-11e7-879d-9e96afa27b3c.png)

![image](https://cloud.githubusercontent.com/assets/24832425/26476109/4f2964e6-418a-11e7-9da6-a1e026801543.png)

**Comment by AlecScudder** [comment]
**MAIN VOCALUXE (DEVELOP)**

C:\Users\tim\Source\Repos\Vocaluxe>git describe --long
0.4.0.beta1-19-gafc9172f

**YOUR CODE**

C:\Users\tim\Source\Repos\VocaluxeNewAcinerella>git describe --long
fatal: No annotated tags can describe 'afc9172f97480a2d52b603b4efb3dfab53120203'.
However, there were unannotated tags: try --tags.

C:\Users\tim\Source\Repos\VocaluxeNewAcinerella>git describe --tags
untagged-0a3d623932b4e7510614

**Comment by lukeIam** [comment]
Your second repository is missing tags.
(did you create it with git clone?)

Try to fix that with:
`git fetch --tags`

**Comment by AlecScudder** [comment]
@lukeIam  I really appreciate you taking the time to try to help with this. But, yes -these were created by cloning from git. (https://github.com/lukeIam/Vocaluxe/tree/newAcinerella). 

Unfortunately, fetching tags did not work, either.  Here is what I tried:


_C:\Users\tim\Source\Repos\Vocaluxe2017>git describe --long
fatal: No annotated tags can describe 'afc9172f97480a2d52b603b4efb3dfab53120203'.
However, there were unannotated tags: try --tags.

C:\Users\tim\Source\Repos\Vocaluxe2017>git fetch --tags

C:\Users\tim\Source\Repos\Vocaluxe2017>git describe --long
fatal: No annotated tags can describe 'afc9172f97480a2d52b603b4efb3dfab53120203'.
However, there were unannotated tags: try --tags.

C:\Users\tim\Source\Repos\Vocaluxe2017>git fetch --tags https://github.com/lukeIam/Vocaluxe.git
From https://github.com/lukeIam/Vocaluxe
 * branch              HEAD       -> FETCH_HEAD

C:\Users\twilson\Source\Repos\Vocaluxe2017>git describe --long
fatal: No annotated tags can describe 'afc9172f97480a2d52b603b4efb3dfab53120203'.
However, there were unannotated tags: try --tags._

**Comment by AlecScudder** [comment]
@lukeIam  OK I decided to just use the unmanaged DLL's from your build and copy them into mine (which I updated the code to do auto preview) and it worked!  I only have 40 songs on my test machine here but I held CTRL+R for over a minute and no crashes. I also tried fast scrolled with arrow keys up and down a bunch of times and it seems very stable. Good job on updating Acinerella. I think it will prevent the sporadic crashes I was experiencing even without the fast video preview.  Yay!

**Comment by lukeIam** [comment]
Please try
`git fetch --tags https://github.com/Vocaluxe/Vocaluxe.git`

**Comment by lukeIam** [comment]
> OK I decided to just use the unmanaged DLL's from your build and copy them into mine (which I updated the code to do auto preview) and it worked!

👍  interesting! But I can't grantee that those different versions work together without problems 😉 

> I only have 40 songs on my test machine here but I held CTRL+R for over a minute and no crashes. I also tried fast scrolled with arrow keys up and down a bunch of times and it seems very stable. Good job on updating Acinerella. I think it will prevent the sporadic crashes I was experiencing even without the fast video preview. Yay!

I'm happy to hear that 😃
