### ISSUE TITLE
More advanced BackgroundSongPlayer

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#242]
Add more options to the BackgroundPlayer:
- Limit to playlist/category 
- Random selection (is is random in the current implementation?)
- Only n seconds per song
- Only play Refrain-Part (Medley-Mode)
- Option to start a song directly (without PlayerSelection)  
Maybe with a smooth rewind transition effect to singing screen
- Fading between songs (do we have fading in current implementation?)
- Preload the next song to avoid gaps caused video loading

**Comment by marwin89** [comment]
This issue is related to:
- #452 

I'll add these ideas to it and close this issue.
