### ISSUE TITLE
Include Genius-Theme into Releases

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#245]
https://github.com/Jiiniasu/Vocaluxe-Genius-Theme

Of cause only if @Jiiniasu agrees 😉 

![image](https://cloud.githubusercontent.com/assets/5115160/21238177/4a95b9f4-c302-11e6-8f2e-a5bf6fa60d4f.png)

**Comment by Jiiniasu** [comment]
@lukeIam I approve of this. ;D

**Comment by Jiiniasu** [comment]
On a little more serious note, I believe the party modes layout/design have to be checked if this is to be an official part of Vocaluxe. The party modes looks a bit weird with my theme graphics.

**Comment by flokuep** [comment]
Yeah, i think this theme Looks really nice. But I think we should drop ambient then... Supporting two different themes is too much work I guess.

**Comment by flokuep** [comment]
Done, see #256
