### ISSUE TITLE
Performance improvements while singing

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#249]
If I choose 6 Players on the PlayerSelectionScreen I immediately feel that the performance goes down (same on the SingingScreen) - sometimes Vocaluxe freezes completely.
With lags lyrics and sound get out of sync.

Note: I only have two microphones while having six active players maybe that could also cause a problem.

Intel Core i5-3210M with HD4000 graphics + 10GB of RAM
using `<RecordLib>PortAudio</RecordLib>` and PitchTracker

Note: I restructured and resorted this issue as it was not in a good form.

**Comment by lukeIam** [comment]
I've done a little research with 100% is all code usage of Vocaluxe,  `PtAKF::_GetNote()` takes `46.52%`.
That's more even more than our (CPU-only) video decoder `29.59 %`.
Is that normal?

**Comment by lukeIam** [comment]
![image](https://cloud.githubusercontent.com/assets/5115160/21365349/54a668fc-c6f5-11e6-8592-ed5abb0d1710.png)

[Report.zip](https://github.com/Vocaluxe/Vocaluxe/files/664578/Report.zip)

**Comment by lukeIam** [comment]
I tried to speed up the bottleneck in PitchTracker a bit:
https://github.com/lukeIam/Vocaluxe/tree/PT_ABS_SPEEDUP

As I don't have absolute numbers I can't calculate a speedup, but the percentage of PtAKF::_GetNote() from Vocaluxe total CPU use decreased by ~ factor 8.

No freezes anymore (at least for me) - debug build with small lag and release build without lag 😃

**Comment by lukeIam** [comment]
> Another question: Why is Vocaluxe.Lib.Video.Acinerella.CDecoderThread::_Decode active and using so much CPU if the song has no video (only BG image)?

Looks like a profiler bug (with dotTrace its only the sleeping background video thread)

**Comment by flokuep** [comment]
I'm not very familiar with these parts of vocaluxe, but @Flamefire has done a lot of work there... Have you seen the test for PitchTracker? https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Lib/Sound/Record/PitchTracker/CPitchTrackerTest.cs

**Comment by lukeIam** [comment]
> I'm not very familiar with these parts of vocaluxe, but @Flamefire has done a lot of work there... Have you seen the test for PitchTracker?

No I haven't  - I'll have a look tomorrow.

And I will restructure this issue (it's a bit messed up - sorry)

**Comment by lukeIam** [comment]
> Have you seen the test for PitchTracker?

I tried to use the PitchTracker tests, but most of them require additional input files to work (which I couldn't find in the repo).
But I did `TestSines` and `TestSpeed` with and without my little PitchTracker modification (both on Release setting):

Without modification:
```
Testing notes C2 - B5
Note D2(1) at buffer 6/8 detected as C#2(!); 
Note D#2(1) at buffer 5/8 detected as D2(!); 
Note E2(1) at buffer 6/8 detected as D#2(!); 
Note B2(1) at buffer 5/8 detected as A#2(!); 
Note D#3(1) at buffer 5/8 detected as D3(!); 
Note C#2(2) at buffer 5/8 detected as C2(!); 
Note C2(3) at buffer 6/8 detected as C#2(!); 
Note C#2(3) at buffer 6/8 detected as D2(!); 
Note D2(3) at buffer 5/8 detected as C#2(!); 
Note C2(4) at buffer 8/8 detected as C#2(!); 
Note D2(4) at buffer 7/8 detected as C#2(!); 
Note D#2(4) at buffer 6/8 detected as D2(!); 
Note A#5(4) at buffer 5/8 detected as E6(!); 
Note A#5(4) at buffer 6/8 detected as C6(!); 
Note A#5(4) at buffer 7/8 detected as C#6(!); 
Note A#5(4) at buffer 8/8 detected as E6(!); 
Note C#2(7) at buffer 8/8 detected as C2(!); 
Note F#3(7) at buffer 5/8 detected as inv.(!); 
Errors Sines: 18 of 1920
Finished: 
CAnalyzer: Errors=18 Passed=1902 Total=1920 Speed=1462kSamples/s (=33rec.s/s)
```

With modification:
```
Note D2(1) at buffer 6/8 detected as C#2(!); 
Note D#2(1) at buffer 5/8 detected as D2(!); 
Note E2(1) at buffer 6/8 detected as D#2(!); 
Note B2(1) at buffer 5/8 detected as A#2(!); 
Note D#3(1) at buffer 5/8 detected as D3(!); 
Note C#2(2) at buffer 5/8 detected as C2(!); 
Note C2(3) at buffer 6/8 detected as C#2(!); 
Note C#2(3) at buffer 6/8 detected as D2(!); 
Note D2(3) at buffer 5/8 detected as C#2(!); 
Note C2(4) at buffer 8/8 detected as C#2(!); 
Note D2(4) at buffer 7/8 detected as C#2(!); 
Note D#2(4) at buffer 6/8 detected as D2(!); 
Note A#5(4) at buffer 5/8 detected as E6(!); 
Note A#5(4) at buffer 6/8 detected as C6(!); 
Note A#5(4) at buffer 7/8 detected as C#6(!); 
Note A#5(4) at buffer 8/8 detected as E6(!); 
Note C#2(7) at buffer 8/8 detected as C2(!); 
Note F#3(7) at buffer 5/8 detected as inv.(!); 
Errors Sines: 18 of 1920
Finished: 
CAnalyzer: Errors=18 Passed=1902 Total=1920 Speed=1828kSamples/s (=41rec.s/s)
```
