### ISSUE TITLE
DLLs missing (libtag)

### ISSUE THREAD

**Issue by flokuep** [Vocaluxe/Vocaluxe#253]
I've currently tested vocaluxe on a (nearly) clean windows installtion. Only .NET-framework was installed. When starting vocaluxe, I get two error-messages:

> Der Prozedureinsprungpunkt "__gxx_personality_sj0" wurde in der DLL "C:\Users\Florian\Git\Vocaluxe\Output\libs\unmanaged\gstreamer64\lib\gstreamer-1.0\libgsttaglib.dll" nicht gefunden. 

> Der Prozedureinsprungpunkt "__gxx_personality_sj0" wurde in der DLL "C:\Users\Florian\Git\Vocaluxe\Output\libs\unmanaged\gstreamer64\bin\libtag.dll" nicht gefunden. 

Can someone confirm this bug? I don't really noticed problems with this message...

**Comment by lukeIam** [comment]
looks more like the DLLs  are there but in mismatching versions 😕 

Did you used a special build?

**Comment by flokuep** [comment]
No. Error occurs when building by myself and trying builds from appveyor.

**Comment by lukeIam** [comment]
> No. Error occurs when building by myself and trying builds from appveyor.

Hmm - the error could be caused by `different exception handling implementations`  
http://myprogrammingnotes.com/undefined-reference-__gxx_personality_sj0.html

**Comment by lukeIam** [comment]
@flokuep maybe installing vc++redist is also worth a try

**Comment by flokuep** [comment]
> maybe installing vc++redist is also worth a try
is already installed because of visual studio installation... installer doesn't let me do this again.

**Comment by lukeIam** [comment]
My best guess: libtag was build with a different version of gcc than the other gstreamer/gstreamerSharp libs - resulting into different and incompatible exception models (I think there was a change of the defaults from gcc 3 to gcc 4).  
But I'm not an expert here...
> The question is why it is only happening on your system?  

Could it be that you try to load tags from a mp3 file with invalid tags? This would result into an exception and as the exception handling mechanism is the wrong one you get this error.. ?

**Comment by flokuep** [comment]
I will check this later today, maybe I can get my hands on some different systems... Currently setting up linux to check new acinerella...

**Comment by lukeIam** [comment]
@flokuep is this still up to date?

**Comment by flokuep** [comment]
Yeah. Still have this problem; also without loading songs, so problematic tag header couldn't be the problem

**Comment by lukeIam** [comment]
Just a try:
Is the file `LIBSTDC++-6.DLL` present in `C:\Users\Florian\Git\Vocaluxe\Output\libs\unmanaged\gstreamer64\lib\gstreamer-1.0\` ?

**Comment by flokuep** [comment]
No, this one is missing.

**Comment by lukeIam** [comment]
> No, this one is missing.

It should be there... 😉 
(the dependency zip contains the file, but nuget is only downloading it when the folder does not already exists)
![image](https://user-images.githubusercontent.com/5115160/29373819-a898661a-82af-11e7-87fe-7fe90bfd1d07.png)

Try deleting `libs\unmanaged\gstreamer64\` and rebuilding.
But ci build should be fine:
![image](https://user-images.githubusercontent.com/5115160/29374049-64a3f23e-82b0-11e7-981d-3a1e9b7d45c8.png)

**Comment by flokuep** [comment]
Your screenshots shows that dll is in **bin** folder, but not in **lib** (there isn't it...)

**Comment by lukeIam** [comment]
my mistake - sorry...
it should be in `libs\unmanaged\gstreamer64\bin`

**Comment by flokuep** [comment]
Okay. Found it there and is (as you said) also in ci build (that doesn't run without error message, too)

**Comment by lukeIam** [comment]
> Okay. Found it there and is (as you said) also in ci build (that doesn't run without error message, too)

Strange... 

Do you have an other 'LIBSTDC++-6.DLL' in path?
Try `where LIBSTDC++-6.DLL` in a command prompt.

**Comment by flokuep** [comment]
Okay. Found it there and is (as you said) also in ci build (that doesn't run without error message, too)... So it must be something different.

**Comment by flokuep** [comment]
Output is 

`C:\Qt\5.7\mingw53_32\bin\libstdc++-6.dll`
`C:\Qt\Tools\mingw530_32\bin\libstdc++-6.dll`
`C:\Program Files\Haskell Platform\8.0.1\mingw\bin\libstdc++-6.dll`

Maybe there is a conflict somewhere? Should I remove these paths from envvar to check it? 🤔

**Comment by lukeIam** [comment]
> Maybe there is a conflict somewhere? Should I remove these paths from envvar to check it? 🤔

Maybe... 
It shouldn't - the version in the same folder should be preferred.
But I found a post on the Internet where removing the paths from `%PATH%` was the solution...

**Comment by flokuep** [comment]
Yeah. Removing them fixes it. Anything we could do on our side to fix it? Otherwise I would close this issue.

**Comment by lukeIam** [comment]
> Yeah. Removing them fixes it. Anything we could do on our side to fix it? Otherwise I would close this issue.

No really - the os decides where to search:

> Before the system searches for a DLL, it checks the following:
> 
> - If a DLL with the same module name is already loaded in memory, the system uses the loaded DLL, no matter which directory it is in. The system does not search for the DLL.
> - If the DLL is on the list of known DLLs for the version of Windows on which the application is running, the system uses its copy of the known DLL (and the known DLL's dependent DLLs, if any). The system does not search for the DLL. For a list of known DLLs on the current system, see the following registry key: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\KnownDLLs.

> [...] the search order is as follows:
> 
> - The directory from which the application loaded.
> - The system directory. Use the GetSystemDirectory function to get the path of this directory.
> - The 16-bit system directory. There is no function that obtains the path of this directory, but it is searched.
> - The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
> - The current directory.
> - The directories that are listed in the PATH environment variable. Note that this does not include the per-application path specified by the App Paths registry key. The App Paths key is not used when computing the DLL search path.

(both from https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx#search_order_for_desktop_applications)

I guess the `LIBSTDC++-6.DLL` is already loaded and the first point of the first paragraph applies.
