### ISSUE TITLE
Symbol-Bedeutung

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#257]
Hallo,
ich frage mich, welche Bedeutung die Symbole in der Titel-Übersicht haben?
 
![symbole](https://cloud.githubusercontent.com/assets/20970069/21573172/ac174716-cee1-11e6-8920-5a083c1f109c.jpg)

**Comment by flokuep** [comment]
Die Kamera bedeutet, dass ein Video vorhanden ist. Das Icon rechts zeigt an, dass ein Medley-Part berechnet wurde. Es gibt das Icon ebenfalls mit einer Raute #, dies bedeutet, dass der Medley-Part über Tags gesetzt wurde.
