### ISSUE TITLE
Titel-Sortierung

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#258]
Hallo,
ich habe in den Einstellungen als Sortierung "Hinzugefügt am" ausgewählt. Nun hätte ich erwartet, dass meine zuletzt generierten Titel entweder am Anfang oder am Ende der Titel-Liste stehen. Wonach oder wo wird den die Sortierung vorgenommen?

**Comment by flokuep** [comment]
Es wird das Datum genommen, an dem Vocaluxe den Song zum ersten Mal im Song-Ordner gefunden hat (sprich ein Eintrag in der Covers.db [oder Highscore.db] angelegt wurde).
