### ISSUE TITLE
Tic Tac Toe Party Game mit Spiel-Modus Duett: Kein Duett - BUG?

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#268]
Ich habe gerade den Modus ausprobiert:

![image](https://cloud.githubusercontent.com/assets/20970069/21752640/82431558-d5dc-11e6-9fb5-0937ba7228d7.png)

es scheint nur nicht wirklich ein Duett zu laufen. Es wird ein Titel dann nur für ca. 30sec gespielt, ähnlich dem Medley Mode. Es erscheint ebenfalls der Zähler, der von 8 herunter zählt, bis der Text gesungen werden muss.
Benutze ich den Modus gff. falsch?

**Comment by flokuep** [comment]
Ist ein Bug - Vielleicht Dank fürs melden. Habe ich bereits gefixed und wird bald im Nightly landen.

**Comment by Michri** [comment]
Woran kann ich erkennen, ob's im Nightly drin ist?

**Comment by flokuep** [comment]
Sobald #288 gemerged ist.
