### ISSUE TITLE
Option to adapt playback tone pitch for own voice

### ISSUE THREAD

**Issue by hofst** [Vocaluxe/Vocaluxe#272]
It would be awesome to have the option to adapt the playback tone pitch of a song while singing in real-time (e.g. via ctrl+plus/ctrl+minus). There are so many songs that are fun to sing but just don't quite fit the pitch of one own's voice.

**Comment by marwin89** [comment]
After 6 years of inactivity I close this issue. There seems to be no interest among coders to implement this request.
