### ISSUE TITLE
BuildBot says latest nightly is from 2015

### ISSUE THREAD

**Issue by BenKmann** [Vocaluxe/Vocaluxe#276]
Hi everyone,
you just merged some stuff and you're BuildBot created a new Nightly as expected.
But the Date is wrong: https://github.com/Vocaluxe/Vocaluxe/releases/tag/Nightly 
It says VocaluxeBuildBot released this on 7 Dec 2015.
Apparently he gets his Date from the Pull-Request start or something?
It looks a little strange on the releases Site ;)

**Comment by lukeIam** [comment]
> It says VocaluxeBuildBot released this on 7 Dec 2015.

looks like this is the date of the first release ever of the buildBot...
atm I'm just deleting to old files and uploading new ones. Maybe we have to recreate the complete release each time - I'll put it on the list...

**Comment by BenKmann** [comment]
What i found is, the only Page where you can see the real Date ist on the Tags Page https://github.com/Vocaluxe/Vocaluxe/tags there he knows that the nightly is only a day old.

**Comment by lukeIam** [comment]
> What i found is, the only Page where you can see the real Date ist on the Tags Page

The tag is moved everytime [here](https://github.com/Vocaluxe/Vocaluxe/blob/develop/.appveyor/moveTagForSpecialBranches.ps1#L15)

But the [appveyor.yml](https://github.com/Vocaluxe/Vocaluxe/blob/develop/appveyor.yml) file deletes only the files of the nightly release and not the release itself. This was done to easily support appveyor (Windows build) and travis (Linux build) at the same time.
