### ISSUE TITLE
Please add "restart song" to ESC menu while singing a song

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#282]
Again just a feature request:
While singing a song, it would be great if I have the possibility to select **Restart Song** if I press ESC. Currently I can only select **Continue** and **Exit Song**.

**Comment by flokuep** [comment]
Yeah, this shouldn't be a problem... I guess we should add **Restart Round** (for current song) and **Restart Game** (for current game, e.g. a medley).

Before doing this, we better update our main theme, so blocked by #256
