### ISSUE TITLE
Updating installer

### ISSUE THREAD

**Issue by flokuep** [Vocaluxe/Vocaluxe#289]
We need to update our installer to our changed situation regarding libs and dependencies. I've created a new advanced installer project from scratch. Please check it out on my new branch (https://github.com/flokuep/Vocaluxe/tree/installer).

We need to think about

- [x] Requirements we want to check before installation
- [x] Install some depedencies automatically (.NET? DirectX?)
- [x] Do we want to provide a single installer for x86 and x64 or do we want seperate ones? (currently both; ~270 MB)

What needs to be done

- [x] Check if INSTALLER target works correctly
- [x] Find a nice process to build and maybe upload installer; x64 exe needs to be in x64-Folder, x86 exe needs to be in x86 folder; we have to build installer target and get all nuget dependencies... (checkout existing batch scripts for this or advanced installer build events)
- [ ] Check how advanced installer auto update work
- [x] Check why x64 installer doesn't work (currently build installer, that just installs x86)
- [x] Do git pull in batch-script if Files folder aready exists

Builds for testing:
- https://cloud.floriankuepper.de/index.php/s/QxOfR4gUKdviYGc
- https://cloud.floriankuepper.de/index.php/s/5DauSMoSNhtVyM0

**Comment by flokuep** [comment]
We could consider to build installer with appveyor when releasing a version? 

http://www.advancedinstaller.com/forums/viewtopic.php?t=31973

**Comment by lukeIam** [comment]
There should be no problem from ci side. But it would require them to allow
us more than one activation of our license, too. I don't know if they do
that with a free OS license.
(and as long we are building x64 and x86 in parallel there can be a short
timeframe with two installations running)

**Comment by lukeIam** [comment]
> Install some depedencies automatically (.NET? DirectX?)

yes
- .NET
- DirectX 9.0c
- Visual C++ Runtime (which version[s]?)

> Do we want to provide a single installer for x86 and x64 or do we want seperate ones? (currently both; ~270 MB)

If we want to use ci to build the installers (in future) we need to use separate ones, as the builds are splitted.

**Comment by flokuep** [comment]
Okay. Integrating setup files for our dependencies might blow up install package a lot, I guess. We're currently on .NET 4, right?

**Comment by flokuep** [comment]
Using webinstaller requires an internet connection... Not sure if I like this way.

**Comment by lukeIam** [comment]
> Using webinstaller requires an internet connection...

yes, but if the error message is good I don't see a problem.
convenient solution if you have an Internet connection and a fallback that tells you what you have to do manually.

**Comment by flokuep** [comment]
I've added a little batch-script for doing all jobs to build a fresh, clean (and hopefully) working installer. This will build two different installers, one for x64 and one for x86.

Currently the installer only checks if .NET 4.0 is installed, if not it should open regarding download file in browser, so users can install it. This helps us to keep our installer package small. Could do the same for vc++ runtimes, but quite not sure which one. It might be needed by PitchTracker, and this project is set up for VS 2010, so I guess this could be the right one?

I've uploaded current installer builds for testing:
- https://cloud.floriankuepper.de/index.php/s/QxOfR4gUKdviYGc
- https://cloud.floriankuepper.de/index.php/s/5DauSMoSNhtVyM0

Please check for errors and unexpected behaviour.

**Comment by flokuep** [comment]
Got another problem: Can't build PitchTracker without updating platform toolset... I might copy built dlls from CI for building installer; We should update this after releasing next version.

**Comment by lukeIam** [comment]
I think its vc2012...

PitchTracker can be upgraded as the runtime is statically linked (at least
it should) - so no dependencies from there...

**Comment by flokuep** [comment]
Okay. I will upgrade it and add vc2010 as dependency.

**Comment by lukeIam** [comment]
> Okay. I will upgrade it and add vc2010 as dependency.

you mean vc2012?
My plan for the future is to deeper analyze the dependencies and eliminate all besides those we ship and DirectX 9.

**Comment by flokuep** [comment]
> you mean vc2012?

Yes.


> My plan for the future is to deeper analyze the dependencies and eliminate all besides those we ship and DirectX 9.

Sounds great.

**Comment by lukeIam** [comment]
> Builds for testing:
> 
> https://cloud.floriankuepper.de/index.php/s/QxOfR4gUKdviYGc
> https://cloud.floriankuepper.de/index.php/s/5DauSMoSNhtVyM0

cool! Thanks for working on this!
I tried the x64 installer:

- Got a SmartScreen Error (other installers work fine) [disabled Win10's SmartScreen to continue]
- The installers spawns two windows: 
![image](https://user-images.githubusercontent.com/5115160/29750926-92f51da2-8b48-11e7-99ec-20e2ad5b9c96.png)
- On the first start (with the desktop shortcut) I got:
`Error on start up: Could not find a part of the path:
D:\Users\dummy\Documents\Vocaluxe\Benchmark.log`
Note: My OS language is English and my profile folders are on `D`
(But cloud not find any other Vocaluxe profile directory on `C`)
- 2 x (Same Message + a stack trace for Error.log) -> crash of Vocaluxe

**Comment by flokuep** [comment]
Thanks for your feedback. I've (hopefully) resolved every issue and remaining tasks except SmartScreen error. I think we need to sign our executables for this, but I'm quite not sure how to do this. There is a digital signature option in AI, but for this we maybe need to sign every exe in our package(?). Currently not much time to dig deeper into this topics, so if someone has time to help I would be really grateful.

Feel free to do a second test:
- x86: https://cloud.floriankuepper.de/index.php/s/QxOfR4gUKdviYGc
- x64: https://cloud.floriankuepper.de/index.php/s/5DauSMoSNhtVyM0

**Comment by lukeIam** [comment]
> I've (hopefully) resolved every issue and remaining tasks except SmartScreen error.

Looks good... 😃 

This one in not really installer related more installer version of Vocaluxe related:  
We crash if we want so save a profile located in `C:\Program Files\Vocaluxe\Profiles` because we do not have access. This also happens when a new user is created and should be saved...

Log of trying to save a new profile "Asd":

```
1) Unhandled error: Access to the path 'C:\Program Files\Vocaluxe\Profiles\guest1.xml' is denied.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)
   at VocaluxeLib.Xml.CXmlSerializer.Serialize(String filePath, Object o, String rootNodeName)
   at VocaluxeLib.Profile.CProfile.SaveProfile()
   at Vocaluxe.Base.CProfiles.SaveProfiles()
   at Vocaluxe.Screens.CScreenProfiles.HandleMouse(SMouseEvent mouseEvent)
   at Vocaluxe.Base.CGraphics._HandleInputs(CKeys keys, CMouse mouse)
   at Vocaluxe.Base.CGraphics.UpdateGameLogic(CKeys keys, CMouse mouse)
   at Vocaluxe.Lib.Draw.CDrawBase`1.MainLoop()
   at Vocaluxe.Lib.Draw.CDrawBaseWindows`1.MainLoop()
   at Vocaluxe.CMainProgram._Run(String[] args)
   at Vocaluxe.CMainProgram.Main(String[] args)
```

**Comment by lukeIam** [comment]
> I think we need to sign our executables for this, but I'm quite not sure how to do this. There is a digital signature option in AI, but for this we maybe need to sign every exe in our package(?).

I did some research: 
SmartScreen is based on "reputation". If the executables are signed (normal or EV) the reputation is shared between them. If you have a new executable signed with an EV certificate you get a better starting reputation. 
In this case we only need to sign the installer (but if we would have signing certificate we cloud also easily sign the other files too)
But code signing certs are expensive... (There are some offers for open source but there are just a bit cheaper - the free offer are gone as far as I could find out)

Then I played around with the downloaded files:

1.  A SmartScreen check is only done if the file is marked with the "from Internet flag".
If the file is unblocked before starting everything is fine:
![image](https://user-images.githubusercontent.com/5115160/29884464-e0276586-8db3-11e7-82d3-cefaf7a86978.png)
1b. I thought about putting the exe file into a zip-archive. With 7zip ists working, but if you use the windows explorer it's transferring the flag to the extracted files.
2. An other option that the user can bypass the SmartScreen warning in two steps:
![image](https://user-images.githubusercontent.com/5115160/29884619-53ac06ce-8db4-11e7-988d-e76619c19517.png)
![image](https://user-images.githubusercontent.com/5115160/29884655-678781d2-8db4-11e7-94ef-a657c86e4e99.png)

Summary: I suggest to show a popup after a click on the installer download button explaining how to unblock the installer file (option 1 or 2). Maybe we even need a little browser switch as IE is applying the smart screen check right after downloading and shows an other waring.

**Comment by lukeIam** [comment]
It's worse than I thought:
If you use windows explorer to extract the portable editions it flags **every** file in the extracted folder.
==> If you try to start Vocaluxe it's shows the same warning.
You have to unblock "Voclauxe.exe" and "VocaluxeServerConfig.exe" or simply the zip file before extracting.

**Comment by flokuep** [comment]
Yeah that is really worse; Already noticed this some time ago and didn't find a nice solution for that.

Anyway: I've fixed the profile bug.
