### ISSUE TITLE
Improve error logging 

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#291]
For some errors we do not have much information e.g. video decoding errors.
Maybe based on: https://github.com/lukeIam/Vocaluxe/tree/logDecoderExceptions

**Comment by flokuep** [comment]
Yeah. Would be nice. Maybe we should add this before releasing our next version to get proper bug reports?

**Comment by flokuep** [comment]
I've spent some work on this and added writing exception into error log where I found some unhandled exceptions...

What do you think about
- [ ] CWebservice._GetSession()
- [ ] CKeys._Add()

Should we log there, too? Currently not sure if some exceptions are expected here.

**Comment by lukeIam** [comment]
CWebservice._GetSession() -> occurs if somebody sends a malformed session
key (should not happen if the official web app is used) -> we can ignore
this (but logging it does also not hurt)


CKeys._Add() -> I guess you mean the try catch around `_KeysPool.Add(pool);`
-> _KeysPool is a List and I as far as I know there no Exceptions with
List<T>.Add() (only if _KeysPool is null - and this could not happen here)

Should we also log a stack trace to the log file (easier to reproduce)?
Maybe we can write an extension method for Exception which converts an
Exception instance to an custom string (e.g. `e.WriteToLog()`) for logging
(or even but the log part to that method e.g. `e.WriteToErrorLog()`).

**Comment by lukeIam** [comment]
The new logging framework is live.
