### ISSUE TITLE
XP compatibility

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#292]
Maybe we lost XP compatibility by using a new ffmpeg version:
https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=2&t=2937

**Comment by flokuep** [comment]
Unfortunately I don't have a xp system nor an installation disc to setup a vm for testing. So I suggest to _hope_ everything is fine and we could release a (last) xp version....

**Comment by Jiiniasu** [comment]
In my opinion no energy should be put on XP compatibility as the consumer variants of the OS have been completely unsupported for several years now... I'd refer to older versions if one would want to run it on XP.

**Comment by derivator** [comment]
If even one person upgrades from XP because of Vocaluxe I'd consider it a success.

**Comment by flokuep** [comment]
Okay. So I guess we could close this, @lukeIam ?

**Comment by lukeIam** [comment]
yes!
