### ISSUE TITLE
Automatically pull transifex translations

### ISSUE THREAD

**Issue by flokuep** [Vocaluxe/Vocaluxe#297]
Currently we need to pull translations manually (and correct some issues here and there than, mostly regarding emphasis in french translation).

Automatically pull translations should be easier and less error-prone: https://www.transifex.com/blog/2013/github-transifex-integration/

**Comment by lukeIam** [comment]
This requires

> A free Amazon EC2 instance.

But, Amazon EC2 is only free for the first year...

I'm surprised that the do not have a direct github integration as [others](https://github.com/marketplace/category/localization)...

**Comment by hendrikbl** [comment]
We could use Crowdin for that. It's also free for Open Source Projects and as mentioned offers a nice [GitHub integration](https://github.com/marketplace/category/localization).

**Comment by flokuep** [comment]
Not sure if we will loose some of our translators when we switch to another tool... What do you think @lukeIam ?

**Comment by lukeIam** [comment]
> Not sure if we will loose some of our translators when we switch to another tool... What do you think @lukeIam ?

I agree! I don't thing every translater will create a new account and would change with us...

@flokuep How high is the pressure to move to something more automated?

**Comment by flokuep** [comment]
We need to run some service on a server (or amazon ec2). Another way would be to integrate this into CI; I've already use a little python tool to fetch latest translations. We could do this on every CI build I gues... Here is a small how-to for travis, but appveyor should be the same; .tx/config already exists. https://docs.transifex.com/integrations/github

**Comment by lukeIam** [comment]
Theoretically we cloud pull new translation after every nightly build and commit the changes to the repo if there any.

**Comment by marwin89** [comment]
@flokuep : is this still a problem? Or did you solve it with the latest transifex configuration in the last months? If solved, then I would close this issue.
