### ISSUE TITLE
Lubuntu Install fails

### ISSUE THREAD

**Issue by diver66** [Vocaluxe/Vocaluxe#304]
Hi,
sadly the lubuntu install fails everytime, can somebody pls tell me, what I can do about it ?

diver66@ultrastar:~/Vocaluxe$ make
make -C PitchTracker
make[1]: Entering directory '/home/diver66/Vocaluxe/PitchTracker'
g++  -std=gnu++11 -fPIC  -c -o compatibility.o compatibility.cpp
g++  -std=gnu++11 -fPIC  -c -o dywapitchtrack/dywapitchtrack.o dywapitchtrack/dywapitchtrack.cpp
g++  -std=gnu++11 -fPIC  -c -o dywapitchtrack/ptDyWa.o dywapitchtrack/ptDyWa.cpp
g++  -std=gnu++11 -fPIC  -c -o FFT/FFT.o FFT/FFT.cpp
g++  -std=gnu++11 -fPIC  -c -o FFT/RealFFTf.o FFT/RealFFTf.cpp
g++  -std=gnu++11 -fPIC  -c -o Helper.o Helper.cpp
g++  -std=gnu++11 -fPIC  -c -o performous/pitch.o performous/pitch.cc
g++  -std=gnu++11 -fPIC  -c -o ptAKF.o ptAKF.cpp
g++  -std=gnu++11 -fPIC  -c -o PitchWrapper.o PitchWrapper.cpp
gcc -shared -o libPitchTracker.dll.so -fPIC compatibility.o dywapitchtrack/dywapitchtrack.o dywapitchtrack/ptDyWa.o FFT/FFT.o FFT/RealFFTf.o Helper.o performous/pitch.o ptAKF.o PitchWrapper.o
strip libPitchTracker.dll.so
cp libPitchTracker.dll.so ../Output/
make[1]: Leaving directory '/home/diver66/Vocaluxe/PitchTracker'
make -C Vocaluxe/Lib/Video/Acinerella
make[1]: Entering directory '/home/diver66/Vocaluxe/Vocaluxe/Lib/Video/Acinerella'
gcc -c -fPIC acinerella.c -I /usr/local/include
acinerella.c: In function ‘cpymetadata’:
acinerella.c:344:9: warning: implicit declaration of function ‘strncpy_s’ [-Wimplicit-function-declaration]
         strncpy_s(tar, len, entry->value, len);
         ^~~~~~~~~
gcc -shared -o libacinerella.so acinerella.o -lavformat -lavcodec -lavutil -lm -lswscale -lswresample
strip libacinerella.so
cp libacinerella.so ../../../../Output/
make[1]: Leaving directory '/home/diver66/Vocaluxe/Vocaluxe/Lib/Video/Acinerella'
rm -f Output/gstreamer-sharp.dll Output/glib-sharp.dll
xbuild /property:Platform=x64 /property:Configuration=ReleaseLinux
XBuild Engine Version 14.0
Mono, Version 4.6.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 9/2/2017 11:08:22 AM.
__________________________________________________
/home/diver66/Vocaluxe/Vocaluxe.sln:  warning : Ignoring vcproj 'PitchTracker'.
/home/diver66/Vocaluxe/Vocaluxe.sln:  warning : Failed to find project 54a48af7-515c-4edd-b395-2bffa096050a
Project "/home/diver66/Vocaluxe/Vocaluxe.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "ReleaseLinux|x64".
	Target Build:
		Project "/home/diver66/Vocaluxe/VocaluxeLib/VocaluxeLib.csproj" (default target(s)):
			Target PrepareForBuild:
				Configuration: ReleaseLinux Platform: AnyCPU
				Created directory "../Output/libs/managed/"
				Created directory "obj/ReleaseLinux/"
			Target ResolveAssemblyReferences:
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Drawing' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				HintPath attribute not found
				For searchpath {TargetFrameworkDirectory}
				For searchpath {PkgConfig}
				Considered System.Drawing, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered System.Drawing, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'System.Drawing' as a file, but the file does not exist
				For searchpath ../Output/libs/managed/
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.Drawing' as a file, but the file does not exist
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.Drawing.exe' as a file, but the file does not exist
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.Drawing.dll' as a file, but the file does not exist
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Windows.Forms' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				HintPath attribute not found
				For searchpath {TargetFrameworkDirectory}
				For searchpath {PkgConfig}
				Considered System.Windows.Forms, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered System.Windows.Forms, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'System.Windows.Forms' as a file, but the file does not exist
				For searchpath ../Output/libs/managed/
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.Windows.Forms' as a file, but the file does not exist
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.Windows.Forms.exe' as a file, but the file does not exist
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.Windows.Forms.dll' as a file, but the file does not exist
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.XML' not resolved
				For searchpath {CandidateAssemblyFiles}
				Warning: {CandidateAssemblyFiles} not supported currently
				For searchpath {HintPathFromItem}
				HintPath attribute not found
				For searchpath {TargetFrameworkDirectory}
				For searchpath {PkgConfig}
				Considered System.XML, but could not find in any pkg-config files.
				For searchpath {GAC}
				Considered System.XML, but could not find in the GAC.
				For searchpath {RawFileName}
				Considered 'System.XML' as a file, but the file does not exist
				For searchpath ../Output/libs/managed/
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.XML' as a file, but the file does not exist
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.XML.exe' as a file, but the file does not exist
				Considered '/home/diver66/Vocaluxe/Output/libs/managed/System.XML.dll' as a file, but the file does not exist
			Target GenerateSatelliteAssemblies:
			No input files were specified for target GenerateSatelliteAssemblies, skipping.
		Done building project "/home/diver66/Vocaluxe/VocaluxeLib/VocaluxeLib.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/diver66/Vocaluxe/Vocaluxe.sln".-- FAILED
Done building project "/home/diver66/Vocaluxe/Vocaluxe.sln".-- FAILED

Build FAILED.

Warnings:

/home/diver66/Vocaluxe/Vocaluxe.sln:  warning : Ignoring vcproj 'PitchTracker'.
/home/diver66/Vocaluxe/Vocaluxe.sln:  warning : Failed to find project 54a48af7-515c-4edd-b395-2bffa096050a

/home/diver66/Vocaluxe/Vocaluxe.sln (default targets) ->
(Build target) ->
/home/diver66/Vocaluxe/VocaluxeLib/VocaluxeLib.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Drawing' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.Windows.Forms' not resolved
	/usr/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets:  warning : Reference 'System.XML' not resolved

	 5 Warning(s)
	 0 Error(s)

Time Elapsed 00:00:01.2986320
makefile:4: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by flokuep** [comment]
Looks like there are some libs missing. We've manage our dependencies with nuget, could you try `nuget restore` - Currently not sure if this fully works with mono, but should.

You could also try to find out why System.XML.dll was not found... This should be a standard dll that comes with your mono installation I guess.

Building vocaluxe on linux is hard work, in my experience you get from one solved issue to another one... You could read about it in some issues, where people try to get it work. Actually it _should_ but don't know someone who made it recently. (#271, #31)

**Comment by diver66** [comment]
I guess you are right it still does not work, it does not finish the make. Maybe somebody will figure this out soon   .... :-)

**Comment by derivator** [comment]
@diver66 I'm pretty sure that this is an error that I've fixed before. Your best bet is probably with [this](https://github.com/derivator/Vocaluxe/tree/travis) (quite old) branch, which should have all the fixes required to get it to build, but as @flokuep said, it's pretty difficult to get it running at the moment.

**Comment by lukeIam** [comment]
@diver66 
This (a bit older version) was building fine locally with ubuntu and on a travis build host:
https://github.com/lukeIam/Vocaluxe/tree/travis_ffmpegPrebuild_test

See the `.travis.yml` for the build commands:
https://github.com/lukeIam/Vocaluxe/blob/travis_ffmpegPrebuild_test/.travis.yml

But I finally failed to build some required runtime dependencies for ubuntu and gave up.

Hope this helps a bit.

**Comment by diver66** [comment]
thanks guys I try that out

**Comment by bidinou** [comment]
Hi ! I encounter the same issues when trying to build on KDE Neon (Ubuntu 16.04 based). It would be awesome if, in the future, you considered distributing Vocaluxe as a flatpack or snap package...

**Comment by lukeIam** [comment]
> It would be awesome if, in the future, you considered distributing Vocaluxe as a flatpack or snap package...

Hi @bidinou ,

yes something like flatpack, snap, appimage, ... you be the best way to go.
But first of all we have to get all dependencies building for the target system.
At to moment I not having the time to work on the linux dependency problem.
(I tired two times so far and both times I failed on build a sub-sub-dependency)

**Comment by lukeIam** [comment]
@diver66 @bidinou 
I've updated my travis branch (https://github.com/lukeIam/Vocaluxe/tree/travis) to compile successfully with Ubuntu 14.04 (still having runtime dependency problems).
I also updated the LinuxHowTo: https://github.com/Vocaluxe/Vocaluxe/pull/376/files (currently open pr)

Hope this helps you to compile it your self.
