### ISSUE TITLE
version name isn't set correctly

### ISSUE THREAD

**Issue by flokuep** [Vocaluxe/Vocaluxe#306]
Our release candidate builds have '0.4.0.beta1' as version... Should be  '0.4.0.rc1' or at least '0.4.0.beta2'...

Also: It isn't released as 'preview version'...

**Comment by lukeIam** [comment]
This is the problem I feared... some where `rc` is not recognized as a term.

Also it's marked as "latest release" and the x64 build was deleted...

**Comment by flokuep** [comment]
Mhm. Delete tag and try it with beta2 again?

**Comment by lukeIam** [comment]
> Mhm. Delete tag and try it with beta2 again?

should fix the most of it.

but not the overriding of the x64 release - I'm investigating it

**Comment by flokuep** [comment]
Should be my mistake. I've changed it manually to pre release.

**Comment by lukeIam** [comment]
no - the description must contain the $(APPVEYOR_REPO_COMMIT) 
It's used as flag to workaround an other problem

**Comment by lukeIam** [comment]
With that beta2 should work (the release is created automatically and if both files were added we can change the description)
-> so we just have to create an other tag with beta2

**Comment by flokuep** [comment]
Okay, will check it out.

**Comment by lukeIam** [comment]
Okay - looks better (two files in the release now)
And I already updated the description.

**Comment by lukeIam** [comment]
I've downloaded the x64 build: is starting and version looks good:
`Vocaluxe 'Blue Sunrise' 0.4.0.beta2 (x64) (0.4.0.beta2-0-g01fa98a)`

**Comment by flokuep** [comment]
Yes. I've just build our installer, also looks fine... I'll upload them now.

**Comment by lukeIam** [comment]
> Yes. I've just build our installer, also looks fine... I'll upload them now.

👍 

Maybe we should rename `Vocaluxe-0.4.0.12-x64.exe` to `Vocaluxe_0.4.0.beta2_windows_x64.exe`.
Otherwise the page will not detect the right flags. 
(To update the page just do an empty commit to the gh-pages branch)

**Comment by flokuep** [comment]
Jep, worked 👍

**Comment by lukeIam** [comment]
Looks good!

:+1:

**Comment by lukeIam** [comment]
We may should thing about an way to redirect the missing source forge users:
![image](https://user-images.githubusercontent.com/5115160/30001233-f0749cac-9087-11e7-88e6-4cdc938f528a.png)

**Comment by flokuep** [comment]
I could upload released versions there... But actual, thats not the best solution I guess.

**Comment by lukeIam** [comment]
@flokuep clould this be closed?

**Comment by flokuep** [comment]
Yes.
