### ISSUE TITLE
Problem with non-latin characters

### ISSUE THREAD

**Issue by flokuep** [Vocaluxe/Vocaluxe#310]
When loading songs with non-latin characters, Vocaluxe can't display them properly. Charachters lay on top of each other.

I've already digged into this and found the problem: In CGlyph, L 54, MeasureString doesn't work properly and returns width=0, the same method works properly (without parameters) in line 50.

On StackOverflow I've found this:   https://stackoverflow.com/questions/11708621/how-to-measure-width-of-a-string-precisely This works (can't say why), but it breaks cover generation...

Any ideas what could be wrong and how to fix it (properly)?

**Comment by lukeIam** [comment]
phuu - good question...

maybe this helps trying out the options:
https://www.codeproject.com/Tips/1012908/GDI-DrawString-Configurator-App
