### ISSUE TITLE
Update .NET version

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#315]
https://cdn.rawgit.com/lukeIam/b056457bf5ef460d18cbea216153e6e2/raw/6ed412dd13fd4ac84c35a4f3b86895d87eed2249/ApiPortAnalysis.html

**Comment by lukeIam** [comment]
Any reason not to go for 4.7.x?

**Comment by flokuep** [comment]
I don't see any.

**Comment by lukeIam** [comment]
Visual Studio 2015 needs a developer pack to support  .NET 4.7.1 .
Download it from here:
https://www.microsoft.com/net/download/thank-you/net471-developer-pack
