### ISSUE TITLE
New nightly crash in Options / Record

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#317]
Using Vocaluxe 0.4.0.beta2-83-gae5a463 x64 nightly from 18. September 2017. This version crash as soon as I try to start singing a song or go into the Options / Record settings.

The nightly from July 2017 is still working without problems. Using Windows 10 x64 1703.

Even if I set DebugLevel to TR_CONFIG_LEVEL_MAX in the Config.xml file, I don't see useful stuff in the debug.log file.

**Comment by Stefan1200-de** [comment]
![image](https://user-images.githubusercontent.com/15168351/30772591-ab5bcc80-a05e-11e7-9995-3c5594ee6214.png)

**Comment by lukeIam** [comment]
Hi @Stefan1200-de,

thanks for reporting!

Anything in the `error.log`?

 `Singing a song` and `Options / Record` -> looks like something with the microphones...

**Comment by Stefan1200-de** [comment]
Song related errors, yes. I use the same song directory, as with the Vocaluxe Nightly from July and Performous 1.1 (which can use it without problems).

[Error.log](https://github.com/Vocaluxe/Vocaluxe/files/1327003/Error.log)

**Comment by lukeIam** [comment]
> Error.log

Also nothing use full here...
Thats strange - looks like our mechanism to log uncatched errors failed.

ok, then some other questions:
- Do you have microphones attached (which, how many)
- The `sound` and `record` sections of your `config.xml` could be usefull
- If you have some time and you like to get us more informations about the crash you can create a dump file:
  - Download https://www.microsoft.com/en-us/download/details.aspx?id=49924
  - Start DibugDiag2 Collection
  - Add Rule -> Crash -> A specific process -> Vocaluxe.exe (start Vocaluxe before)
  - Keep defaults for the other steps (but note the target path somewhere)
  - go to the Sing screen and let Vocaluxe crash
  - start Vocaluxe again (the dump rule will be still active) and crash Vocaluxe with the RecordOptions screen
  - Get us the content of the dump folder
  - Delete the Rule in the diagnostics tool

**Comment by Stefan1200-de** [comment]
I copied over the Record block of the Config.xml file from the older nightly, now it is not crashing anymore.

Just to test if there is a problem on the first start of the Vocaluxe nightly, I deleted the Config.xml file and started it again, but now I don't have problems anymore. I don't know what was wrong the first time.

I only remembered that there was a DeviceName, which I don't have. But I'm unable to reproduce it, even if I write crap into the config file. Unfortunately I forgot to make a copy of the corrupted config file.

**Comment by lukeIam** [comment]
> I only remembered that there was a DeviceName, which I don't have. But I'm unable to reproduce it, even if I write crap into the config file.

Same for me - tried some non existing devices or blank names - couldn't trigger a crash...
-> Closing this for now 
If someone has the same problem again - feel free to post here and I will reopen this issue.
