### ISSUE TITLE
Ambient for new nightly?

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#319]
Is it possible to use the Ambient theme from the older nightly versions? For me the Genius theme is to dark.

Just copy over the Ambient theme don't work.

**Comment by flokuep** [comment]
No, I'm sorry. We don't have enough time to support two themes. You could upgrade ambient yourself, just step through vor latest commits and follow notes in theme-changelog.

**Comment by Stefan1200-de** [comment]
Yeah, I tried it already, but as soon as I go to the sing screen, Vocaluxe crashed. I will stay at beta 2 for now, which already has many nice improvements compared to the July 2017 nightly. :)
