### ISSUE TITLE
2nd player lyrics missing at duet songs if lyrics position is set to "Top"

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#322]
2nd player lyrics missing at duet songs if lyrics position is set to "Top" in the game settings. Tested with the Windows x64 version of Vocaluxe 0.4.0 released on 28. September 2017. Tested multiple duet songs, all have the same problem. As soon as I set the lyrics position to "Bottom" everything is fine.

**Comment by flokuep** [comment]
Thanks for reporting this bug. Will be fixed in (coming) version 0.4.1.
