### ISSUE TITLE
Windows 10 x64 Notebook - Vocaluxe 0.4.0 is not starting

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#324]
After executing the Vocaluxe.exe I only get the Vocaluxe splash screen and the Vocaluxe process is taking around 32% for an endless time (waited around 10 minutes until I took the Task Manager). I used the Vocaluxe Installer and this error also occurs with an empty songs directory. No error.log or debug.log was created.

On my Windows 10 x64 desktop PC everything is working fine with the same USB microphone. Tested this with only one capture device connected to my notebook (the USB microphone). Forcing Vocaluxe to use the NVidia 940M or Intel HD GPU was not helping. It is more or less the same software installed as on my desktop PC.

OS: Windows 10 x64
CPU: Intel i5 5200U
RAM: 8 GByte RAM
GPU: NVidia 940M & Intel HD (multi GPU device!)

What can I do to help you finding this issue? By the way: Performous 1.1 has the same issue, while UltraStar Deluxe 2017.8.0 is working fine.

**Comment by lukeIam** [comment]
> No error.log or debug.log was created.

The installer version creates these files your personal folder aka `%userprofile%`.  

You can also check the `Benchmark.log` file.
Furthermore increasing the `DebugLevel` in the `Config.xml` may help getting better information.

**Comment by Stefan1200-de** [comment]
Found the Benchmark.log and Config.xml file in my personal documents directory (in a Vocaluxe directory), thanks for that hint. On my desktop pc I used the ZIP file, that's why I only knew the "current dir" location. ;)
[Benchmark.log](https://github.com/Vocaluxe/Vocaluxe/files/1357214/Benchmark.log)

But the error.log and debug.log files still don't get created, even if I set TR_CONFIG_LEVEL_MAX at DebugLevel. But maybe the Benchmark.log file already helps you.

**Comment by flokuep** [comment]
Okay. Seems to be a problem with initialising record-stuff. Could you change <Sound>...<RecordLib> in config.xml to DirectSound and check it again? You could also try to remove config.xml (this would be a 'hard reset', maybe there are some strange saved configs in <Record>-part).

**Comment by Stefan1200-de** [comment]
Results of my tests:
Deleting the config.xml does not help, same issue.

Set the **RecordLib** to **DirectSound** was helping, I can start Vocaluxe now, but with two side effects:
**- I can't start Vocaluxe without a recording device.** Sometimes this would be nice, if I want to test something. But that is not a big deal for me, because I do this on my desktop PC. I get this message:
![vocaluxe_directsound_norecorddevice](https://user-images.githubusercontent.com/15168351/31318297-3457558e-ac50-11e7-9731-331983fd0888.png)

**- I can't see the device names in the Options / Record settings.**
![vocaluxe_options_record](https://user-images.githubusercontent.com/15168351/31318327-b0098260-ac50-11e7-8baa-04842f5e90eb.png)

**Comment by Stefan1200-de** [comment]
Audacity 2.1.3 is working, including Audio recording.

**Comment by Stefan1200-de** [comment]
Any new ideas how to fix this issue?

**Comment by flokuep** [comment]
Currently not... Not that much time for vocaluxe at this moment... 😞

**Comment by flokuep** [comment]
I've just stepped into code and this seems to be very weird. I don't really see something that goes to some (kind of) endless loop.

I've currently added a commit, that simply tries to log every step in initializing record stuff into error.log. Could you start this and upload error.log after that?

https://ci.appveyor.com/api/buildjobs/jwsx180mq3mhnd05/artifacts/Vocaluxe_testing-pa_Windows_x64.zip
https://ci.appveyor.com/api/buildjobs/qlrh0plf5qxb1kfg/artifacts/Vocaluxe_testing-pa_Windows_x86.zip

Attention: If there is really a endless loop, error.log could get very big. So better just wait only for a minute or so ;)

**Comment by Stefan1200-de** [comment]
Well, even your test version does not create the error.log file. To make sure, that I look at the right location, I set the RecordLib to DirectSound and I found the error.log in the program directory. Switched back to PortAudio, again no error.log.

**Comment by flokuep** [comment]
Well. That is really strange now. It should be there if you set it to portaudio...

Could you search on your filesystem for it? With my test Version it should be next to vocaluxe.exe

**Comment by Stefan1200-de** [comment]
I searched for it, there is no error.log. As soon as I set the RecordLib to DirectSound, I get the error.log in the same directory. If I go back to PortAudio, the error.log will not be updated. I also checked the Windows perfmon.exe, Vocaluxe does not have any file system activities, while it is in the endless loop.

**Comment by lukeIam** [comment]
Invested an other 1,5 hours - could not reproduce it and the code paths look good... 😕 

A last idea: you can record a profile of the Vocaluxe.exe execution - even without having Visual Studio installed:

1. Download this build of Vocaluxe:
2. Download: https://aka.ms/vs/15/release/StandaloneProfiler.amd64ret.deu.exe
3. Install the StandaloneProfiler (specify a path - with defaults I couldnÄt find the folder 😉 )
4. Start a cmd and navigate to the Vocaluxe folder
5. Run this command 
```cmd
[YourFolder]\VSPerf.exe /launch:".\Vocaluxe.exe" /file:"PR324Dump"
```
7. Vocaluxe should start
8. As your Vocaluxe start is endless, wait a moment and then kill the Vocaluxe.exe with the taskmanager
9. The profiler should say something like "saving data" (for me this message stays until I pressed enter after a while)
6. Send us the `PR324Dump.vspx` file next to the Vocaluxe.exe

**Comment by Stefan1200-de** [comment]
Thanks for still searching for the problem.

In the last two weeks I had not much time to do this, but today I did this test. Zipped PR324Dump.vspx file:
[PR324Dump.zip](https://github.com/Vocaluxe/Vocaluxe/files/1611076/PR324Dump.zip)

By the way, the default path of VSPref.exe is: C:\Program Files (x86)\Microsoft Visual Studio 15.0\Team Tools\Performance Tools

**Comment by lukeIam** [comment]
Hi @Stefan1200-de,

thanks for providing us the trace file!
I analyzed it: 
- We call `Pa_Initialize()` on the native `PortAudio.dll`
- That call never returns 
=> looks like a bug in PortAudio :/

Maybe we can upgrade the PortAudio version to fix this - but we have to check if the API would change...

**Comment by lukeIam** [comment]
Hi @Stefan1200-de,

just created a version with a new portaudio version:
https://ci.appveyor.com/project/lukeiam/vocaluxe/branch/NewPortAudio

Please test with this version.

**Comment by Stefan1200-de** [comment]
I tested on my notebook and on my desktop pc (just to make sure, that the new PortAudio don't break anything on my desktop pc), on both systems the new version is running fine! Thanks for finding this issue.

**Comment by lukeIam** [comment]
@Stefan1200-de 

I'm happy to hear that! Thanks for testing!
