### ISSUE TITLE
Windows 64bit Videoplayback issue. video error

### ISSUE THREAD

**Issue by strikegun** [Vocaluxe/Vocaluxe#327]
I am using stable 0.4.0.
The playback of all video file types are not working correctly.
A screenshot can be viewed here: [http://forum.ultra-star.de/download/file.php?id=899](http://forum.ultra-star.de/download/file.php?id=899)

thanks

**Comment by flokuep** [comment]
Thanks for reporting this. I've just answered you in ultra-star forum.

**Comment by lukeIam** [comment]
Hi @strikegun 

can you please provide some more information?

- type of installation: portable/installer 
- "fresh" install or "over" an existing Vocaluxe installation
-  x64 or x86
- windows version (xp is not longer supported by Vocaluxe and ffmpeg)

Thanks!

**Comment by lukeIam** [comment]
Closing this because of no response (comment here if we should reopen this issue)
