### ISSUE TITLE
Crash in Challenge Mode

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#348]
When playing with 4 people (2 microphones) Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-160-gee60af4) (281 songs) in Challenge Mode, we always ended up after some minutes in a crash: see attachment

![challengecrash](https://user-images.githubusercontent.com/20970069/34229300-03437212-e5d4-11e7-906a-ca85a6552aa3.jpg)

Any idea about how to avoid it?

**Comment by flokuep** [comment]
Thanks for reporting this issue. We hopefully already fixed this for upcoming bugfix release. You can test it with this build: https://ci.appveyor.com/api/buildjobs/w0vg4k6q23xuqi4u/artifacts/Vocaluxe_master_Windows_x64.zip

**Comment by Michri** [comment]
Is this fix already part of the latest nightly build?  
Right now I noticed a new version (23.12.2017 - fcc1ca6 - https://github.com/Vocaluxe/Vocaluxe/releases)

**Comment by flokuep** [comment]
No, currently not in nightly because we're preparing a bugfix version and are working on multiple branches (see #328).
Current build for this: https://ci.appveyor.com/api/buildjobs/9yixssb1t7yrgja3/artifacts/Vocaluxe_master_Windows_x64.zip

We merge these fixes into develop (and so into nightly builds) from time to time.

**Comment by Michri** [comment]
ok, so when using the link (https://ci.appveyor.com/api/buildjobs/9yixssb1t7yrgja3/artifacts/Vocaluxe_master_Windows_x64.zip), I ill get the fix for this crash already?
Thanks.

**Comment by flokuep** [comment]
Link is current _nightly_ of bugfix version 0.4.1. Fix will be of course part of all upcoming versions... We just need to merge this into our dev branch.

**Comment by Michri** [comment]
Ok, so I will check this linked version.
So as I understand, this version fixed already this crash issue?

**Comment by Michri** [comment]
No I am confused.
The version of the link looks different:
In the nightly build (2. December 2017) I found 2 party modes only: Challenge Mode + Tic-Tac-Toe
In the version of the link, the Medley mode was separated from Challenge mode (as already long time ago).
Is that correct?

**Comment by flokuep** [comment]
Sorry for confusing ;)

- release-0.4.1: Base is release-0.4 build, we are only doing bugfixes there to get a bugfix release
- develop: Base is release-0.4 build, we are adding new features/bigger changes here to develop a 0.5 (or something similar) release.

In develop, we added a more general song-selection for party-modes. It's possible to sing medleys in challenge mode now, so challenge medley mode get obsolete (less work for us when adding some things to party modes), so: yeah, it's correct.

I could reproduce your encountered bug, but we messed up everything here. I've openend a new issue for this (#357).

**Comment by Michri** [comment]
I am still lost.
So my reported bug is already fixed in the version you were linking to (https://ci.appveyor.com/api/buildjobs/9yixssb1t7yrgja3/artifacts/Vocaluxe_master_Windows_x64.zip)? Although this linked version isn’t covering the new party mode handling?

**Comment by flokuep** [comment]
No worries, I thought your bug was fixed there, but it may not. I'm currently working on fixing it.

**Comment by flokuep** [comment]
@Michri fix is merged in develop-branch. Our CI is currently building new nightly builds, it will be available in the next minutes :)

**Comment by Michri** [comment]
Ok, Sounds cool, so last nightly from https://github.com/Vocaluxe/Vocaluxe/releases will call contain the fix?

**Comment by flokuep** [comment]
Yes.
