### ISSUE TITLE
Tic-Tac-Toe mode doesn't store fields

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#349]
When playing with 4 people (2 microphones) Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-160-gee60af4) (281 songs) in Tic-Tac-Toe mode, played fields were not marked as used with info about what team hs won the session.

Did we made something wrong?

**Comment by Michri** [comment]
IS there some info available about that issue?

**Comment by flokuep** [comment]
Don't find time to check this currently.

**Comment by flokuep** [comment]
Did you finished a song? If you abort it, vocaluxe won't mark a song as won (because it was aborted).

**Comment by Michri** [comment]
Yes, we finished the song. Got "Auswertung"- and "Gesamtpunktzahl"-view and the Highscore list. Then the Tic-Tac-Toe matrix appears and the selected are isn't marked.
No guests were playing.

How might I upload videos (.mov)? Then I can show.

**Comment by flokuep** [comment]
Video would be nice. You could use something like workupload.com for uploading big files. If you have problems with this, it's okay for me when you provide more information about this problem: How configured you tic-tac-toe mode?

**Comment by Michri** [comment]
9 fields
it happens with and without refilling jokers
all songs
normal and medley mode (3 songs) tested
2 teams with 1 or 2 players each

**Comment by flokuep** [comment]
Ah. You're using nightly build, right? I've missed this somehow. Will check it there.

**Comment by Michri** [comment]
Yes, right. I used version 'Blue Sunrise' 0.4.0 (x64) (0.4.0-160-gee60af4).
It was a nightly build from about 20 days ago.
