### ISSUE TITLE
Missing singer in Highscore overview

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#351]
When playing with 4 people (2 microphones) Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-160-gee60af4) (281 songs) in different modes, we had sometimes the issue that Highscore overview shows only one singer instead of both.

**Comment by flokuep** [comment]
Please check if these profiles aren't guest profiles. If these are, this is the correct behaviour

**Comment by Michri** [comment]
Right, we had guest profiles in there as well.
What'S the reason, for keeping them out?

**Comment by flokuep** [comment]
No bug, duplicate of #350
