### ISSUE TITLE
Change guest profiles

### ISSUE THREAD

**Issue by flokuep** [Vocaluxe/Vocaluxe#354]
Currently we have three guest profiles with very boring names: 'Guest 1', 'Guest 2' and 'Guest 3'.

I suggest to change them to some (un)real names and add maybe some nice avatars (a set of selectable avatars would also be nice, imho). It would be a good idea to have guest profiles for every difficulty, we may can find some nice names (male and female?) that reflects them (something like Betty Beginner).

Would be nice to have some help for designing avatars and getting some names.

**Comment by hendrikbl** [comment]
I can see if I can make some avatars similar to the one I'm using if that's something we want to use 👍

**Comment by flokuep** [comment]
Hmm. Not sure if we should use some more colorful ones (like your avatar or avatars of usdx project (see https://github.com/UltraStar-Deluxe/USDX/tree/master/game/avatars)

**Comment by hendrikbl** [comment]
> Hmm. Not sure if we should use some more colorful ones

I personally don't like the ones from usdx. I prefer the flat ones like my avatar.

While playing around with avatars I came up with an idea for a profiles screen. Not sure if thats something we want to do, but it shows my avatar and one I grabbed from [here](https://freeiconshop.com/icon/person-icon-flat/) the way I'd make the guest avatars.

![vocaluxe_profiles](https://user-images.githubusercontent.com/9558391/34691226-400c3fb6-f4bc-11e7-9ddf-c9554b1927bc.png)

**Comment by flokuep** [comment]
I like these avatars 👍

**Comment by marwin89** [comment]
- I added new guest profile avatars and changed the avatar settings in this PullReq https://github.com/Vocaluxe/Vocaluxe/pull/671 🎨 ✅ 
![AvatarsGuestProfiles](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/f37944c1-88b6-479d-a3e4-7f0676a5e736)
