### ISSUE TITLE
Crash when exiting Vocaluxe

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#355]
When using 'Blue Sunrise' 0.4.0 (x64) (0.4.0-160-gee60af4) - nighly build of 20.12., I had sometimes a crash when exiting Vocaluxe:
![shutdown crash](https://user-images.githubusercontent.com/20970069/34320600-221df8ac-e7fe-11e7-95b2-8383799633b3.jpg)
Is that something critical?

**Comment by Stefan1200-de** [comment]
Same issue as #320

**Comment by lukeIam** [comment]
@Michri Can you please check the current nightly - this should be fixed (and if not we have better logs now 😉 )

It's nothing critical: we try to delete a object the is already deleted.
