### ISSUE TITLE
Problem with Duet mode

### ISSUE THREAD

**Issue by akeix** [Vocaluxe/Vocaluxe#360]
Hello,

On the nightly version, the duet mode no longer works.
Both players play and earn points on the same singer.

For example, on the song "this blue dream" of the movie Aladdin, both players play and earn points with Aladdin. When it's Jasmine's turn, no player earns points. The lyrics are displayed but the notes disappear.

**Comment by Stefan1200-de** [comment]
You have this issue only with this song? Does this issue still exists with the current nightly?

**Comment by akeix** [comment]
with the current nightly, it's OK

**Comment by Stefan1200-de** [comment]
Thanks for reporting back. I close this issue now.
