### ISSUE TITLE
StaticExtra , ScreenScore.xml 

### ISSUE THREAD

**Issue by askusbloodfist** [Vocaluxe/Vocaluxe#362]
Hi there! I dont know if you remmeber me. I was the guy working on the Theme "Simple" Ive seen you been hard work on Vocaluxe. So i started working on my Theme and been doing some changes. Do you remmeber the implementation you did about "StaticExtra" You did that so i could add a static that changes color to the diffrent players. 

Could you maby add this so its usable in the ScreenScore.xml =?

**Comment by lukeIam** [comment]
@flokuep Can you help here?

**Comment by flokuep** [comment]
StaticExtra was not about having colors in place, more having statics on the correct positions. It makes a difference, if the SingScreen shows 1 or 6 players, so you can show for every player P with total players N different statics (and colors can be also varied of course).

It's not hard to add this to ScreenScore, should be straight forward. Unfortunately, I don't have time currently. If you have some experience with coding, you might try it yourself...

**Comment by marwin89** [comment]
closed due inactivity. please re-open if needed.
