### ISSUE TITLE
Problems with "Control Vocaluxe with smartphone"

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#364]
When using last nightly build (37d5373 - 29.12.2017) I accessed Vocaluxe via iPhone (Port: 3000). Then I got problems:
1. First I tried to create profile via iPhone, but when clicking "Speichern und hochladen" I get an error: Bad Request . This happens with and without taking a photo upfront. I haven't logged in before.
BTW: Is a password required?

2. How can I login on smartphone with already defined users? What password?

3. "Nehme ein Foto auf und zeige es am Ende der Runde an" isn't showing any picture. What is wrong?

(Firewall disabled on PC.)

**Comment by Michri** [comment]
Am I the only one having this issue?

**Comment by lukeIam** [comment]
Hi @Michri,

the whole app/webserver needs a rewrite but the basic functions should work in most situations. 

> First I tried to create profile via iPhone, but when clicking "Speichern und hochladen" I get an error: Bad Request . This happens with and without taking a photo upfront. I haven't logged in before.
> BTW: Is a password required?

Can confirm this -> that whole profile creating/editing is broken atm.

> How can I login on smartphone with already defined users? What password?

Yes the users are the same and if no password is defined it's a blank password. As the passwords are stored salted and hashed there is no easy way to set a password without the profile edit feature.

> "Nehme ein Foto auf und zeige es am Ende der Runde an" isn't showing any picture. What is wrong?

Do you see the image in the Photos folder?

**Comment by lukeIam** [comment]
The problems are caused by the change to GUID-PlayerIds...
