### ISSUE TITLE
Better error logging/reporting

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#365]
As we often have problems reproducing or understanding problems of users we should improve our logging/reporting capabilities.

- [x] Distribute debug symbols with the releases #353 
- [x] Create the possibility to log more info
I looked around a finally decided to give [Serilog](https://serilog.net) a try:
In my test branch https://github.com/lukeIam/Vocaluxe/tree/improvedLogging logging is working fine, but I'm unhappy with the structure (atm I had to decide between auto source enrichment or manual objects). I already have an Idea how to solve this, but there are some project and c# language limitations I will have to work around.
- [x] Some GUI for uploading current (or last log after total crash) to gist(?) + maybe opening the browser with a new issue and the gist link pre-filled.

**Comment by lukeIam** [comment]
@flokuep 
My current plan includes to move the `CLog` class to `VocaluxeLib` -> we would get rid of `ILog`-`CBlog`-construct.
The only thing that would change in "Main-Vocaluxe" would be that we have to include `VocaluxeLib.Log` instead of `Vocaluxe.Base`.

I'm I missing something?

**Comment by flokuep** [comment]
No, this would work But you need to ensure first, if all methods we need in CLog are available over VocaluxeLib-API.
