### ISSUE TITLE
Should Vocaluxe exclude skipped songs?

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#366]
We just played with last nightly build (29.12.2017). It was running really well (Thanks!), but

Playing any kind of party mode caused some surprised players. Within the same game (after a round) songs already skipped with jokers in rounds before were appearing again. That’s annoying. Can songs skipped via jokers be removed from pool - in same way as already played songs?

**Comment by Michri** [comment]
Am I the only one having this issue?

**Comment by lukeIam** [comment]
As explained in https://github.com/Vocaluxe/Vocaluxe/issues/368#issuecomment-364075481 the random function in party mode works with a random list of all songs that match the criteria.
Jokers just skip a song and take the next one from the list.
If the list runs empty it is refilled with all songs and shuffled again.
-> So you only having the chance to get a skipped song again if you've sung/sikpped all songs.

Do I understand stand you correct: you would like to ignore all joker skipped songs for the refill and sing already sung songs again? In my opinion a joker is a one time skip for the person that is currently using it. If the song will appear again (under the rare circumstances stated above) maybe two other persons like to sing it.

**Comment by daggeg** [comment]
I’m with lukelam on this. If it’s not easy to add this as an in-menu-option I think we should close this issue.
