### ISSUE TITLE
Random functionality not random enough?

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#368]
We just played with last nightly build (29.12.2017). It was running really well (Thanks!), but

Songs being played are not really shuffled. We were playing Vocaluxe already for several months. We have about 300 Songs in there. Since yesterday we always had sorting by artist configured.
Of course we got different songs from our pool provided, but during the months it felt like we were getting mostly every time the same collection.
Yesterday we switched song-sorting from by artist to unsorted. Suddenly we got songs from our song collection we never had before.

Would be cool to get songs shuffled in a better way. Right now it feels like not fully mixed.

**Comment by Michri** [comment]
Am I the only one having this issue?

**Comment by Nefrin** [comment]
No, you are Not the only one. We exerienced the same issue about Four years ago with 0.3.

Having gathered some experience with C# in the mean time I have the feeling it’s something with the initialisation of the random function that shows fairly apparent patterns in the first bunch of random numbers. 
This however is just a guess, I have not looked at the code yet. (Trying to find myself some time for that for four years now :( )

**Comment by lukeIam** [comment]
> Having gathered some experience with C# in the mean time I have the feeling it’s something with the initialisation of the random function that shows fairly apparent patterns in the first bunch of random numbers.

You are right: c#'s random algorithm is a pseudo random algo which depends on the initialization seed.
But we are using the default constructor for creating a `Random` object:https://github.com/Vocaluxe/Vocaluxe/blob/37d53739928b7d0dea441e2da4d284c59393bc1a/Vocaluxe/Base/CGame.cs#L41
And according to the documentation the default constructor `initializes a new instance of the Random class, using a time-dependent default seed value.` (https://msdn.microsoft.com/en-us/library/h343ddh9(v=vs.110).aspx) So in this case the random number generator shouldn't be the problem.

I haven't wrote the code for random song selection and I personally don't use it when playing Vocaluxe but I had a quick look at the code:
It seems that there is some logic applied to preselect song before random drawing.
Without going deep into the code:

1. Calculate the average play count over all visible songs
2. Add all songs which where played less or equal that average to a list
3. If no songs where found add all visible songs (I think this step is not required as the `<=` already handles the case where all songs have the same play count)
4. Draw a song randomly from this list
5. All further draws will also be taken from this list
6. If the list is empty the algorithm starts again

If you have an idea how to make the random functionality better we can discuss them here.

@Nefrin If you want to have a look into the code this is the relevant part:
https://github.com/Vocaluxe/Vocaluxe/blob/be9e54d7d5ece0311e902c41bee00ef4e1e54774/Vocaluxe/Base/CSongs.cs#L206-L237

**Comment by lukeIam** [comment]
A bit off topic:
@flokuep We should may think about to but such really common code like the `UpdateSongList()` method to the base class `CMenuParty` (as a "generic" version working with all filters). If you already done this during your party mode restructuring project, even better ;)

**Comment by lukeIam** [comment]
A bit off topic:
@flokuep We should may think about to but such really common code like the `UpdateSongList()` method to the base class `CMenuParty` (as a "generic" version working with all filters). If you already done this during your party mode restructuring project, even better ;)

**Comment by lukeIam** [comment]
@Michri @Nefrin 
As described in https://github.com/Vocaluxe/Vocaluxe/issues/368#issuecomment-364075481 I think Vocaluxe's random functionality is really random.  
If you have an idea how to improve the random-song-selection-algorithm please comment here and I will reopen this issue.

**Comment by Michri** [comment]
I am no developer expert, so hard for me to dig into the code, but it still feels like an issue.
In our parties people always complain about getting sams songs on each party and some songs are never played 😩
Would be cool to get this solved.
