### ISSUE TITLE
Make Vocaluxe compatible with ffmpeg 3.3 / 3.4 / or newer

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [Vocaluxe/Vocaluxe#381]
Vocaluxe so far only accepts ffmpeg 3.2. To have it working on multiple linux distributions it would be requiered to always make it compile against the newest versions of ffmpeg. In this case: ffmpeg 3.3 and 3.4.

So if someone is into this topic it would be nice to work on that.

Also, they made these adjustments for UltraStar Deluxe already. Maybe it's work having a look on the headers there. Thansk :)

**Comment by lukeIam** [comment]
ffmpeg api is very unstable and I don't have the time to keep up with the modifications.
And in my opinion it's not really a problem for Vocaluxe to use older ffmpeg versions - at least the the Windows build (and thats the main part atm)

For Linux we could ship the older versions in a flatpak/snap/...

**Comment by cRaZy-bisCuiT** [comment]
The flatplack solution sounds convienient to me. Still if someone feels like implementing it, I think it's not a problem to leave the ticket open.

**Comment by cdjm** [comment]
Just an idea: Wouldn't it be possible to let gstreamer do the handling of ffmpeg instead?
Gstreamer has to be included anyway for the playing of audio so why not let them do the handling of ffmpeg?
Alternatively using libvlc as proposed in #382 could do the trick.

**Comment by lukeIam** [comment]
> Just an idea: Wouldn't it be possible to let gstreamer do the handling of ffmpeg instead?
> Gstreamer has to be included anyway for the playing of audio so why not let them do the handling of ffmpeg?
> Alternatively using libvlc as proposed in #382 could do the trick.

Quite some time ago I had a look on gstreamer's video capabilities and libvlc:
- both would fit
- gstreamer is much easier to use
- none of them support hardware accelerated decoding and zero copy in our scenario
  - gstreamer has a only paid package that may fit
  - libvlc does supports zero copy but as far as I found out only if their player window is the target

I came to the conclusion not to invest much time into a new video system with out getting real hardware accelerated playback (as far that I can remember we are using 30-40% of the CPU just for video decoding).

In my opinion Vocaluxe would need a rewrite anyway - at to many points the UI and logic is tightly mixed and not abstracted. Moreover Vocaluxe depends on a lot of plugins - some are required versions are very old, some are not longer developed and some are not so easy to use with Linux.

I'm toying with the idea to do a UI rewrite for Vocaluxe in Unity.
With unity we could replace many of our dependencies with all in one, popular and actively developed system.
As far as I know hardware accelerated video playback is also supported by Unity's video player.
Also we could achieve platform portability much easier.

I already started a test balloon with unity, a flexbox based ui layouting and strict UI separation (see my [ui_study_yoga branch](https://github.com/Vocaluxe/Vocaluxe/tree/ui_study_yoga)).
But thats more a pre-project to get a better feeling how to design the hole system.

Now the bad news: at the moment I definitely have no time to work on Vocaluxe - sorry...
I hope that in one or two month it will better - but can't promise it.
But I'm still motivated to continue contributing to Vocaluxe 😉

**Comment by cRaZy-bisCuiT** [comment]
@lukeIam thanks for your ideas.

About the engine / Unity: Wouldn't Godot as a FOSS engine be a far better choice then unity? They recently changed their license and e.g. companies using streaming services got trouble. 

They could also enforce tighter rules of usage for FOSS projects as well so I'd be a little worried if a FOSS projects uses their engine.

**Comment by lukeIam** [comment]
> They recently changed their license and e.g. companies using streaming services got trouble.
I read it in the news...
But as far as I understand using a self hosted or cloud hosted unity game server ist not a problem.
Only if you offer a service offering unity bundled with 3rd party software this is a problem.
(their view: https://blogs.unity3d.com/2019/01/10/our-response-to-improbables-blog-post-and-why-you-can-keep-working-on-your-spatialos-game/)


> Wouldn't Godot as a FOSS engine be a far better choice then unity?

I just had a short look on Godot (I could get some things wrong):
- Only OpenGL and no DirectX support (in the past I experienced some OpenGL with windows - but could be fixed)
- Videoplayer only supports OGV Theora and no other formats
- Could not find anything about gpu accelerated video decoding and zero-copy displaying

It's not easy to find a framework which:
- is easy to use / all features are well integrated (we do not have so much time for developing)
- supports 2d rendering without hacks
- supports gpu accelerated video playback
- supports DirectX and OpenGL
- supports Windows and Linux (and maybe Android)
- has a huge community/maintainer -> want to migrate to a framework that will still be developed in the next years


> They could also enforce tighter rules of usage for FOSS projects as well

Thats always a risk if a company is the main maintainer.
There are also a some FOSS projects which "main branch" went limited or closed source.
But I don't think Unity will do that - they seem to have a working business model and why should they kill the community they also profit from.

Short: I don't see a real problem with using Unity - but I'm open for suggestions.

**Comment by lukeIam** [comment]
> * **Videoplayer**: That's true! You could encode videos in real time with ffmpeg though to play other formats using FFMPEG. Shouldn't be an issue for current hardware. Just low performance devices like RaspberryPi might fail.
>   https://godotengine.org/qa/4595/how-to-play-a-video

May people use an old system (or an rapberry pi) as party pc.
Currently we are using a huge amount of the required CPU time just for ffmpeg decoding and copying fames around.
And realtime transcoding would make the everything even slower, as we would do something like this:
`decode source format -> encode to OGV Theora -> decoding for displaying`  
Also it would be tricky to sync this pipeline, when we have to seek (e.g for the preview).
The second solution from you link can't be used in Vocaluxe as we require non full-screen rendering.

> * **gpu accelerated video and zero-copy displaying**: For the first thing I don't find anything either. We could still rely on ffmpeg?
>   I have no clue about zero-copy displaying

The Idea is if we invest so much time in a separating Logic and UI and do a UI-rewrite why not use gpu accelerated video decoding, as this would save a lot of cpu resources and makes Vocaluxe playable on even more low powered devices (e.g. raspberry pi).   
Zero-Copy describes gpu accelerated video decoding where the decoded frames are not transferred to the CPU but directly rendered to a surface.
Theoretically this can also be done with ffmpg -> but it's definitely not easy  (I failed)  

With Unity we could get this with not to much effort. Also unity abstracts the different hardware accelerated decoding APIs for the different systems:
```
This hardware acceleration is made possible by native custom APIs, which vary from platform to platform. Unity’s video architecture hides these differences by providing a common UI  and Scripting API in order to access these capabilities.
```

I'm sorry but imho Godot in it's current state and what I read about it, it's not the right framework for rewriting Vocaluxe's UI-System.
Nevertheless, we plan to keep the UI code separated from the actual rendering code.
So changing the framework should not be so hard in future as it currently is 🙈 .

**Comment by cRaZy-bisCuiT** [comment]
Well, this was just an idea. Thank you for your detailed informations!
