### ISSUE TITLE
Error in initializing of Direct3D

### ISSUE THREAD

**Issue by Rom888** [Vocaluxe/Vocaluxe#383]
Can't run program. 

### Steps to reproduce
Just after run I have got error window (attached logfile below).
I use windows 10 with DirectX12,
Intel(R) HD Graphics 515,
Notebook asus ux305ca.
I updated Intel(R) HD Graphics 515 drivers, but error still occurs.

### Vocaluxe version and logfile
Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-256-g48975b1)
https://gist.github.com/3668295f33f995b1a004037c9fb97f20

**Comment by flokuep** [comment]
Vocaluxe needs DirectX9 to run. Please install this and try it again: http://www.microsoft.com/download/en/details.aspx?id=8109

DirectX12 doesn't includes DirectX9, so you might need both on your machine.

**Comment by Rom888** [comment]
I have installed what you suggested and it works now!
Thank you!
Great software.
