### ISSUE TITLE
Video freezing

### ISSUE THREAD

**Issue by Rom888** [Vocaluxe/Vocaluxe#384]
Very noticeable video freezes occurs on Game and Song screens.
This happens on a not very powerful notebook, but everything is fine with the video using UltraStar Deluxe on the same PC. 
Separately in the MPC-HC player any video is played without any problems, even Full HD.

Are there any recommendations for solving this?

Configuration:
Windows 10 x64, 
NVIDIA® ION™ Graphics
1GB RAM
Intel® Atom™ D330 (Dual Core; 1.6GHz) Processor

**Comment by Stefan1200-de** [comment]
I guess the MPC-HC player is using hardware decoding to play this video, Vocaluxe maybe not (I'm not a Vocaluxe developer, I can just guess). But an Intel Atom chip is really very slow, I even have problems on my 4 years old Pentium Quadcore CPU (N3700) sometimes, which is around 200% faster than your Atom D330 chip.

**Comment by deinlandel** [comment]
Nope, it's not about performance. I have a Core i7 8700K and Geforce 2080ti and still video freezes in songs. There's something wrong with video playback in game

**Comment by Stefan1200-de** [comment]
@deinlandel Well, on my Core i7 7700k with GTX 1070 and my second PC Ryzen 1500X with GTX 1050 Ti I don't have this problems. Maybe your video files are broken?

**Comment by marwin89** [comment]
After 4 years inactivity I close this issue.
