### ISSUE TITLE
Nightly - After singing a single song, the first song will be selected in song menu list

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#390]
Tested the nightly from January 2018 and the current nightly from 5.5.2018:
After singing a single song, I come back to the song menu list and the first song at the top of the list will be selected. So after every song, I have to scroll down the big song list again to come back to the last sung song.
Using song menu style: list

Vocaluxe 0.4 does not have this issue, the last played song will be selected in that list. This is also what I would expect from future versions.

**Comment by lukeIam** [comment]
confirmed...

**Comment by lukeIam** [comment]
The `_SongMenu.LeaveSelectedCategory()` (https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Screens/CScreenSong.cs#L657) resets the the old selection.

The whole block is new and wasn't there in 0.4.0. But I'm not sure how and what exactly it does...
@flokuep Can you help here?

**Comment by flokuep** [comment]
Well, it's some time ago i've changed something here. But as far as I remember, we need to check here if there is a changed CategoryIndex from PartyMode and enter this category (and if there is now category, so we need to go back to category overview).

Currently can't say where CategoryIndex for _normal_ singing is saved (might be in SongMenu or in CBase.Songs), but you could check if adding another check in the if-condition for PartyMode could work. We might need an else-block for entering category after that 🤔

**Comment by Stefan1200-de** [comment]
Are you able to locate this issue?

**Comment by flokuep** [comment]
Sorry, currently no time for coding or resolving bigger issues (and this is one).

**Comment by AlecScudder** [comment]
I thought once the duets bug was fixed I could go back to trying a current build, but this is annoying enough to put me back to version 0.4.  I have over 500 songs and it is just no fun to have to have it reset to the first song after every song.

I poked through the code and unfortunately, I'm not skilled enough to figure out a solution for this one.

I hope that someone capable finds time to fix this bug soon. I appreciate all the efforts of those who are more skilled than me!  thanks.

**Comment by Stefan1200-de** [comment]
Still using Vocaluxe 0.4 because of this bug. But unfortunately one PC of mine can't use Vocaluxe 0.4 because of issue #324. Is it possible to get another Vocaluxe 0.4 release with just #324 fixed?

**Comment by lukeIam** [comment]
> Still using Vocaluxe 0.4 because of this bug. But unfortunately one PC of mine can't use Vocaluxe 0.4 because of issue #324.

Hi @Stefan1200-de,

unfortunately flokuep and I do not have any time for Vocaluxe programming (or making a new release) at the moment.
I hope that I will have some more time for Vocaluxe in the next year - we will see...

> Is it possible to get another Vocaluxe 0.4 release with just #324 fixed?

You can try this branch (it includes #324):
https://github.com/Vocaluxe/Vocaluxe/tree/release-0.4.1

You can build it yourself or I can trigger a CI build for you later today.

**Comment by lukeIam** [comment]
> You can build it yourself or I can trigger a CI build for you later today.

https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/build/job/3m1voxbdtn3dusq4/artifacts

**Comment by daggeg** [comment]
I think this bug arose after flokeup fixed the problem in challenge mode where not all players got to sing the same number of songs. For instance, if you’d chosen 10 rounds most participants endes up singing 10 songs. But most of the time at least one player only got to sing 9 while another got to sing 11. Which was not good i challenge mode. And as I recall it this bug of the first song showed up as soon as that bug was fixed.

**Comment by daggeg** [comment]
It’s a shame. Vocaluxe would be absolutely perfect if only this bug could be fixed. Noone out there with programming skills who would be able to help out?

**Comment by daggeg** [comment]
> The `_SongMenu.LeaveSelectedCategory()` (https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Screens/CScreenSong.cs#L657) resets the the old selection.
> 
> The whole block is new and wasn't there in 0.4.0. But I'm not sure how and what exactly it does...
> @flokuep Can you help here?

Since the bug arose when fixing the challenge mode problem I've mentioned above I guess this in CScreenSong.cs#L657 relates fo the changes in CSongMenuFramework.cs#289-293,  ISongMenu.cs#43 and perhaps CPartyModeNormal.cs#66.

**Comment by Stefan1200-de** [comment]
So, I debugged a little bit in the last 80 minutes. I found the reason for this bug.

It was this commit, the change at the file VocaluxeLib/Menu/SongMenu/CSongMenuFramework.cs:
https://github.com/Vocaluxe/Vocaluxe/commit/1b0c40a20b3d44fe156312ab257df0f30ef980b8#diff-c575bd092d254a04099f1b5057ccaa92

That commit implemented the call of CSongMenuList _LeaveCategory(), which itself calls a method CSongMenuFramework SetSelectedCategory() always with the value 0. And SetSelectedCategory() always sets the current selected song.

Here my debugging output:
**On Song Screen, selecting the song number 572 by one key press!**
In CScreenSong _JumpTo: 572
In CSongMenuFramework SetSelectedSong: 572
In CSongMenuList _SelectionNr - Previous selected song: 0
In CSongMenuList _SelectionNr - New selected song: 572
**#### Sing Screen, stopping song after some seconds and go back to Song Screen ####**
In CSongMenuFramework LeaveSelectedCategory
In CSongMenuList _LeaveCategory: 0
In CSongMenuFramework SetSelectedCategory: 0
In CSongMenuList _SelectionNr - Previous selected song: 572
In CSongMenuList _SelectionNr - New selected song: 0
In CSongMenuList OnShow: calling _EnterCategory(0)
In CSongMenuList _EnterCategory: 0
In CSongMenuList OnShow: 0
In CSongMenuFramework SetSelectedSong: 0
In CSongMenuList _SelectionNr - Previous selected song: 0
In CSongMenuList _SelectionNr - New selected song: 0

Here is the part which I don't understand, why does a method named like "SetSelectedCategory(int categoryNr)" set the selected song? And if this is wanted, why does _LeaveCategory() always set the selected song to 0?

If I remove the call of _LeaveCategory() in the CSongMenuFramework.cs at LeaveSelectedCategory() this bug is gone. But I don't know which other bugs might occur because of this. I don't know why @flokuep added this particular line.

**Comment by daggeg** [comment]
Well done Stefan! I'll make a build myself removing the _LeaveCategory() and see if I experience anything annoying.

**Comment by Stefan1200-de** [comment]
> Well done Stefan! I'll make a build myself removing the _LeaveCategory() and see if I experience anything annoying.

I guess flokuep had a reason to implement this, but without more information about his intentions and whats the reason of some of the functions in that chain between LeaveSelectedCategory() and SetSelectedCategory(int categoryNr) we can just build a solution around it and hope the best. :)

**Comment by Stefan1200-de** [comment]
With todays nightly this bug is fixed. But I have to know, if this temporary bug fix reopen other bugs. Please keep an eye open.

**Comment by Stefan1200-de** [comment]
Just open a new issue, if the implemented temporary fix open new bugs.
