### ISSUE TITLE
0.4.0 and Nightly May 5 - Disabling video preview not possible

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#391]
This issue was written in assumption that the setting **Video** / **Video preview** = **Off** should disable the video preview for the selected song in the song menu.

I tested Vocaluxe 0.4.0 and the newest Nightly from May 5, set all Video Options to Off. Disabling **Video backgrounds** and **Videos while singing** is working, no videos anymore. But after disabling **Video preview** I still get a video preview in the song menu after selecting a song. No matter if I use the Song-menu style **List** or **Tiles**, both have this issue. I also tested the Nightly from May 5 with default settings, I only changed the Video Options, same issue.

Does **Video preview** affect something different or is it really not working?

**Comment by lukeIam** [comment]
Hi @Stefan1200-de ,

sorry for the delay, but currently we are quite busy and don't have much time for Vocaluxe 😞 
However thanks for reporting this bug - I can reproduce it on my pc and will try to find time for a fix...

**Comment by lukeIam** [comment]
https://github.com/Vocaluxe/Vocaluxe/commit/3bec24f4ff6d95f5ede4daac814089d0877fa8e5 should fix this...

Build to test (when the CI has finished):
https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/build/254

**Comment by Stefan1200-de** [comment]
Thanks, I will test it this weekend.

For me is the issue #390 much more important. Do you have a solution for it too?

**Comment by lukeIam** [comment]
> Do you have a solution for it too?

I'm no so deep in Vocaluxe's screens... But I'm trying to find a solution.

**Comment by Stefan1200-de** [comment]
@lukeIam I can confirm, that your test build 3bec24f fix this Video Preview issue.
