### ISSUE TITLE
Odd number of players not working in Tic-Tac-Toe Party Mode

### ISSUE THREAD

**Issue by dr-waterstorm** [Vocaluxe/Vocaluxe#401]
If you setup a Tic-Tac-Toe game (Latest nightly build as of 29.10.18) with two teams and for example 5 players (3 on team 1 and 2 on team 2), the game will only use the first 2 players of team 1 and match them against both of team 2. 
The 3rd player of the first team will never be chosen to sing a song.
For now I've just added a "Guest" to the second team, 3on3 is working just fine. But it should be possible to also play with an odd number of players.

**Comment by Stefan1200-de** [comment]
Michri commented on 10 Feb 2019 at issue #412 
"HI,
we played again Vocaluxe. This time with 6 microphones and different game-scenarios.

Playing Party > Tic-Tac-Toe (16 fields, refill jokers, all songhs, short-version, adding 3 persons to each team)

Only first 2 players per team were involved into the game. Last players being added never had to sing."

**Comment by marwin89** [comment]
This bug is solved by ✅ 
- https://github.com/Vocaluxe/Vocaluxe/pull/636

Merged into nightly, official release v0.5.0
