### ISSUE TITLE
Forced close with Chinese songs in latest nightly

### ISSUE THREAD

**Issue by Xyde** [Vocaluxe/Vocaluxe#402]
Doesn't seem to happen on stable, nor other languages I've tested so far (French, Spanish, English).

**Comment by flokuep** [comment]
Coud you provide a sample text-file that triggers the crash and the error.log, please?

**Comment by dritz28** [comment]
Error-Log Vocaluxe 'Blue Sunrise' 0.4.0 (x86) (0.4.0-61-g81c3233) 4/24/2020 1:16:43 AM
----------------------------------------
...
4) Warning: Automatic changes have been made to C:\Ultrastar\張學友 Jacky Cheung - 李香蘭 (粤)\Jacky Cheung - Li Xiang Lan.txt Please check result!
Skipped 2 notes (0-Length: 0, Overlapping: 0, No text: 2)
Adjusted 1 line breaks (Overlapping previous note: 1, No length: 0)

5) Warning: Automatic changes have been made to C:\Ultrastar\張學友 Jacky Cheung - 每天愛你多一些 (粤,國)\Jacky Cheung - Love You A Little More Each Day (CAN).txt Please check result!
Skipped 24 notes (0-Length: 0, Overlapping: 0, No text: 24)

6) Warning: Automatic changes have been made to C:\Ultrastar\張學友 Jacky Cheung - 每天愛你多一些 (粤,國)\Jacky Cheung - Love You A Little More Each Day (MAN).txt Please check result!
Skipped 25 notes (0-Length: 0, Overlapping: 0, No text: 25)

7) Error opening video file: C:\Ultrastar\周杰倫 Jay Chou - 聽媽媽的話 (國) Listen to Mom\Jay Chou - Ting Ma Ma De Hua (Listen to Mom).mp4

8) Error opening video file: C:\Ultrastar\周杰倫 Jay Chou - 聽媽媽的話 (國) Listen to Mom\Jay Chou - Ting Ma Ma De Hua (Listen to Mom).mp4
9) Unhandled error: stream is null   at Vocaluxe.Base.CVideo.Skip(CVideoStream stream, Single start, Single gap)
   at Vocaluxe.Screens.CScreenSing._LoadNextSong()
   at Vocaluxe.Screens.CScreenSing.OnShowFinish()
   at Vocaluxe.Base.CGraphics._FinishScreenFading()
   at Vocaluxe.Base.CGraphics.Draw()
   at Vocaluxe.Lib.Draw.CDrawBase`1.MainLoop()
   at Vocaluxe.Lib.Draw.CDrawBaseWindows`1.MainLoop()
   at Vocaluxe.CMainProgram._Run(String[] args)
   at Vocaluxe.CMainProgram.Main(String[] args)

**Comment by dritz28** [comment]
Here's a sample text file:
[Jacky Cheung - Love You A Little More Each Day (CAN).txt](https://github.com/Vocaluxe/Vocaluxe/files/4527057/Jacky.Cheung.-.Love.You.A.Little.More.Each.Day.CAN.txt)

**Comment by flokuep** [comment]
Can you try to remove the Video-Tag (#VIDEO:Jacky Cheung - Love You A Little More Each Day.mp4) from your textfile? Vocaluxe seems to have some problems with your video.

**Comment by dritz28** [comment]
That totally worked.  Thanks!

**Comment by flokuep** [comment]
So looks like this video is maybe some kind of broken. Can you open it in a media player, like VLC for example and test if this is working there?
