### ISSUE TITLE
 A more advanced search option

### ISSUE THREAD

**Issue by Xyde** [Vocaluxe/Vocaluxe#403]
Currently the only way to filter option (date, artist, language) is by going through the option tab, and from a UX standpoint as somebody who juggles between filters a lot I would find it to be more convenient to make the filter available when choosing songs

Furthermore, the search option right now only allows for one letter search. With a very big library, a more in-depth search option allowing full keywords might prove to be more useful.

**Comment by flokuep** [comment]
- Yeah, having sort-options in song selection screen would be very nice, we have to rethink the whole song selection process UX-wise, I guess.

- Search: Did you know our integrated search (pressing F3 button)? This will search in title, artist and selected sorting (edition, genre, ...).

**Comment by Stefan1200-de** [comment]
@flokuep unfortunately CTRL + F / F3 also search for directory names. So if I have multiple txt files in the same directory (e.g. normal and duet versions of the same song) and the directory name has the word duet behind the artist / title name, this search will find both files. ;)

I solved it for me by renaming all directories. ;)

**Comment by Zapiboss** [comment]
@Stefan1200-de Hey, it's strange, but i can't search for folder names. Only artist and title names.
Did you do something in particular ?
I tried the nightly version and the stable one.

**Comment by Stefan1200-de** [comment]
> @Stefan1200-de Hey, it's strange, but i can't search for folder names. Only artist and title names.
> Did you do something in particular ?

Just like I wrote, CTRL + F. I had to rename folders to make sure, that not all txt files will be found, if I search for the directory name. Tested in version 0.4.

**Comment by Zapiboss** [comment]
Yeah, i tried CTRL + F (or F3), and most of my folders were already renamed, see screenshot : 
![image](https://user-images.githubusercontent.com/4704947/60769379-3175f800-a0cf-11e9-8ee2-697038003ae9.png)

Using the same version as yours, i don't see the "Sword Art Online" songs.
![image](https://user-images.githubusercontent.com/4704947/60769399-684c0e00-a0cf-11e9-8f56-aab3e685138e.png)

Where did i do something wrong ? Do i need to also rename the txt files ?

**Comment by Stefan1200-de** [comment]
I can just say, that my Vocaluxe on Windows is searching for folder names too.
![image](https://user-images.githubusercontent.com/15168351/60940876-56d85100-a2dd-11e9-93c4-50405407d8e0.png)

![image](https://user-images.githubusercontent.com/15168351/60940861-4a53f880-a2dd-11e9-985f-c1e199b72d45.png)

**Comment by Stefan1200-de** [comment]
I implemented stuff like this, check out:
release-0.4.1 branch: https://github.com/Vocaluxe/Vocaluxe/pull/431
develop branch: https://github.com/Vocaluxe/Vocaluxe/pull/432

If you need binaries, currently I have them only at my own fork of Vocaluxe:
https://github.com/Stefan1200-de/Vocaluxe/releases

But I will add this changes in the official nightly too, but I need some more time.

**Comment by Stefan1200-de** [comment]
The most parts of your wishes are now included in the current nightly. Do you still miss something?

**Comment by Zapiboss** [comment]
![image](https://user-images.githubusercontent.com/4704947/72225812-04c50080-358a-11ea-8a0e-d98962de2fac.png)
Much better this time, i can search by folder name !
I took 5 minutes to figure out that i had to CTRL + F (for search function) and after that type "fo: NAME_OF_THE_FOLDER".

Thank you very much, Vocaluxe just got a lot better now !

**Comment by Stefan1200-de** [comment]
Oh, okay. 5 Minutes is long, how I can make this better? Do you see the new help text at the bottom, which show that you can use the F3 key (do the same as CTRL+F) for the search function?

I wish I had more space to put some examples to the help text file the search bar is visible, so it would be easier to understand, that "fo:Mahou" (in your example) would work.

**Comment by Stefan1200-de** [comment]
Oh, and did you see, that you now can just type elisa without open the search bar, to jump to the first entry with a song from elisa?

**Comment by Zapiboss** [comment]
No, i think the problem comes from me, i didn't noticed it at first.

Maybe you should put replace the text at the bottom by something like : 
"F1 = Open help menu / Open commands menu"
and then, you put everything here ?

But if you leave like that, it's also fine, that way, they can clearly see what to do to filter.
Personally, i prefer you leave it like that.

And without opening the search bar, if i type ELISA, it did nothing
I have to sort the songs in the options by 'Artist' to make it work.

**Comment by Stefan1200-de** [comment]
Thanks for your opinion. I leave the line like it is now, maybe someday I also add an overlay on F1, which shows everything a little bit more detailed.

> And without opening the search bar, if i type ELISA, it did nothing
> I have to sort the songs in the options by 'Artist' to make it work.

oh, but that should also work for other sorting options like folder, title or year. If you sort for the year, you can just type 2002 to jump to the song from that year. Same for folder or title.
