### ISSUE TITLE
Nightly doesn't recognize .NET when starting 

### ISSUE THREAD

**Issue by xyxyxyxy49** [Vocaluxe/Vocaluxe#405]
Hey Guys,
i tried to start the current nightly Version (0.4.0-327), and it stopped directly asking for .NET 4.7.1. 
I've been using Windows x64 (Build 17754, Windows Insider Slow Ring), which has .NET 4.7.2 preinstalled. 

But it doesn't get recognized by Vocaluxe. I could resolve the issue by simply changing the "Vocaluxe.exe.config" in line 4 from
`<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1"/>`
to
`<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7"/>`

**Comment by flokuep** [comment]
Thanks, will check this.

**Comment by lukeIam** [comment]
> I've been using Windows x64 (Build 17754, Windows Insider Slow Ring), which has .NET 4.7.2 preinstalled.

Normally .NET 4.7.2 Runtime is backward compatible with all 4.x executables.
But in this case this is a known bug in your Windows Preview Build 17754:
```
Known issues
[...]
[ADDED 9/12] Apps that use .NET 4.7.1 will not work correctly on this build. As a workaround until then, you can change your app config to list 4.7.2 instead of 4.7.1 to correct the issue. Or you can change/add these registry keys:
Both X86/X64: [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework,Version=v4.7.1]
X64 only:[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework,Version=v4.7.1]
```
from:
https://blogs.windows.com/windowsexperience/2018/09/05/announcing-windows-10-insider-preview-build-17754/
