### ISSUE TITLE
16 round on the 14 round it crashed after the 13th round

### ISSUE THREAD

**Issue by goncalofalcao** [Vocaluxe/Vocaluxe#408]
Describe your issue here.

### Steps to reproduce
16 round on the 14 round it crashed after the 13th round. ON THE NEW EVEEEEE(POKEMON)!!!!!

Will push a fix tomorrow

### Vocaluxe version and logfile
Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-327-gfda7d4a)

**Comment by Stefan1200-de** [comment]
You have more details for this issue?
