### ISSUE TITLE
Any new version available?

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#411]
I wonder, if there is some progress on a new version. Last nightly build is quite old and some feedback was already sent in by several players.

**Comment by Stefan1200-de** [comment]
Well, the last code change was 8 month ago. The devs wrote a year ago, that they don't have much time currently. But I hope, the development continues in a not so far future, because from all UltraStar clones I only like Vocaluxe.

**Comment by Stefan1200-de** [comment]
@flokuep and @lukeIam Do you already know if and when the development of Vocaluxe continues? May chocolate help? ;) I would send some to you :)

**Comment by Stefan1200-de** [comment]
Lets see, if I can add some new stuff and bugfixes in the next time. But please don't expect big steps, since the main developers still have no time for Vocaluxe.
