### ISSUE TITLE
People excluded from game

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#412]
HI,
we played again Vocaluxe. This time with 6 microphones and different game-scenarios.

Playing Party > Tic-Tac-Toe (16 fields, refill jokers, all songhs, short-version, adding 3 persons to each team)

Only first 2 players per team were involved into the game. Last players being added never had to sing.

**Comment by Stefan1200-de** [comment]
Which Vocaluxe version did you used?

**Comment by Stefan1200-de** [comment]
Same issue: #401
