### ISSUE TITLE
Gamepad not working

### ISSUE THREAD

**Issue by rodmilak** [Vocaluxe/Vocaluxe#419]
I have built the newest build using visual studio 2019 and set the value in CContriller.cs to true in line 77. https://github.com/Vocaluxe/Vocaluxe/blob/fda7d4acb33b155cbe9b1c265da84b3e591e4f8f/Vocaluxe/Base/CController.cs#L77

But when i have a DS4 Controller (official ps4 controller from sony) connected via Bluetooth on my Laptop the game would still not recognize any inputs I try to do on my gamepad. Any pointers on how to resolve my issue? I am running a Samsung np305v5a Laptop on Windows 7 with an Intel 3160HMW BT module. 

Responses in german are welcome as well.

**Comment by lukeIam** [comment]
Hi @rodmilak ,

changing that line in `CController.cs` should not be necessary
https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Lib/Input/CGamePad.cs#L96
should be relevant line. 

The problem with your ps4 controller is that it does not support XInput. Possible workaround for you (haven't tested it): https://github.com/Jays2Kings/DS4Windows

**Comment by rodmilak** [comment]
The gamepad does output XInput via the SCP driver (an XInput wrapper) that I using. Any idea why it still doesn't work? I will try using DS4Windows and will update you if that works.
