### ISSUE TITLE
Crash on Duet mode

### ISSUE THREAD

**Issue by LegolasV** [Vocaluxe/Vocaluxe#42]
With certain duet songs, I get a crash with an index out of bounds error. (The actual error is in Dutch.)
This seems to be related to certain duet mode songs that have a "#DUETSINGERP1" and "#DUETSINGERP2" tag in the header, although this may just be a coincidence.

**Comment by lukeIam** [comment]
I'll close this issue because it seems to be fixed...

@LegolasV If your problem still exists feel free to reopen it.
