### ISSUE TITLE
Sound upon song selection "repeats" for 2-3 seconds before starting

### ISSUE THREAD

**Issue by deuteragenie** [Vocaluxe/Vocaluxe#423]
On Windows 7 64 bit with nightly as at 20 Aug 2019.

Upon song selection, the current selected song sound frame seems to "repeat" for 2 or 3 seconds before the song starts to play.  No issue afterwards.

Expected behavior is that the selected song starts to play "cleanly" without repeats of the current frame.

**Comment by marwin89** [comment]
Couldn't reproduce this error. This might be already solved with the new nightly builds in 2024.
Please re-open this issue if needed.
