### ISSUE TITLE
Build failed (ReleaseWin/x86)

### ISSUE THREAD

**Issue by Scylin232** [Vocaluxe/Vocaluxe#425]
Hello! I would like to make my own changes and modify Vocaluxe, but when I build, I get the following errors:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0006	Metadata file 'C:\Users\Scylin\Source\Repos\Vocaluxe\Output\Vocaluxe.exe' could not be found	Tests	C:\Users\Scylin\Source\Repos\Vocaluxe\Tests\CSC	1	Active
Error		The command "if exist "C:\Users\Scylin\source\repos\Vocaluxe\Output\PartyModes\Challenge\Code" rd "C:\Users\Scylin\source\repos\Vocaluxe\Output\PartyModes\Challenge\Code" /S /Q
cd C:\Users\Scylin\source\repos\Vocaluxe\Partymodes\
xcopy "C:\Users\Scylin\Source\Repos\Vocaluxe\PartyModes\PartyModeChallenge\*.cs" "C:\Users\Scylin\source\repos\Vocaluxe\Output\PartyModes\Challenge\Code\" /EXCLUDE:Excludes.txt /I /Y" exited with code 9009.	PartyModeChallenge			
Error		The command "if exist "C:\Users\Scylin\source\repos\Vocaluxe\Output\PartyModes\TicTacToe\Code" rd "C:\Users\Scylin\source\repos\Vocaluxe\Output\PartyModes\TicTacToe\Code" /S /Q
cd C:\Users\Scylin\source\repos\Vocaluxe\Partymodes\
xcopy "C:\Users\Scylin\Source\Repos\Vocaluxe\PartyModes\PartyModeTicTacToe\*.cs" "C:\Users\Scylin\source\repos\Vocaluxe\Output\PartyModes\TicTacToe\Code\" /EXCLUDE:Excludes.txt /I /Y" exited with code 9009.	PartyModeTicTacToe			
Error		The command "powershell -ExecutionPolicy Bypass -File C:\Users\Scylin\source\repos\Vocaluxe\\.build\winPreBuild.ps1 C:\Users\Scylin\Source\Repos\Vocaluxe\Vocaluxe\ x86" exited with code 9009.	Vocaluxe			
`
Visual Studio 2015, NET Framework 4.7.1

**Comment by Stefan1200-de** [comment]
Did you just opened the Vocaluxe.sln with Visual Studio? I use 2019 and don't had this kind of problems.

**Comment by Scylin232** [comment]
I Resolved the Problem

10 января 2020, 18:53:47, от "Stefan" <notifications@github.com>:

Did you just opened the Vocaluxe.sln with Visual Studio? I use 2019 and don't had this kind of problems.

**Comment by Stefan1200-de** [comment]
> I Resolved the Problem

How? Maybe you can share your solution for other people with this issue?

**Comment by Scylin232** [comment]
I Don't Remember, That's was long time ago

10 января 2020, 22:39:26, от "Stefan" <notifications@github.com>:

I Resolved the Problem
How? Maybe you can share your solution for other people with this issue?

**Comment by Stefan1200-de** [comment]
Okay, thanks. Have a nice weekend.
I close this issue now.
