### ISSUE TITLE
Nightly Builds

### ISSUE THREAD

**Issue by diver66** [Vocaluxe/Vocaluxe#426]
What's happening to the Nightly Builds the last one was done in 2018-10-24 ?

**Comment by Stefan1200-de** [comment]
Development was stopped, since the two developers have no time anymore. 2018 they wrote that they hope to come back 2019, but there are not many days left ;)

**Comment by Stefan1200-de** [comment]
I created my own fork with new features based on the release-0.4.1 branch, if someone is interested: https://github.com/Stefan1200-de/Vocaluxe/releases

**Comment by diver66** [comment]
Excellent ! thank, you very much

 

Von: Stefan <notifications@github.com> 
Gesendet: Mittwoch, 8. Januar 2020 16:35
An: Vocaluxe/Vocaluxe <Vocaluxe@noreply.github.com>
Cc: diver66 <joe@la-palma-tauchen.com>; Author <author@noreply.github.com>
Betreff: Re: [Vocaluxe/Vocaluxe] Nightly Builds (#426)

 

I created my own fork with new features based on the release-0.4.1 branch, if someone is interested: https://github.com/Stefan1200-de/Vocaluxe/releases

**Comment by flokuep** [comment]
Hey everyone,

yes, I'm not very active here. Thought there would be more free time for developing vocaluxe after finishing my master thesis, but yeah: Job, private stuff and so on...

I've invited @Stefan1200-de and @daggeg to the Github vocaluxe core team, so feel free to review your code, accept pull requests and/or release new versions. Build pipeline should be working for an releasing a new version. Just add a new git-tag on master-branch....

If you need some assistance, I might can find some time...

Thank you very very much for spending your time into this project!
Florian

**Comment by Stefan1200-de** [comment]
@flokuep thanks for your trust. I accepted your invitation. Currently I see myself just for smaller changes, but of course I try to help.

Maybe you have some time to look at my post from today at https://github.com/Vocaluxe/Vocaluxe/issues/390#issuecomment-572132419 to give me some answers to my questions at the bottom of my post?

**Comment by lukeIam** [comment]
> Thought there would be more free time for developing vocaluxe after finishing my master thesis, but yeah: Job, private stuff and so on..

Unfortunately, I'm in the exact same situation...

> Thank you very very much for spending your time into this project!

👍 👍 👍 

I will try to support you and may do some smaller stuff...

To this issue: the last nightly was on 2018-10-24 because the last change was done there.
Meanwhile we have new commits on develop but since Nov 2019 the pipline is broken.
Fix is incoming #441
