### ISSUE TITLE
Facebook group for developers and fans of Vocaluxe / Ultrastar

### ISSUE THREAD

**Issue by AlecScudder** [Vocaluxe/Vocaluxe#427]
Forgive me for posting this here, but Vocaluxe hasn't been developed in over a year, and one of the main fan sites for Ultrastar just got shut down. So in the interest of keeping these games alive, please feel free to join the new private Facebook group I created:

https://www.facebook.com/groups/karaokegamefans/

We can discuss further development of these games, as well as song creation, etc.

**Comment by Stefan1200-de** [comment]
Closing this issue now after 30 days. But thanks for this Facebook group!
