### ISSUE TITLE
Switching cover theme bug if game option Tabs is set to "on"

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#446]
The new genius cover themes do not seem to work fully as expected. Before restarting the game I get the following:
![Screenshot_2](https://user-images.githubusercontent.com/6724256/72461581-9ec9ba80-37cf-11ea-9a7b-08b5edf60833.png)

After restarting the game it seems to be ok though.

**Comment by Stefan1200-de** [comment]
I wrote it already yesterday here: https://github.com/Vocaluxe/Vocaluxe/issues/444#issuecomment-574388871

It's not a new bug of the new xml files, it is just a bug within Vocaluxe, which already exist for years. But in the last years there was only one xml file, so this was never tested. But it's good to have this bug as an issue, so we don't forget it.

**Comment by daggeg** [comment]
> I wrote it already yesterday here: [#444 (comment)](https://github.com/Vocaluxe/Vocaluxe/issues/444#issuecomment-574388871)
> 
> It's not a new bug of the new xml files, it is just a bug within Vocaluxe, which already exist for years. But in the last years there was only one xml file, so this was never tested. But it's good to have this bug as an issue, so we don't forget it.

Aha, ok.

**Comment by Stefan1200-de** [comment]
Implemented a workaround for this bug. It's not a real bug fix. I just find out, that disable and enable the tabs view will fix this issue. And this is now done, if you switch the cover theme.

I tried to debug the real issue, I guess in one of the sub functions at the ReloadCovers() function in the CCover class, but I preferred the workaround after one hour searching.

**Comment by Stefan1200-de** [comment]
@daggeg about this issue, is everything working now on your side?

**Comment by daggeg** [comment]
Yes. Everything seems to work as expected. A couple of seconds delay every start up if the folder option is on. One thing though, but I don't who'd be willing to do it, it would be nice with folder graphics for each of the cover theme skin's colours. As in the ambient theme.

**Comment by Stefan1200-de** [comment]
I didn't change anything on the folder option itself, but I guess you have a big library and the folder option does more sorting stuff, so it should be normal.

Well, I'm not a good gfx designer to create new graphics :)
I close this issue now.
