### ISSUE TITLE
Skip a single song while in mode "Ctrl + A" all songs in random order

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#453]
I think it would be great to add a button here saying "stop singing", but with the same meaning as the regular stop singing. That is, if the last line has passed the song will stop and the scores will be entered into the highscore list (and then you get to choose your next song if in regular mode). If pressing stop singing when in ctrl+A mode the song stops as well as the mode of ctrl+A stops.

It would therefore be nice to have two different stop singing buttons where one would mean stop the song and one where you stop the song AND mode of ctrl+A. Because it can be a bit tedious to have to wait 'til the song is over when there is e.g. two minutes left of the song after the last line. Perhaps the restart game button could be if it's a bit troublesome to enter a sixth button since that function almost seems to be superfluous when also having restart round (perhaps there is some usability to restart game that I don't get though?).  

![Screenshot](https://user-images.githubusercontent.com/6724256/72510232-58b13d00-3849-11ea-9201-c6dff71f5b82.png)

**Comment by diver66** [comment]
This idea is not bad, but this function already kinda exists, by using the Ultrastar Manager one can fix the audio length via the #END tag

**Comment by daggeg** [comment]
First of all this is not a big problem (perhaps it was unnecessary to mention it since this is not a problem if we use ctrl+R instead). But the thing is that sometimes you do want to listen to the rest of the song and sometimes you don't and I don't want to go through 1800 songs ;)

**Comment by Stefan1200-de** [comment]
@daggeg I thought the button **Skip this song** is for that?

**Comment by daggeg** [comment]
Oh, do I dare pressing that one after we’re done singing the song? I thought that button merely made you skip a song. I don’t want the scores to get lost. I should for obvious reason try it and see what happens.

**Comment by Stefan1200-de** [comment]
Well, I'm not sure about the highscore stuff, but at least the playlist should continue.

**Comment by Stefan1200-de** [comment]
The new hotkey CTRL + Right Arrow of pull request #458 could help here. Just skip to the end of the song with this hotkey, highscore entries should be saved.

**Comment by Stefan1200-de** [comment]
@daggeg Does CTRL + Right Arrow help you with this issue, and if yes, can I close this issue?

**Comment by daggeg** [comment]
Yes, CTRL+right arrow works. Thanks.
