### ISSUE TITLE
New nuget hosting concept

### ISSUE THREAD

**Issue by lukeIam** [Vocaluxe/Vocaluxe#462]
A long time ago I cleaned up Vocaluxe's dependencies and packed them into nuget packages - everybody should be able to build Vocaluxe after checkout without worrying about libraries and versions.
I've put the packages source on github (https://github.com/lukeIam/VocaluxeDependencies) and let the packages themselves been hosted on [myget](https://www.myget.org).

As at that point of time nuget has no signatures and no pinning, we decided to remove all other sources than myget.org (Otherwise someone else could register that name on e.g. nuget.org and this package might be pulled).
As result of this decision we had to mirror all the dependencies of our dependencies on myget.org .
Meanwhile we exceeded our free storage by a lot (maybe they decreased it a bit ;) )
But at the moment we can not publish new nuget packages.

Options:
- Remove old packages from myget (older versions of Vocaluxe can not longer be build)
- change the strategy and only host own packages ( dependencies of our dependencies will be pulled from nuget.org).

Optional:
- change the hoster:
  - nuget.org is the main repo -> would fix the problem with somebody steals our package names
  - github.org recently started with an own free repo hosting offer
- Signatures and pinning (I'm not up to date but I know that it was added to nuget in the meanwhile)

Comments?

**Comment by Stefan1200-de** [comment]
Well, I'm completely new in this world. I'm a closed source Java and PHP developer and I never had to think about dependencies (except for the Java and PHP interpreter, of course) ;)

But if there are no drawbacks for Vocaluxe, it might be a good idea to have everything on GitHub, if they offer something similar? Or is it much work to change this?

But in my opinion you are much deeper into this topic. Which solution do you prefer, if we want to keep older branches still usable?

**Comment by Stefan1200-de** [comment]
@lukeIam Do you have an idea, how we can continue with this?

**Comment by lukeIam** [comment]
> @lukeIam Do you have an idea, how we can continue with this?

sorry just had a short look yet:
signing is not a real option as it requires really expensive Code Signing Certificates.
At least nuget.org blocks self signed certificates (couldn't find an info for github).
So in the end we have to use unsigned packages and if we want to solve the name stealing problem we have to use nuget.org.

But I will have a deeper look on this and provide more details about the transition...

**Comment by Stefan1200-de** [comment]
@lukeIam maybe ProGet is an usable alternative? In fact I don't know what we exactly need, but it sounds similar to NuGet. It has an free account, but I found no information about the self signed certificates stuff.

Website: https://inedo.com/proget
Limitations of the free account: https://docs.inedo.com/docs/proget/administration/license

**Comment by Stefan1200-de** [comment]
Btw. how big are the files? Will they be downloaded using https or something like that, which I can provide on my own server? Can be the source different, so all files, which are already on myget can stay there and we just put the new files on my space?

**Comment by lukeIam** [comment]
not that big at least the nuget packages - some zipfiles with the theme videos are bigger.

But anyway I prepared everything to move to nuget.org - but I currently have login problems there (wrote the support).
If you would like to go ahead you can register there and create an Vocaluxe org + create an access token and place it with a meaningful name here: https://github.com/Vocaluxe/VocaluxeDependencies/settings/secrets

**Comment by Stefan1200-de** [comment]
@lukeIam I don't have access to https://github.com/Vocaluxe/VocaluxeDependencies/settings/secrets, but I have to admit that this nuget packages concept is new to me, maybe it is better if you do it. If course, if you have troubles to get your account running, I can create an account on nuget.org and send you the login details by mail?

**Comment by lukeIam** [comment]
> I don't have access to https://github.com/Vocaluxe/VocaluxeDependencies/settings/secrets,

now you should have 



> but I have to admit that this nuget packages concept is new to me, maybe it is better if you do it. Of course, if you have troubles to get your account running, I can create an account on nuget.org and send you the login details by mail?

Nuget Org Account:
https://docs.microsoft.com/de-de/nuget/nuget-org/organizations-on-nuget-org#adding-a-new-organization
Api key creation:
https://docs.microsoft.com/de-de/nuget/nuget-org/publish-a-package#create-api-keys

If it's not working it is also not a problem - I think I have to wait till Monday with my own account.

**Comment by Stefan1200-de** [comment]
Creating a new Microsoft account (to have it separated from my Windows account), waiting for that confirmation mail. :)

**Comment by Stefan1200-de** [comment]
Funny, that confirmation mail don't find a way to me...

**Comment by Stefan1200-de** [comment]
@lukeIam I created that organisation now, which name I should invite?

**Comment by lukeIam** [comment]
> @lukeIam I created that organisation now, which name I should invite?

lukeIam 

But I cant login as I cant reset my password (same problem not getting the mail from nuget)

**Comment by Stefan1200-de** [comment]
> But I cant login as I cant reset my password (same problem not getting the mail from nuget)

Also google mail?

**Comment by lukeIam** [comment]
> > But I cant login as I cant reset my password (same problem not getting the mail from nuget)
> 
> Also google mail?

yes

**Comment by Stefan1200-de** [comment]
It seems Microsoft don't like Google :D ;)

**Comment by Stefan1200-de** [comment]
@lukeIam I got my confirmation mail just this minute and I invited you to the organisation.

**Comment by lukeIam** [comment]
> @lukeIam I got my confirmation mail just this minute and I invited you to the organisation.

got them tonight - but all already expired ^^ but I requested a new one and is was there in seconds...

**Comment by Stefan1200-de** [comment]
> got them tonight - but all already expired ^^ but I requested a new one and is was there in seconds...

Yeah, mail server problems. One of my daily businesses at work :D :)

**Comment by lukeIam** [comment]
The Vocaluxe dependency repo is moved to https://github.com/Vocaluxe/VocaluxeDependencies and uses nuget.org now.
#461  will update the Vocaluxe main project to use it.

**Comment by Stefan1200-de** [comment]
@lukeIam this issue can be closed?

**Comment by lukeIam** [comment]
Yes - thought that the pr closed it...

**Comment by Stefan1200-de** [comment]
> Yes - thought that the pr closed it...

No, it didn't. But since I'm the clean up crew, I close this issue. ;)

**Comment by lukeIam** [comment]
Thanks! (Only email access atm - can’t close it myself)
