### ISSUE TITLE
Playlist song selection

### ISSUE THREAD

**Issue by Angel203** [Vocaluxe/Vocaluxe#487]
If I select a song from a playlist and I have to scroll down a bit it plays/selects the wrong song.
Then it plays the song which would be in this place without scrolling down.
This behavior is the same with the keyboard or mouse selection.

I'm on the latest develop-release.

**Comment by Stefan1200-de** [comment]
I can confirm that.

Way to reproduce:
Create or open a playlist with more than 9 entries, so you have to / can scroll that playlist.
If you scroll down that playlist, do a double click on a song, it will start to sing a song, which is in the same row without scrolling.

**Comment by Stefan1200-de** [comment]
Found bug, fixed in the next nightly (later or tomorrow).
