### ISSUE TITLE
Game crashes when set songlength to short version in Party (Challenge and TicTacToe)

### ISSUE THREAD

**Issue by Charger93** [Vocaluxe/Vocaluxe#492]
This is the error while the game crashes.
I'm using the version from 8th Feb 2020.

[00:01:49.3132980] [Fatal] Unhandled error: "Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index"
{ThreadId: 1, CallingContext: "{ callerMethodeName = Main, callerFilePath = C:\projects\vocaluxe\Vocaluxe\Program.cs, callerLineNumer = 76 }"}
System.ArgumentOutOfRangeException: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index
   bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei VocaluxeLib.Menu.CMenuPartySongSelection._GetSelectedOptions() in C:\projects\vocaluxe\VocaluxeLib\Menu\CMenuPartySongSelection.cs:Zeile 224.
   bei VocaluxeLib.Menu.CMenuPartySongSelection.HandleMouse(SMouseEvent mouseEvent) in C:\projects\vocaluxe\VocaluxeLib\Menu\CMenuPartySongSelection.cs:Zeile 155.
   bei Vocaluxe.Base.CGraphics._HandleInputs(CKeys keys, CMouse mouse) in C:\projects\vocaluxe\Vocaluxe\Base\CGraphics.cs:Zeile 550.
   bei Vocaluxe.Base.CGraphics.UpdateGameLogic(CKeys keys, CMouse mouse) in C:\projects\vocaluxe\Vocaluxe\Base\CGraphics.cs:Zeile 197.
   bei Vocaluxe.Lib.Draw.CDrawBase`1.MainLoop() in C:\projects\vocaluxe\Vocaluxe\Lib\Draw\CDrawBase.cs:Zeile 405.
   bei Vocaluxe.Lib.Draw.CDrawBaseWindows`1.MainLoop() in C:\projects\vocaluxe\Vocaluxe\Lib\Draw\CDrawBaseWindows.cs:Zeile 218.
   bei Vocaluxe.CMainProgram._Run(String[] args) in C:\projects\vocaluxe\Vocaluxe\Program.cs:Zeile 300.
   bei Vocaluxe.CMainProgram.Main(String[] args) in C:\projects\vocaluxe\Vocaluxe\Program.cs:Zeile 72.

**Comment by Stefan1200-de** [comment]
Fixed with the next nightly version (later today or tomorrow).
