### ISSUE TITLE
Covers being cropped

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#499]
I just noticed that many of the covers in the game is being cropped. Perhaps it's got to do with the adjustments the other week? 
![Skärmklipp 2020-02-17 19 56 12](https://user-images.githubusercontent.com/6724256/74680791-fb9b0500-51c1-11ea-9948-3bd337bf6ec0.png)

**Comment by Stefan1200-de** [comment]
I can confirm that, the nightly from 2018 don't cropped the most cover images in tiles view, but the current nightly do. But funny fact: The tiles view do crop the most images (CSongMenuTileBoard.cs -> Draw()) and I don't changed something here.

I will check that.

**Comment by daggeg** [comment]
Did this bug appear after Jiiniasu changed how much the covers are enlarged when doing mouseovers?

**Comment by Stefan1200-de** [comment]
> Did this bug appear after Jiiniasu changed how much the covers are enlarged when doing mouseovers?

No. My Pillarbox aspect ratio is the reason. Working on it.

**Comment by daggeg** [comment]
Ok. Cool.

**Comment by Stefan1200-de** [comment]
File CoverDB.sqlite should be deleted after using a nightly with the new fix, so cover images will be recreated!

**Comment by daggeg** [comment]
Yup.
