### ISSUE TITLE
CTRL+Right

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#504]
Would it be possible to change the CTRL+Right to skip 15 or 20 seconds instead of 30 seconds? It would make the function possible to use more often.

**Comment by Stefan1200-de** [comment]
Maybe I add a different meta key for a 10 second skip.
Shift+Right for 10 seconds
CTRL+Right for 30 seconds

What do you think about it?

**Comment by daggeg** [comment]
That would do the trick.
