### ISSUE TITLE
After Highscore back to the first song in the menu

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#506]
When using the highscore option at the song menu like this:
<img width="960" alt="Skärmklipp 2020-03-07 10 28 26" src="https://user-images.githubusercontent.com/6724256/76140831-8bfc9500-605e-11ea-83f5-82535ffa41d5.png">
You end up on the first song in the menu instead of the song you were at.

**Comment by Stefan1200-de** [comment]
Which key did you use to leave the highscore screen?

**Comment by daggeg** [comment]
It's not how I leave the highscore menu, it's seems to be related to how I enter it. Everytime I enter by going through the Song Options menu clicking on select (as shown below) and then on highscore this seems to happen. It doesn't seem to happen if I click on the song's cover followed by pressing highscore.
<img width="960" alt="Skärmklipp 2020-03-08 16 08 28" src="https://user-images.githubusercontent.com/6724256/76165538-1674ef80-6158-11ea-9f5c-2564e7b317a3.png">

**Comment by Stefan1200-de** [comment]
I can't reproduce it, no matter if I'm in list or tiles view. Also no matter if I enter the highscore using the Song Options button or the CTRL+H shortcut. And it does not matter if I leave the highscore with the left or right mouse button or the ESC key.

So what is different on your end?

**Comment by daggeg** [comment]
I tried this now and it seems like this problem occurs after having pressed ctrl+T.

**Comment by daggeg** [comment]
It's not only after having pressed ctrl+t. It happened just now after having clicked the left mouse button when looking at the highscores.

**Comment by Stefan1200-de** [comment]
Yeah, from time to time (not always) I had it too. Workaround: Use the right mouse button or ESC key.

**Comment by daggeg** [comment]
Now I've found out when it goes back to the first song and when it doesn't.
![InkedSkärmklipp 2020-04-10 10 16 56_LI](https://user-images.githubusercontent.com/6724256/78975713-f8166100-7b14-11ea-96d2-1573885f2947.jpg)
If I click on the song's cover and press on highscore, like in the picture above, it doesn't matter how I leave the highscore screen. Pressing left or right mouse doesn't matter, I still end up where I started. 

But if I enter the highscore screen by pressing select in the top left corner, as in the picture below, I will end up at the first song no matter how I leave the highscore screen.
![InkedSkärmklipp 2020-04-10 10 17 20_LI](https://user-images.githubusercontent.com/6724256/78975983-9276a480-7b15-11ea-8cbb-79040792fd07.jpg)

**Comment by Stefan1200-de** [comment]
> Now I've found out when it goes back to the first song and when it doesn't.
> But if I enter the highscore screen by pressing select in the top left corner, as in the picture below, I will end up at the first song no matter how I leave the highscore screen.

I tested around a bit. On my end this only happens, if you click on a song (one time) without opening the "Song Options", but the song preview starts, now hover with the mouse over another song without clicking on it, the preview is still playing the clicked song. Now enter the Highscore by pressing the CTRL + H keys. The Highscore of the clicked song will be displayed (as expected), but now it does not matter how you leave the Highscore screen, it will start playing the preview of the last song hovered by the mouse. Of course the same also happens using the keys.

**Comment by Stefan1200-de** [comment]
Looked into the code and understand the most parts which results into this behavior.

I don't know if it's useful to change this behavior. Because Vocaluxe use that to decide to jump to the last hovered song in that list after reentering the song list. If I change that to the last previewed song, it could change the expected behavior for some people. Currently I don't know, how big the impact would be.
