### ISSUE TITLE
Dependency problem libgstreamer-1.0-0.dll

### ISSUE THREAD

**Issue by Mat-D** [Vocaluxe/Vocaluxe#509]
Hi,

i build vocaluxe in VS2017. Unfortunately when starting in x64/Debug mode, i get an error message saying that **libgstreamer-1.0-0.dll** is missing. Any suggestions?

Thanks!

Regards

**Comment by stefanengelmayer** [comment]
Hi, 

I also had problems to compile it with Visual Studio 2017.
Try using Versions which are listed in the HowTo: https://github.com/Vocaluxe/Vocaluxe/wiki/HowTo:-Build-Vocaluxe-(Windows)
With 2015 I can compile and run it without any problems.

I think some required features are missing in the newer VS versions ;)

Have a nice day.

**Comment by lukeIam** [comment]
Should also be working with newer Visual Studio Versions.
I was working with Visual Studio 2017 till last week without any problem.

All dependencies should be resolved using nuget.
GStreamer is one of the two special things (the lib is to huge) so there is a nuget package that will download the files directly from our github repo.
Could be that the handover of the VocaluxeDependency repo to the Vocaluxe repo broke something. I'll do some tests - can you please check the output of the package manager console?

**Comment by lukeIam** [comment]
> can you please check the output of the package manager console?

ok it should be in the normal build log.
It is still loading from the old (my) repo but as it's still available it should work.
Actually it is working for me without a problem.

Delete the folder:
`Vocaluxe\Output\libs\unmanaged\gstreamer64`
(or the complete content of `libs` - everything in there should be recreated automatically by nuget)

The log should look like:
```
[...]
2>  gstreamer is missing - download started:
2>  https://github.com/lukeIam/VocaluxeDependencies/blob/master/zips/dependencies/gstreamer_x64.zip?raw=true
[...]
```


If that is not working, open a powershell in the Vocaluxe folder and run:
`nuget restore`
(https://docs.microsoft.com/de-de/nuget/reference/cli-reference/cli-ref-restore)

**Comment by lukeIam** [comment]
I opened #511 for updating the urls to the new repo.
But as posted before it should not be the cause of your problem.

**Comment by stefanengelmayer** [comment]
At least for me this solution works.

**Comment by lukeIam** [comment]
> At least for me this solution works.

Cool - looks like an earlier download was corrupted -> and as the folder exits no new download it triggered.

**Comment by Mat-D** [comment]
Thanks for the replies! I also got it working now, but it looks like i've missed simply selecting the right debug configuration. Default "Debug Linux" is selected - which due to my VS2017 layout reads "Debug Li" and didn't get my attention until looking at it with fresh eyes in the morning;-).

After Rebuilding the solution in "Debug Win" it worked. Deleting the lib folder wasn't probably necessary for me.

**Comment by Mat-D** [comment]
Thanks!
