### ISSUE TITLE
Create Playlist with custom Path

### ISSUE THREAD

**Issue by stefanengelmayer** [Vocaluxe/Vocaluxe#512]
Hello again, 

I use a custom Playlist path by adding a parameter to the shortcut.
It works fine and the playlists can be used ingame.

Problem:
But if I want to create a new playlist and save it, I always get this error message: 
'Unhandled error: "Ein Teil des Pfades "F:\Vocaluxe\FullPlaylists \NewPlaylist.xml" konnte nicht gefunden werden."'
Somehow Vocaluxe adds a space after the dir. 

(My shortcut is like "F:\Vocaluxe\Vocaluxe.exe -ConfigFile Config.xml -PlaylistFolder FullPlaylists")

Can someone confirm this bug or am I doing something wrong?

**Comment by lukeIam** [comment]
> Can someone confirm this bug or am I doing something wrong?

Confirmed - seems to be a fast fix...
