### ISSUE TITLE
Sorting "Artist by letter"

### ISSUE THREAD

**Issue by Edi316** [Vocaluxe/Vocaluxe#514]
I have found an issue when sorting the songs by "Artist by letter"

I have artists starting with the letters A and Ä. This causes the issue that the category for the letter A is split:

The first A-category lists the artists: Aa-Ar
The second A-category list the artists: As-Az
The Ä-category only has one artist starting with Är

This is just a "cosmetic issue" (the game works perfect), but maybe there is a solution for that.

![Artist by Letter](https://user-images.githubusercontent.com/61267443/76853343-5e2d0280-684d-11ea-8bcc-912d6a13e745.jpg)

**Comment by Stefan1200-de** [comment]
Reproduce-able with the current nightly.

![image](https://user-images.githubusercontent.com/15168351/77235649-0fb69580-6bb8-11ea-90c7-615a8f562b92.png)
