### ISSUE TITLE
Can't Find highscores

### ISSUE THREAD

**Issue by Benasty** [Vocaluxe/Vocaluxe#515]
Hi, i'm a simple user from France. you've done a wonderful job on vocaluxe, keep going.

i have an issue i cant find / put on screen any score , highscore for any songs. 
i'm using windows 10 and vocaluxe 0.40 stable. i've seen some of your screenshots and whenever you select a song there's lines you can click ( sing, normal, new playlist, add to playlit) and at home on my computer, i dont have highscore !
can someone help me ? ( i dont know anything about programming, that's why i'm on windows ) 
and sorry for my bad english
see you soon
Benoit

**Comment by Stefan1200-de** [comment]
Maybe you only sing with the quests profiles? You have to create player profiles and sing with them to keep the highscores saved.

**Comment by Benasty** [comment]
i asked my girlfriend to test it immediatly. ( and yes we juste renamed the existing profiles )

**Comment by Benasty** [comment]
yes ! i was only that... thank you  !!!!

**Comment by Stefan1200-de** [comment]
Great, so I close this issue.
