### ISSUE TITLE
Video Ratios

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#516]
I know that you @Stefan1200-de have said that I should add #VIDEOASPECT:3 in the song file if the video ratio turns out to be fishy for a particular song. This due to the video ratio scaling code you implemented a wile ago. But I've found it not too uncommon that #VIDEOASPECT:3 doesn't fix it, but  #VIDEOASPECT:4 does. This seems to be related to older videos, I think this so far has only happened for video from the 80:s. Is there anyway to fix this so you don't have to fix this manually song by song?

**Comment by Stefan1200-de** [comment]
It is not a bug. It is just moved from 3 to 4, because I implemented a new value for a video aspect.

As long as the acinerella library, which Vocaluxe is using for video files, can't read the DAR value of a video file, I can't change this behavior without breaking it for other videos.

**Comment by marwin89** [comment]
I close this issue due inactivity. Please re-open if needed. The [official ultrastar songformat v1.0.0 or v1.1.0](https://usdx.eu/format/) doesn't support #VIDEOASPECTRATIO and won't support this in future.
