### ISSUE TITLE
Additional Theme for Vocaluxe

### ISSUE THREAD

**Issue by marwin89** [Vocaluxe/Vocaluxe#518]
Hey Vocaluxe-Peeps!

I've developed an additional theme for Vocaluxe and I love to share it with you.

Is it possible to include it in the standard-vocaluxe-download? Or maybe we can add it to the official site as a seperate download? Or maybe you can use some elements for further developement. What do you think? It's okay if not, just close this ticket.

Some Infos about the theme:
- Static backgrounds are created for 1080px Full HD.
- Default-bg-video and loading-video won't be used
- I've edited all screens just a little and all textures, no feature is affected
- There's also a new cover style
- GIMP-Ressources are available and can be used by the community for further adjustments

Thank you so much for the hard work
It's a great project!

[Download](https://www.sendspace.com/filegroup/MR3MKlC%2Boym3JtCmTNSKrA)
(Theme 19MB / Ressources 16 MB)

**Comment by Stefan1200-de** [comment]
It looks nice, I like it. Currently I can't say, if it is useful to add it to the standard Vocaluxe download. But I will look at it.

By the way: Currently Vocaluxe renders everything in the resolution 1280x720, no matter which screen resolution you have (it will be scaled up or down from 1280x720 to the target resolution), so there is no advantage to include anything beyond this resolution.

**Comment by Stefan1200-de** [comment]
Another question: Do you created that theme for the nightly or for the 0.4.1 version? The nightly use an updated theme version and is not compatible with Vocaluxe version 0.4.1. We don't add any new features to the old 0.4 versions. Are you able to update your theme for the Vocaluxe Nightly?

**Comment by marwin89** [comment]
alrighty! Good to know! Don't worry if not. I've created it for the 0.4.1 version, so it needs an update for the nightly. Maybe I've got some time within the next two month.
Oh and by the way: Is there an svg-version of the vocaluxe logo?

**Comment by Stefan1200-de** [comment]
> Oh and by the way: Is there an svg-version of the vocaluxe logo?

@lukeIam do you know that about the Vocaluxe logo?

**Comment by lukeIam** [comment]
> > Oh and by the way: Is there an svg-version of the vocaluxe logo?
> 
> @lukeIam do you know that about the Vocaluxe logo?

no - there is no svg version of the logo.
But the Photoshop files (under `Vocaluxe\Ressources`) contain text paths -> so I can render you a png with a resolution of your choice.
Theoretically I cloud also export it as svg but that seems too kill the filling of the letters.

**Comment by Stefan1200-de** [comment]
@marwin89 where did you found the player icons?

**Comment by marwin89** [comment]
@lukeIam : Thanks for checking! 1281x392 would be nice. I could work with that.
@Stefan1200-de : do you mean the player avatars? there not included in the theme. They're just examples for your inspiration, just private use. It's from a boardgame called "Party In My Dorm". It's not creative commons. You can search "subculture avatar vector" in duckduckgo or other search engines to find some buyable fancy avatars. didn't find a cool profile picture collection for free yet. Let you know if I find some.

**Comment by Stefan1200-de** [comment]
Thanks marwin. I googled around today and find other avatars, which are free. But unfortunately not creative commons, just free. But I had to do some work on it, to have it as single transparent png image, here my result:
![image](https://user-images.githubusercontent.com/15168351/79644351-aae75e80-81a8-11ea-955a-e0aedae538a4.png)

From: https://vectorcharacters.net/free-vector-2/10-free-flat-character-designs

**Comment by Stefan1200-de** [comment]
This is usable too: https://face.co
It can export images in 400x400 transparent PNGs, perfect for Vocaluxe.

**Comment by daggeg** [comment]
I think your theme looks really nice @marwin89. One question though, is it possible to have the pics for the folders (as shown in pic 3) a bit transparent? I really like that the pics for folders in Genius are transparent, it makes the game look more alive when the first song in the folder is shown to a degree.

**Comment by lukeIam** [comment]
> @lukeIam : Thanks for checking! 1281x392 would be nice. I could work with that.

![Logo](https://user-images.githubusercontent.com/5115160/79687994-50530e80-824b-11ea-8785-b385aff1dafc.png)

**Comment by marwin89** [comment]
Update
---
@daggeg : that's a good point! i've made the cover more transparent. the game really looks more alive now.
@lukeIam : thank you :) but the PNG has no transparency. could you send it without the white BG?
@Stefan1200-de : thank you so much for your work. I like the cartoon style. I found some free avatars as well.

@ all! Good News. I've **rebuild the whole theme for the new nightly build**. The Genius Theme is amazing and there are alot of cool features and the loading/sing screen is fancy. Can't wait for the release! 

Please download and check my updated theme for the nightly build. Let me know if you find some bugs. Comment here if there are major changes in the nightly build.

[Download: Theme "Energy" (Nightly Build) / 20 MB](https://www.sendspace.com/file/eepwhf)

The Download includes: 
- Change Log
- Theme
- Cover
- BackgroundMusic (free licence) [Orangefreesounds](http://www.orangefreesounds.com/category/music/background-music/)
- Profiles (free licence) - [Freepik](https://www.freepik.com/free-vector/subculture-people-portraits-set_4376522.htm)
- GIMP Ressources

**Comment by lukeIam** [comment]
> @lukeIam : thank you :) but the PNG has no transparency. could you send it without the white BG?

sorry, my fault (forgot to remove the white bg before export)

![Logo](https://user-images.githubusercontent.com/5115160/80275730-7c570f80-86e3-11ea-9fb1-46c397cabcf4.png)

**Comment by steump** [comment]
@marwin89 looks fine - can you please upload the theme again for the 0.4.1 version?

**Comment by marwin89** [comment]
@steump [Download: Theme "Energy" (Nightly Build) / 20 MB](https://www.sendspace.com/file/eepwhf)
