### ISSUE TITLE
v0.4.1 does not start on Windows 7 x64

### ISSUE THREAD

**Issue by bigboss97** [Vocaluxe/Vocaluxe#519]
I'm new to Vocaluxe. Yesterday I tried v0.4.1 on my Windows 7 64bit and it froze on the splash screen.
x86 and x64 both crashed. Is there any log I can look at?

**Comment by Stefan1200-de** [comment]
There should be an Error.log in the Vocaluxe directory.
Do you see an error message while Vocaluxe is crashing?
Can you check if the current nightly is running?

**Comment by bigboss97** [comment]
I got the nightly build and it works perfectly, thanks.
