### ISSUE TITLE
Unable to display German lyrics

### ISSUE THREAD

**Issue by bigboss97** [Vocaluxe/Vocaluxe#522]
I'm running a nightly build with the product version of 0.4.0-560 on English Windows 7.
Some of the German characters cannot be displayed. Is there a setting which can fix?
![Screenshot - 20-04-27 12 16 51](https://user-images.githubusercontent.com/34834507/80328644-418bdd80-8883-11ea-92bf-cc578faaf1d8.png)

**Comment by Stefan1200-de** [comment]
Make sure, that you use ANSI / ISO 8859-1 for the text file encoding, not UTF-8!

**Comment by bigboss97** [comment]
I have tried many of them and they all have the same problem. I didn't created the songs. I really don't want to change them because I assume they work for other users.

**Comment by Stefan1200-de** [comment]
Use the "Convert to ANSI" option in Notepad++:
![image](https://user-images.githubusercontent.com/15168351/80343812-d7fdd600-8866-11ea-8798-d37f4a110a3d.png)

**Comment by bigboss97** [comment]
Looks like the existing text file is already in ASCII. There's no changes after I saved it in ASCII.
![Screenshot - 20-04-28 13 40 25](https://user-images.githubusercontent.com/34834507/80444989-85034c00-8956-11ea-934b-af91d0a1eb48.png)

Probably, it won't be an issue on German Windows. I also tried to save it in UTF-8. The characters changed, but still not correct.

**Comment by Stefan1200-de** [comment]
Please upload the TXT file.

**Comment by bigboss97** [comment]
I basically have lyric problem on all German songs. I'm using English Windows 7.
[Bino - Mama Leone.txt](https://github.com/Vocaluxe/Vocaluxe/files/4543661/Bino.-.Mama.Leone.txt)
[Dschinghis Khan - Dschinghis Khan.txt](https://github.com/Vocaluxe/Vocaluxe/files/4543663/Dschinghis.Khan.-.Dschinghis.Khan.txt)

**Comment by Stefan1200-de** [comment]
I only tested the Dschinghis.Khan.-.Dschinghis.Khan.txt file, here is it working with Vocaluxe Nightly. But I use the German Windows 10, don't know if that makes the difference.

**Comment by bigboss97** [comment]
Yes, it does.
I've used Chinese and German Windows before UTF-8 era. Basically you couldn't get Chinese and German displayed at the same time. German letters were displayed as Chinese on Chinese Windows and vise versa. Chinese mainly used Big5 and GB encoding which can only be displayed on Chinese Windows.
Interestingly, "modern" Chinese Windows can handle Unicode and legacy encoding.
I guess this is also happening on German Windows.

I'll do more testing and get back to you.

**Comment by bigboss97** [comment]
I found the problem on my PC. For some reason my fallback language was set to Chinese. I changed it to English. Now German songs work perfectly. Thank you for your time  :-)
![Screenshot - 20-04-29 14 22 44](https://user-images.githubusercontent.com/34834507/80561116-c4996900-8a26-11ea-951e-7fb50808e061.png)

**Comment by Stefan1200-de** [comment]
Yeah, that is the drawback from ANSI, it can only have one character set beside of the English letters. Only 4 byte UTF-8 or UTF-16 can handle everything at the same time.

**Comment by Jiiniasu** [comment]
I've personally solved the issue with encoding by coding all my .txts in UTF-8 with BOM so that vocaluxe always will autodetect UTF-8 correctly. However one could also use the #ENCODING-tag in the file itself.

**Comment by bigboss97** [comment]
Yes, I did try UTF-8 with BOM and it worked. Of course I had to do it on another PC  :-)
