### ISSUE TITLE
Checkout failed

### ISSUE THREAD

**Issue by bigboss97** [Vocaluxe/Vocaluxe#524]
I'm using VS 2019 and tried to follow the instruction. I got following error:

Cloning into 'E:\work\CPP\Vocaluxe'...
POST git-upload-pack (175 bytes)
Remote: Enumerating objects: 345, done.        
Remote: Total 345 (delta 0), reused 0 (delta 0), pack-reused 345        
Error: invalid path 'HowTo:-Add-a-new-feature-to-the-Vocaluxe-server.md'
Error encountered while cloning the remote repository: Git failed with a fatal error.
unable to checkout working tree
Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Nothing has been checked out except a .git directory. What have I done wrong?

**Comment by lukeIam** [comment]
Hi @bigboss97 ,

looks like you tried to clone the wiki - which is most likely not you want.
try cloning:
https://github.com/Vocaluxe/Vocaluxe.git

e.g.
`git clone https://github.com/Vocaluxe/Vocaluxe.git`

**Comment by bigboss97** [comment]
Will try that, thanks.
I simply followed the screenshots and copied the URL  :-)

**Comment by bigboss97** [comment]
Success!
I was reading the instruction. Of course my URL was for the wiki page, how silly :-)
Thanks!
