### ISSUE TITLE
Platform Toolset not found while building

### ISSUE THREAD

**Issue by bigboss97** [Vocaluxe/Vocaluxe#525]
I'm running VS2019 on Windows 10. What should I do in this case?
![Screenshot - 20-05-01 15 01 04](https://user-images.githubusercontent.com/34834507/80783543-78ccf800-8bbd-11ea-8166-45bbd7f48ad0.png)
or is it still possible to find VS2010?

**Comment by Stefan1200-de** [comment]
I just did "upgrade to v142" and it was working.

**Comment by bigboss97** [comment]
Thanks, it works now. But somehow only the pitch tracker was built. Even though I right clicked on the solution node.
![Screenshot - 20-05-01 17 54 17](https://user-images.githubusercontent.com/34834507/80791494-226bb380-8bd5-11ea-98b8-d03c55f39ec9.png)

**Comment by Stefan1200-de** [comment]
Make sure that you selected the Windows version. And try to build again. Sometimes I also need 2-3 tries until it works without problems.

And check this:
![image](https://user-images.githubusercontent.com/15168351/80791650-9afd5080-8b92-11ea-871b-30790c8573ad.png)

**Comment by bigboss97** [comment]
You can see from my previous screenshot that all other projects were not loaded because I cancelled on this popup:
![Screenshot - 20-05-01 18 23 08](https://user-images.githubusercontent.com/34834507/80792876-f18d7d80-8bd8-11ea-8625-acd0d75aba4a.png)
Then I tried once again with OK on all target. But then I got a lot of reference errors.

**Comment by Stefan1200-de** [comment]
Just download that target .NETFramework and do not change that project.

**Comment by lukeIam** [comment]
> I just did "upgrade to v142" and it was working.

thats the way to do it at the moment (there is a version switch but its not supporting the VS2019 atm).
In earlier days the selection was more important due to windows xp support but as this is now dropped the selection is only important for release versions (has influence on the dependencies of Vocaluxe).


> And try to build again. Sometimes I also need 2-3 tries until it works without problems.

After a first build VS may show a lot of errors but the build should succeed - just reopen the project and build again to fix ui. (the first build a lot of dependencies where downloaded)

> Make sure that you selected the Windows version.

Jep, selection of Linux under Windows might create some funny output...

> And check this:
> ![image](https://user-images.githubusercontent.com/15168351/80791650-9afd5080-8b92-11ea-871b-30790c8573ad.png)

Unsafe code should not be required and should not be enabled. @Stefan1200-de any special reason to tick that? then we should have a look...


> You can see from my previous screenshot that all other projects were not loaded because I cancelled on this popup:

Just install 4.6.1:
![image](https://user-images.githubusercontent.com/5115160/80794919-6772f400-8b9b-11ea-912f-c8ddd11cd07f.png)

**Comment by Stefan1200-de** [comment]
@lukeIam Well, I got a message from VS, that compiling is not possible without checking that. But I will look deeper into that as soon as I start coding again.

**Comment by lukeIam** [comment]
> thats the way to do it at the moment (there is a version switch but its not supporting the VS2019 atm).

version switch for VS2019: pr #526

**Comment by bigboss97** [comment]
Compile went through with the message, see also attachment.
========== Rebuild All: 7 succeeded, 0 failed, 0 skipped ==========
[output.txt](https://github.com/Vocaluxe/Vocaluxe/files/4564253/output.txt)
Vocaluxe crashes on start
![Screenshot - 20-05-01 23 04 41](https://user-images.githubusercontent.com/34834507/80807503-b737d680-8c00-11ea-836d-4ef623dced58.png)

**Comment by lukeIam** [comment]
> Compile went through with the message, see also attachment.
> ========== Rebuild All: 7 succeeded, 0 failed, 0 skipped ==========
> [output.txt](https://github.com/Vocaluxe/Vocaluxe/files/4564253/output.txt)
> Vocaluxe crashes on start
> ![Screenshot - 20-05-01 23 04 41](https://user-images.githubusercontent.com/34834507/80807503-b737d680-8c00-11ea-836d-4ef623dced58.png)

that's "normal" - out of the box Vocaluxe requires VC++ 2010 runtime to be installed.
Install it and it should run fine...

**Comment by bigboss97** [comment]
Hooray! It's started.
Thank you so much for your time.
