### ISSUE TITLE
Soundgraph iMon remote unable to send key combination to Vocaluxe

### ISSUE THREAD

**Issue by bigboss97** [Vocaluxe/Vocaluxe#527]
I'm trying to program my iMon remote for Vocaluxe.
http://folksfun.blogspot.com/2006/05/how-to-install-imon-vfd-in-tsunami-pc_20.html
There's no problems in sending single keys. But when I tried key combination, like [ctrl]+[1]. It didn't work. It works with keyboard. I tried my remote with key combination on VLC. It's also fine.

So, Vocaluxe can receive key combination and iMon is sending key combination. What is wrong here?

**Comment by bigboss97** [comment]
I want to investigate the problem. I can build my own version. I want to write the key event to a log file to compare the keys. Where can I add few lines of codes to achieve that?

**Comment by lukeIam** [comment]
maybe https://github.com/Vocaluxe/Vocaluxe/blob/15d5b17fd2f8a0a2981ef2a24afcfb29ee0b26a7/Vocaluxe/Base/CUtility.cs#L143 could be a good starting point

**Comment by bigboss97** [comment]
Thanks, will have a look.
Are there any functions I can use to write values to log file?
I can't set break points because the box using IR control hasn't got VS installed.

**Comment by lukeIam** [comment]
> Are there any functions I can use to write values to log file?

e.g. CLog.Information()

Edit:
or https://docs.microsoft.com/de-de/visualstudio/debugger/remote-debugging-csharp?view=vs-2019

**Comment by bigboss97** [comment]
I have printed following information in PollEvent()
keyEvent.ModCtrl +":"+ keyEvent.Key+":"+ Char.ConvertToUtf32( keyEvent.Unicode.ToString(),0)
When I entered [Ctrl]+[2] and [Shift]+[3] I received:
>> True:ControlKey:0
>> True:D2:0
>> False:ShiftKey:0
>> False:D3:0
>> False:None:35

When used iMon I received:
>> True:ControlKey:0
>> False:ShiftKey:0
>> False:None:35

Basically, iMon sends the key combination as a single key.
Interestingly, this is my first program which has problem with iMon key combination.

**Comment by lukeIam** [comment]
Looks like your iMon virtual input device does not support DirectInput.
Found on the web: https://github.com/xbmc/xbmc/pull/1111#issuecomment-6695937

I guess on other games using DirectX will also not work...

**Comment by bigboss97** [comment]
I've been using Kodi with iMon remote for sometime. Everything seems to work. I also double checked my iMon settings. Kodi does use many combination keys and they work.

**Comment by marwin89** [comment]
closed due inactivity. please re-open if needed.
