### ISSUE TITLE
Private build crashes on Start Singing: "stream is null"

### ISSUE THREAD

**Issue by bigboss97** [Vocaluxe/Vocaluxe#528]
My Vocaluxe build starts up and looks normal. But it crashes when I click on Start.
I'm very new and don't have much ideas.

In the log file, it looks like something to do with video:
[00:00:12.9492561] [Error] Error opening video file: E:\work\CPP\Vocaluxe\Output\Songs\Chinese\Chopstick Brothers - 小苹果\Chopstick Brothers - 小苹果.mp4
I pasted the path in explorer and the video was running.
A full log is attached, any ideas?
[Vocaluxe.log](https://github.com/Vocaluxe/Vocaluxe/files/4590850/Vocaluxe.log)

**Comment by bigboss97** [comment]
Same thing happened on another box (Windows 7) with downloaded software.
I'm pretty sure I sang that song and the video was playing.

**Comment by Stefan1200-de** [comment]
> Error opening video file: E:\work\CPP\Vocaluxe\Output\Songs\Chinese\Chopstick Brothers - 小苹果\Chopstick Brothers - 小苹果.mp4

How big is this video file? Can you upload it for me?
Did you tried to rename that file and foldername, maybe just to test.mp4 (of course you have to change that filename in the txt file too) and the folder to Chopstick Brothers - Test. Does that change anything?

**Comment by bigboss97** [comment]
OK, confirmed. It's path problem.
After investigation, I found out it's video only, this works:
![Screenshot - 20-05-08 09 44 41](https://user-images.githubusercontent.com/34834507/81355106-b4f9de80-9110-11ea-8201-5622d270f4d5.png)

I know why it did work before. I got the song initially in ASCII. Then I replaced the lyrics with Chinese. While I was testing I didn't change the file names etc.

Here is the files for your testing:
https://drive.google.com/file/d/1S2iGf4kKjbyZUmWwoObNQ5yvg-NT4frk/view?usp=sharing

**Comment by Stefan1200-de** [comment]
Okay, if you already know, that the filename is the problem, I don't need the file for testing anymore. Vocaluxe use a third party library for reading the video file, maybe this library us unable to read Chinese letters. @lukeIam do you have an idea? Can be acinerella the problem?

**Comment by whipflash191** [comment]
I have this same issue but my filename is just video.mpg using latest nightly

**Comment by Stefan1200-de** [comment]
> I have this same issue but my filename is just video.mpg using latest nightly

Can you upload that file somehow?

**Comment by whipflash191** [comment]
sure here you go 
https://drive.google.com/file/d/1veHe4N26ZyIFaNlJ3QN721rF6OY_qcII/view?usp=sharing

The game crashes with pretty much any video file I throw at it but runs perfectly fine when I remove them

**Comment by Stefan1200-de** [comment]
@whipflash191 The current nightly use a new version of an external library (ffmpeg and acinerella, both are used to load and display video files), while older nightlys (February 2020 and earlier) and Vocaluxe 0.4.X use an older version. Maybe your system is somehow incompatible with that.

Unfortunately I can't download that video file from your Google drive anymore (no permissions), to check, if that file works on my pc. Please make sure that it can be downloaded from everyone with that link.

**Comment by marwin89** [comment]
closed due inactivity. please re-open if needed.
