### ISSUE TITLE
Jump back in song while singing

### ISSUE THREAD

**Issue by Lenbus** [Vocaluxe/Vocaluxe#529]
I am working on a solution for producing really high quality Learning Tracks especially for Choirs, Bands and other ensembles. I think therefore Vocaluxe is a neat and beautiful way to do such a thing, especially having that closed loop feedback loop and the intuitive noteflight view - as opposed to sheet music, which can be quite hard to read for many people. For those who prefer sheet music I've put a video of that playing in my note editing program in the background. So right now everything looks really really promising. There is only one feature missing, that could make or break the whole approach:
For Karaoke you do not need this, but for learning and training purposes it is very important, that you can navigate to a specific part of the song and redo it as often as you want (of course this might screw up the complete scoring system but never mind). 
On the bottom of the screen there is a global timeline, which could just be used for that quite easily (just click and jump to that location). Maybe this would need a special option or mode to activate such functionality, as you do not want or need that just playing karaoke (but then you just would not have to click there and it'll be okay). Also for orientation Markers or the ability to Loop certain Regions could come in really handy. 
So I am really begging you to implement at least the quick-jump-navigation feature and I will be a very happy person, being able to provide high quality note learning abilities to the homes of many people, who are currently being stuck at home and not able to perform with their groups.

If I can help you in anything, please let me know! Thank you so much in advance and all the best.
Lenbus

**Comment by Stefan1200-de** [comment]
Currently you can only jump forward using the current nightly (Shift / CTRL + Arrow Right). So currently you can only achieve this by restarting the song using the ESC menu and skip forward to the position you want.

I already tested it to implement jumping back using the same way, but there is much more work needed, because of the scoring stuff and weird display issues. That's why I only implemented the jump forward stuff.

**Comment by Lenbus** [comment]
Hey Stefan, 

thank you so much for that quick response. 

Restarting the song and being then able to quickly jump forward to the desired location is quite a good workaround as a starting point, even though of course it is a bit inconvenient. 

Currently I’m just getting started developing and enhancing my method to create the files needed. Do you think there might be the opportunity to have this requested navigation feature implemented soon? It’d be a blast and would help so much!

Let me know if I can help you anyhow.

Lenbus

**Comment by Stefan1200-de** [comment]
> Do you think there might be the opportunity to have this requested navigation feature implemented soon?

Not soon from my end, because currently I have a break from coding and I'm still not deep into the scoring code. But if no other person is coding this, I will look into it, if I have more time for coding. Can't say when.

**Comment by RumovZ** [comment]
Given that this is not an intended use case of Vocaluxe and the current stagnancy in the project, I wouldn't be too optimistic about the implementation...

However, why don't you just create seperate txt files for the respective parts? If you already have the txt for the whole song, you would only need to copy it and insert the #START and #END tags* restricting the playback to the segment you are interested in.
Wouldn't this have all the functionality you need?

*Note that #START takes seconds and #END milliseconds.

**Comment by marwin89** [comment]
As this use case is not intended for vocaluxe I close this Request.
Maybe the game melody mania or performous can do this.
