### ISSUE TITLE
System.OutOfMemoryException ~3500 Songs

### ISSUE THREAD

**Issue by D3rK4is3r** [Vocaluxe/Vocaluxe#530]
Hi,
had a System.OutOfMemory Exception. 

First i had a few covers in the log so i reduced their size to 200x200
But now the Log looks like this:
[Error.txt](https://github.com/Vocaluxe/Vocaluxe/files/4640035/Error.txt)

Important note: I got 3500 Songs in Vocaluxe. 

Steps to reproduce:
Precondition: ~3500 Songs
1. Start Vocaluxe
2. Press Sing
3. Dont do anything, You will see some stutters in the Preview of the Music video of the first song (Wait until it runs smooth again)
4. Choose another song --> System.OutOfMemory Exception

Edit: Happens on both Nightly & Stable Build.
Error on Stable Version:
![image](https://user-images.githubusercontent.com/65488898/82142499-0145cc80-983d-11ea-8a31-0f7cf2480fc7.png)

**Comment by Stefan1200-de** [comment]
How is the RAM usage of Vocaluxe after press on sing? How much RAM do you have? Please check both information using the Windows Task Manager.

**Comment by D3rK4is3r** [comment]
I got 16GB RAM.

I just tried it. I dont even need to press on Sing. While the games load the Songs RAM Usage is around 400-500 MB.
![while_loading](https://user-images.githubusercontent.com/65488898/93170847-47963400-f728-11ea-9198-d76fa6b1f941.PNG)

But in the Idle Screen it keeps rising until it hits around 1125 MB and crashs.
![In_Idle_Screen](https://user-images.githubusercontent.com/65488898/93171115-c25f4f00-f728-11ea-95a4-c22b9fe4cf7b.PNG)

**Comment by Stefan1200-de** [comment]
Using the nightly, are there errors in the Songlog file? Does Vocaluxe load all files, or crash it before loading all files?

**Comment by D3rK4is3r** [comment]
Yes, there are Errors in the Song.log
Arround 445
BG Images are missing, Line break Adjustments, Removed empty lines 

Yes all Songs are loaded completly. I Can even get in the songlist, switching songs, starting them. But as soon as hitting 1126 MB thats it.

**Comment by D3rK4is3r** [comment]
here the nightly build error message:
[E_OUTOFMEMORY.txt](https://github.com/Vocaluxe/Vocaluxe/files/5222992/E_OUTOFMEMORY.txt)
and
[JIT-Debugger.txt](https://github.com/Vocaluxe/Vocaluxe/files/5222994/JIT-Debugger.txt)
and
[Vocaluxe.log](https://github.com/Vocaluxe/Vocaluxe/files/5223131/Vocaluxe.log)

Could it be that the Covers are causing this? (Amount + different Sizes)

I removed all cover errors in the Vocaluxe.log.
Now every second time i start Vocaluxe it crashs without a report and have a additional error in the Vocaluxe.log. (GDI+)
[GDI.txt](https://github.com/Vocaluxe/Vocaluxe/files/5223306/GDI.txt)

Here is a Video:
https://www.youtube.com/watch?v=tX-8COikenE

**Comment by D3rK4is3r** [comment]
Ok, it seems like the "Cover loading" is causing this error.

I had "Dynamic" cover Loading on, it crashs after X Seconds in Game.
"On Demand" Game does not crash
"On Start-up" the game cant finish loading the songs.

**Comment by Stefan1200-de** [comment]
> Ok, it seems like the "Cover loading" is causing this error.
> 
> I had "Dynamic" cover Loading on, it crashs after X Seconds in Game.
> "On Demand" Game does not crash
> "On Start-up" the game cant finish loading the songs.

That make sense, because loading 3500 cover images into RAM at once could jump over some memory limits. Another thing could be a corrupted cover image file, which leads into a crash or memory leak.

**Comment by brunzel** [comment]
you have to use the x64 version instead of the x86 version

**Comment by marwin89** [comment]
After 3 years of inactivty i close this issue
