### ISSUE TITLE
Error while reading "ScreenMain".xml  Vocaluxe don´t start

### ISSUE THREAD

**Issue by Manticore2020** [Vocaluxe/Vocaluxe#534]
Hello dear community.
I have the problem that men no longer start Vocaluxe.
Had to make my latop new and since then it has not worked.
If the error message comes: "Error while reading" ScreenMain ".xml"

Here is the complete error message:
"[00:00:00.0800440] [Information] Starting to log

{ThreadId: 1, AdditionalData: ["{ Version = Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-563-g5e77816) }", "{ StartDate = 19.06.2020 19:57:48 }", "{ Id = daf01008-b34c-4d98-a5d3-19b86367fc89 }"], CallingContext: "{ callerMethodeName = Init, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CLog.cs, callerLineNumer = 128 }"}

[00:00:00.1639379] [Information] Started "Init Program"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.1729385] [Information] Started "Init Language"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.2469377] [Information] Finished "Init Language" successfully in 69.86ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.2499375] [Information] Started "Init Config"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.3551069] [Information] Finished "Init Config" successfully in 105.38ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.4837400] [Information] Started "Init Draw"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.7258268] [Error] [Direct3D] This AAMode is not supported by this device or driver, fallback to no AA

{ThreadId: 1, CallingContext: "{ callerMethodeName = .ctor, callerFilePath = C:\projects\vocaluxe\Vocaluxe\Lib\Draw\CDirect3D.cs, callerLineNumer = 153 }"}

[00:00:00.8518244] [Information] Finished "Init Draw" successfully in 368.06ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.8538253] [Information] Started "Init Playback"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.0494305] [Information] Finished "Init Playback" successfully in 195.87ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.0494305] [Information] Started "Init Record"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.3874304] [Information] Finished "Init Record" successfully in 337.80ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.3874304] [Information] Started "Init Videodecoder"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.3934306] [Information] Finished "Init Videodecoder" successfully in 5.72ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.3934306] [Information] Started "Init Database"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.8087069] [Information] Finished "Init Database" successfully in 414.78ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.8087069] [Information] Started "Init Webcam"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.8764718] [Information] Finished "Init Webcam" successfully in 67.85ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.8764718] [Information] Started "Init Background Music"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.8824695] [Information] Finished "Init Background Music" successfully in 6.01ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.8824695] [Information] Started "Init Profiles"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.8974703] [Information] Finished "Init Profiles" successfully in 14.29ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.8974703] [Information] Started "Init Fonts"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.9224720] [Information] Started "Build Glyphs"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:03.6114699] [Information] Finished "Build Glyphs" successfully in 1,688.72ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:03.6114699] [Information] Finished "Init Fonts" successfully in 1,714.11ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:03.6114699] [Information] Started "Init Theme"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:03.6534700] [Information] Finished "Init Theme" successfully in 42.22ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:03.6534700] [Information] Started "Load Theme"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.4614707] [Information] Finished "Load Theme" successfully in 807.65ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:04.4614707] [Information] Started "Init Cover"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.5284704] [Information] Finished "Init Cover" successfully in 66.29ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:04.5284704] [Information] Started "Init Screens"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.5344702] [Information] Started "Build Screen List"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.5554698] [Information] Finished "Build Screen List" successfully in 20.81ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:04.5554698] [Information] Started "Load Theme"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.5614721] [Information] Started "Load Theme Test"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.6344711] [Information] Finished "Load Theme Test" successfully in 73.80ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:04.6354719] [Information] Started "Load Theme Load"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.6394718] [Information] Finished "Load Theme Load" successfully in 4.17ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:04.6394718] [Information] Started "Load Theme Main"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:04.6594700] [Fatal] Error while reading "ScreenMain".xml

{ThreadId: 1, CallingContext: "{ callerMethodeName = LoadTheme, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Menu\CMenu.cs, callerLineNumer = 235 }"}

System.Xml.XmlException: Das Stammelement ist nicht vorhanden.

   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)

   bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()

   bei System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)

   bei System.Xml.XmlDocument.Load(XmlReader reader)

   bei VocaluxeLib.Xml.CXmlDeserializer._Deserialize[T](XmlReader reader, Object o) in C:\projects\vocaluxe\VocaluxeLib\Xml\CXmlDeserializer.cs:Zeile 546.

   bei VocaluxeLib.Xml.CXmlDeserializer.Deserialize[T](String filePath, T o) in C:\projects\vocaluxe\VocaluxeLib\Xml\CXmlDeserializer.cs:Zeile 630.

   bei VocaluxeLib.Xml.CXmlDeserializer.Deserialize[T](String filePath) in C:\projects\vocaluxe\VocaluxeLib\Xml\CXmlDeserializer.cs:Zeile 607.

   bei VocaluxeLib.Menu.CMenu.LoadTheme(String xmlPath) in C:\projects\vocaluxe\VocaluxeLib\Menu\CMenu.cs:Zeile 177.

"
Please help!
thank you

**Comment by Stefan1200-de** [comment]
Please try to reinstall Vocaluxe, just keep the Profiles and your songs folder and keep the HighscoreDB.sqlite file. If you are unsure, make a copy of the whole Vocaluxe folder.

**Comment by Manticore2020** [comment]
Hi So installation itself is unfortunately not at all. On the Vocaluxe site you can only download packed folders.
I have unpacked it several times and then copied my songs such as profiles and the highscore data into it.
But the program again brings the same error message.
I set up my latop again. Before I did this, the program was running.
Since I made it new, the error message has been coming.
I have drivers for new graphics and drivers for direct x and java.
Does the program need anything else?

**Comment by Stefan1200-de** [comment]
Did you test the Nightly or Vocaluxe 0.4.1?

**Comment by Manticore2020** [comment]
nightly version

**Comment by Stefan1200-de** [comment]
Please check the file size of the **ScreenMain.xml** in the **Vocaluxe\Themes\Genius\Screens** folder. Is it exactly 6.501 Bytes? Do you have other folders in the **Themes** folder? You don't use the same directory for the Nightly as for 0.4.1? Because the Themes from 0.4.X are not compatible with the Nightly!

**Comment by Manticore2020** [comment]
No use different directories.
So my screens folder is so big: 351 KB (359,698 bytes)

**Comment by Stefan1200-de** [comment]
I was not asking for the folder size.

**Comment by Manticore2020** [comment]
was ok for a size then?
Also in my themes folder is: genius and changelog folder and a Genius.xml datai.
The following are in the Changelog subfolder:

[Changelog_ScreenHighscore.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809059/Changelog_ScreenHighscore.txt)
[Changelog_ScreenLoading.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809060/Changelog_ScreenLoading.txt)
[Changelog_ScreenMain.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809061/Changelog_ScreenMain.txt)
[Changelog_ScreenNames.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809062/Changelog_ScreenNames.txt)
[Changelog_ScreenOptionsGame.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809063/Changelog_ScreenOptionsGame.txt)
[Changelog_ScreenOptionsLyrics.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809064/Changelog_ScreenOptionsLyrics.txt)
[Changelog_ScreenOptionsRecord.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809065/Changelog_ScreenOptionsRecord.txt)
[Changelog_ScreenOptionsSound.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809066/Changelog_ScreenOptionsSound.txt)
[Changelog_ScreenOptionsTheme.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809067/Changelog_ScreenOptionsTheme.txt)
[Changelog_ScreenOptionsVideo.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809068/Changelog_ScreenOptionsVideo.txt)
[Changelog_ScreenProfiles.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809069/Changelog_ScreenProfiles.txt)
[Changelog_ScreenScore.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809070/Changelog_ScreenScore.txt)
[Changelog_ScreenSing.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809071/Changelog_ScreenSing.txt)
[Changelog_ScreenSong.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809072/Changelog_ScreenSong.txt)
[Changelog_SkinSystem.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809073/Changelog_SkinSystem.txt)
[Changelog_ThemeSystem.txt](https://github.com/Vocaluxe/Vocaluxe/files/4809074/Changelog_ThemeSystem.txt)


And in the Genius subfolder there is another folder with screens and files.:
Standard, Ice_blue, Crimson_red
and many png files and mp4

In the subfolder screens are xml files

**Comment by Stefan1200-de** [comment]
> was ok for a size then?

Please check out my post from 21. Juni 2020, 09:18 MESZ (75 minutes ago).

**Comment by Manticore2020** [comment]
ah ok yes the screenmain.xml is size is correct 6.501 Bytes

**Comment by Stefan1200-de** [comment]
If you just unpack the Vocaluxe ZIP file to a new location without coping any files into that directory and just start Vocaluxe without any songs or modifications, does it run then?

**Comment by Manticore2020** [comment]
I heard new folders freshly unpacked without losing anything, but unfortunately I get the same error message

**Comment by Stefan1200-de** [comment]
@Manticore2020 Which on-access virus scanner are you using?

@lukeIam Do you have more ideas? Why it could be a problem to read an XML file on some systems?

**Comment by Manticore2020** [comment]
360 Security Suite 
The antivirus program was on before the laptop was set up again. there it went

**Comment by Stefan1200-de** [comment]
Just to be sure, can you disable the on-access scanner for a minute and try running Vocaluxe while it is disabled? I don't think that this is the reason, but in fact I have no more ideas.

**Comment by Manticore2020** [comment]
I immediately uninstalled the laptop again but unfortunately the same problem.
I copied the folder from latop to usb stick and started it on another pc with windows 10, and hey presto.
Then stick to laptop and start the error message again.
I do not understand that

**Comment by Manticore2020** [comment]
I found this version online <Version> Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-327-gfda7d4a) </Version>

But this is also missing the highscore in the songs

**Comment by Stefan1200-de** [comment]
It's not missing, it is a very new feature, only the nightly has it!

**Comment by Manticore2020** [comment]
So when I unpack the nightly and look in the XML it says:
<Version> Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-563-g5e77816) </Version>

**Comment by Stefan1200-de** [comment]
I know

**Comment by Manticore2020** [comment]
Yes, it found out what it was now.

I pulled beta 0.4 versions out of the network and they didn't want to go either and complained that the visual c is missing.

Geiler shit why didn't the nightly version gripe at that? I have installed this here: Visual C ++ Redistributable for Visual Studio 2012 Update 4. and lo and behold it's finally possible. Thank you MEGA for your help

**Comment by Manticore2020** [comment]
But I still have an outward question.
It says that you can control the software with your smartphone.
how does it work and what do i need?

**Comment by Stefan1200-de** [comment]
Well, there is no installer anymore. But the readme.txt file should give a hint about it.
