### ISSUE TITLE
Highscore in Song

### ISSUE THREAD

**Issue by Manticore2020** [Vocaluxe/Vocaluxe#535]
Hi how do I get the high scores to appear in the title? What do I have to do in the Theme Editor with Shift + F1 but how do I create the link to the highscore of the song?
Before I want to sing a song that sees high scores.

Please help

**Comment by Stefan1200-de** [comment]
I don't understand your problem? On the song screen (where you can see all songs in your library) you can see the highscores of a song. Open the song menu or just press CTRL + H.

**Comment by Manticore2020** [comment]
Yes just not. there is simply no highscore area for the songs.
So when I choose song xy there is singing, degree of difficulty etc. but no high score.
Got all three versions on it.

Nightly: has not been running since the laptop was set up again
Pre release: there is unfortunately nothing
Stable release: yes it runs on a laptop but does not have a high score field

**Comment by Stefan1200-de** [comment]
That feature is quite new and exists only in the Nightly.

**Comment by Manticore2020** [comment]
ahhh ok shame nightly is doesn´t work on my laptop
