### ISSUE TITLE
Vocaluxe wiht Smartphone(android)

### ISSUE THREAD

**Issue by Manticore2020** [Vocaluxe/Vocaluxe#536]
Control Vocaluxe with your smartphone. Supposedly according to the page this should work but in the readme I only found something about the wiiremote controller.

I need help to operate Vocaluxe with my smartphone, what do I need for it?
My laptop has bluetooth if necessary

Please help

**Comment by Stefan1200-de** [comment]
https://github.com/Vocaluxe/Vocaluxe/wiki/HowTo:-Control-Vocaluxe-with-smartphone-tablet
