### ISSUE TITLE
Config.xml won't keep changes

### ISSUE THREAD

**Issue by Amandacheergirl** [Vocaluxe/Vocaluxe#538]
I edit the config.xml.
Upon opening it, my settings are still there.
If I run vocaluxe.exe, the old settings switch back!

**Comment by Stefan1200-de** [comment]
What did you changed? Because if I change some settings in the config.xml while Vocaluxe is closed, it works fine on next Vocaluxe start.

**Comment by Amandacheergirl** [comment]
Hi Stefan,

I haven't changed anything. Vocaluxe just crashed one day and now it doesn't save high scores. It still remembers the previous scores which I would like to keep. If I reinstall, I will lose the high scores.

**Comment by Stefan1200-de** [comment]
Can you send me the log files after you sing a song with a valid highscore? And can you also upload the HighscoreDB.sqlite file? Can you test the newest Nightly in a new folder and copy over the HighscoreDB.sqlite file from the old directory to the new nightly directory? Please copy, not move. Never overwrite files, if you test some stuff for me :)

**Comment by Stefan1200-de** [comment]
Duplicate issue #543, closing this one, because the title and text fits better to the problem.
