### ISSUE TITLE
Vocaluxe crashed and won't save scores

### ISSUE THREAD

**Issue by Amandacheergirl** [Vocaluxe/Vocaluxe#543]
It still has the old scores, and I don't want to re-install and lose those scores.
How do I get it to save scores again?
When it crashed, I couldn't run Vocaluxe executable any more.
I replaced just the .exe and it ran again, but doesn't save scores.

**Comment by Stefan1200-de** [comment]
Can you send me the log files after you sing a song with a valid highscore? And can you also upload the HighscoreDB.sqlite file? Can you test the newest Nightly in a new folder and copy over the HighscoreDB.sqlite file from the old directory to the new nightly directory? Please copy, not move. Never overwrite files, if you test some stuff for me :)

**Comment by Amandacheergirl** [comment]
I was able to fix the problem!
Thanks

**Comment by Amandacheergirl** [comment]
config.xml won't keep changes was a separate problem I had which I gave up on.
Sorry for the confusion with the 2 different issues.

**Comment by Stefan1200-de** [comment]
Which problem do you still have after reinstall?

**Comment by Amandacheergirl** [comment]
I was never able to modify the config file (wouldn't save changes).

**Comment by Stefan1200-de** [comment]
What did you exactly and what do you change? What do you expect, what is not working?
