### ISSUE TITLE
Game Crashes On Song Selection

### ISSUE THREAD

**Issue by DatProGuy** [Vocaluxe/Vocaluxe#545]
Hi, I'm having some trouble with Vocaluxe.

When I select certain songs (abt 8 have this issue of my 1200, from what I've found so far), the game freezes and then crashes. I noticed however that when I removed the video file from the .txt file the songs in question worked perfectly, I'm not too sure what the go could be here, additionally there is nothing in relation to these songs appearing in the Error.log file either.

Regardless based on the fact that once removed they seem to work I'm near certain it's an issue with the video or the way in which it's being played I'm just not sure what (Running Latest "Stable Build").

Any help would be appreciated, Thanks! :)

**Comment by Stefan1200-de** [comment]
Can you check the latest nightly? Please don't overwrite your current version, just download the nightly and use a different folder for the nightly. Of course, you can use the same song directory.

**Comment by DatProGuy** [comment]
Yeah no worries mate, will give that a crack, I'm really glad to see that there is still development and effort going into VX!

**Comment by DatProGuy** [comment]
Just tested it and the tracks that had the issues are working as expected on the Nightly, thanks for the help, I'll have to use Nightly from now on! :) (Plus Nightly looks 100x better anyways!)
