### ISSUE TITLE
Czech characters display

### ISSUE THREAD

**Issue by matozelo** [Vocaluxe/Vocaluxe#547]
I have problem with displaying czech / polish / slovak symbols in lyrics. Is there way to display these symbols or it is possible to sing only in english? The menu can be turned to czech with characters like "čťžýáíú" but in lyrics and song names not.

**Comment by Stefan1200-de** [comment]
Try setting #ENCODING:UTF8 in the txt file and convert that txt file to UTF-8 encoding. It should work in this case.

**Comment by matozelo** [comment]
👍 
Thank you. It helped :)
