### ISSUE TITLE
Error starting up vocalux on Win10 x64

### ISSUE THREAD

**Issue by nevyen** [Vocaluxe/Vocaluxe#549]
Hey I downloaded the latest stable release for Windows x64. 

When I try to start the application the following error could be found in log:

```
1) Error on start up: System.TypeInitializationException: Der Typeninitialisierer für "Gst.Application" hat eine Ausnahme verursacht. ---> System.DllNotFoundException: Die DLL "libgstreamer-1.0-0.dll": Die angegebene Prozedur wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007F) kann nicht geladen werden.
   bei Gst.List.gst_value_list_get_type()
   bei Gst.List.get_GType()
   bei Gst.Application..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Gst.Application.Init()
   bei Vocaluxe.Lib.Sound.Playback.GstreamerSharp.CGstreamerSharpAudio.Init()
   bei Vocaluxe.CMainProgram._Run(String[] args)
```

Any Idea how to solve the problem?

**Comment by Stefan1200-de** [comment]
I just downloaded the file and was able to start Vodaluxe.exe. Are you sure, that you unpacked the whole ZIP file and no malware scanner was deleting a file?

**Comment by nevyen** [comment]
Thanks for your very fast feedback. 

I got no message from my antivirus software that something would be deleted. 

Maybe I am able to test it today on a different pc. 

Have a wonderful Christmas ;-)

**Comment by flokuep** [comment]
Could you check, if Windows is blocking some DLL files? I've encountered some problems with this some years ago, just check the zip file before unzipping and follow this blog post. https://dlaa.me/blog/post/unblock

**Comment by nevyen** [comment]
Hey in case if Christmas, I haven’t the time to look for this by now. 

Thanks for the hint with the dll files. 

I will have a look in the next days.

**Comment by flokuep** [comment]
You're welcome! Have a merry christmas, too.

**Comment by nevyen** [comment]
So I checked it on an other PC. 

There it is running without any problems. So maybe my antivrus is blocking something. I can'T find anything which is blocked. So I have no Idea whats going on. 

The x86 Version is working without any problems. 

Thanks for your support. 

I wish you nice holidays ;-)
