### ISSUE TITLE
TicTacToe mode crashs at start

### ISSUE THREAD

**Issue by Elektro2000** [Vocaluxe/Vocaluxe#550]
Hi, 

I'm a huge fan of the TicTacToe Mode, unfortunately this mode crashes everytime I start a song. 

```
{ThreadId: 8, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}
[00:00:36.1916411] [Fatal] Unhandled error: "Not required!"
{ThreadId: 1, CallingContext: "{ callerMethodeName = Main, callerFilePath = C:\projects\vocaluxe\Vocaluxe\Program.cs, callerLineNumer = 76 }"}
System.ArgumentException: Not required!
   bei VocaluxeLib.PartyModes.TicTacToe.CPartyModeTicTacToe.GetScreenSongOptions()
   bei Vocaluxe.Screens.CScreenSing.OnShow() in C:\projects\vocaluxe\Vocaluxe\Screens\CScreenSing.cs:Zeile 435.
   bei Vocaluxe.Base.CGraphics.Draw() in C:\projects\vocaluxe\Vocaluxe\Base\CGraphics.cs:Zeile 224.
   bei Vocaluxe.Lib.Draw.CDrawBase`1.MainLoop() in C:\projects\vocaluxe\Vocaluxe\Lib\Draw\CDrawBase.cs:Zeile 401.
   bei Vocaluxe.Lib.Draw.CDrawBaseWindows`1.MainLoop() in C:\projects\vocaluxe\Vocaluxe\Lib\Draw\CDrawBaseWindows.cs:Zeile 218.
   bei Vocaluxe.CMainProgram._Run(String[] args) in C:\projects\vocaluxe\Vocaluxe\Program.cs:Zeile 300.
   bei Vocaluxe.CMainProgram.Main(String[] args) in C:\projects\vocaluxe\Vocaluxe\Program.cs:Zeile 72.
```

I used the latest nightly build (Sep 25 2020).

Regards

**Comment by steump** [comment]
Same problem - does someone have a solution?
I used also the latest nightly build (Sep 25 2020).

@lukeIam @Stefan1200-de you know about it?

**Comment by pancho187** [comment]
No solution, but the same issue (latest nightly build Sep 2020).

**Comment by Stefan1200-de** [comment]
Well, I don't use party modes on my end, but I made sure, that Vocaluxe don't crash on start singing within TicTacToe party mode. But it is more testing needed, if the TicTacToe party mode itself still works as expected. I just quickly compared it with Vocaluxe 0.4.0 and it seems to work like the same.

The new nightly build should be online in around 30 minutes. Please test it with that version.

**Comment by Stefan1200-de** [comment]
Unfortunately the new nightly build with that bugfix was not created, I check that.

**Comment by lukeIam** [comment]
Seems that there was a network problem reaching Chocolatey.
Retriggering should normally solve the problem.

Stefan ***@***.***> schrieb am Do., 23. Sept. 2021, 18:33:

**Comment by Stefan1200-de** [comment]
@lukeIam it seems I don't have the permission on AppVeyor to do so. Currently I check if I can fix another smaller bug and create a new PR, to trigger it. If you have a button in AppVeyor to restart the build process, it would be great. :)

**Comment by lukeIam** [comment]
I have the permission - but I'm not at home atm.
We should also give you the permission here.
But a new commit should also help at the moment.

Stefan ***@***.***> schrieb am Do., 23. Sept. 2021, 19:20:

**Comment by Stefan1200-de** [comment]
@lukeIam yeah, new PR with a very small bugfix is online. As soon as someone approved it (I already wrote to daggeg), we should get a new nightly (I hope at least ;)).
I'm now registered on AppVeyor with my GitHub account. If you need some information from my account to add me there, feel free to ask me.

**Comment by Stefan1200-de** [comment]
New nightly is online since some minutes.

**Comment by steump** [comment]
Perfect, now it works - Thanks @Stefan1200-de
