### ISSUE TITLE
Display song name on sing screen in pause menu

### ISSUE THREAD

**Issue by Stefan1200-de** [Vocaluxe/Vocaluxe#559]
Just a reminder for me.

**Comment by marwin89** [comment]
### Suggestion:
Display song name on sing screen in pause menu.

### Why:
Better orientation for players

### Mockup:
![Image](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/2a75169e-b735-41b7-b3dd-7d2155e84e5d)

**Comment by marwin89** [comment]
@damienlaguerre: would you like to do this task? It's quite small, but it's meaningful. 😄

**Comment by damienlaguerre** [comment]
@marwin89 Why not 😆
