### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by Michri** [Vocaluxe/Vocaluxe#571]
Hello, 
some time ago I was able to download nightly builds, which I was able to extract and start directly (compiled versions). Now I cannot find them any more. Is this feature not available any more? Any other way to get a newer version in place?
BTW: I am not a programmer, so not so familar with develoepr-tools.
Thanks

**Comment by Stefan1200-de** [comment]
Oh, you are right. ~2 weeks ago I was still able to download the nightly builds.

@lukeIam do you know, why the nightly builds are not available anymore?

**Comment by lukeIam** [comment]
> @lukeIam do you know, why the nightly builds are not available anymore?

The upload failed:
https://ci.appveyor.com/project/VocaluxeBuildBot/vocaluxe/branch/develop/job/fybacoo6uf26kk9t#L4911

Seems there was a change in the permissions or the access token expired...

**Comment by Michri** [comment]
@lukeIam : Something you can/need to fix? Or does each user need to change something to get the downloads available again?
Thanks

**Comment by lukeIam** [comment]
It's definitely on our side - I did a quick check the token has no expiration date.
Atm I have no idea why the script lost the permission to upload releases.
I just have triggered a rebuild - maybe we are lucky an this was just an temporary problem.

**Comment by lukeIam** [comment]
hmm - updated the tokens in the appveyor file: #573 (lets see if this helps)
(I thought I already did this when github changed tokens - but I could not find the commit for it...)

**Comment by Stefan1200-de** [comment]
It seems the nightly build are working again. Thanks @lukeIam

**Comment by lukeIam** [comment]
> It seems the nightly build are working again. Thanks @lukeIam

welcome!
