### ISSUE TITLE
Duets don't seem to work

### ISSUE THREAD

**Issue by viktor1234678** [Vocaluxe/Vocaluxe#577]
Duet songs don't seem to work in the latest nightly. It always shows both players both parts. I tried playing around with different microphones but always got the same result. Is it a problem on my part or is there no duet support?

**Comment by Stefan1200-de** [comment]
Well, I often use duet songs, which works without problems, even with the newest nightly.
Do you select different voices on the player selection screen? Is your song detected as duet song within Vocaluxe?

**Comment by viktor1234678** [comment]
I found the problem I think. It doesn't recognize the songs as duets. But how does Vocaluxe recognize a file as a Duet?

**Comment by Stefan1200-de** [comment]
> I found the problem I think. It doesn't recognize the songs as duets. But how does Vocaluxe recognize a file as a Duet?

Make sure, that the P1 and P2 tags are set correctly. If you downloaded the file from USDB, you have to add the P1 and P2 tags on your own, because USDB don't support duet files.

**Comment by viktor1234678** [comment]
Thanks For The Help
