### ISSUE TITLE
Getting this everytime we try to start up

### ISSUE THREAD

**Issue by EsExpComp** [Vocaluxe/Vocaluxe#585]
[00:00:00.0952938] [Information] Starting to log

{ThreadId: 1, AdditionalData: ["{ Version = Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-588-g4d62eff) }", "{ StartDate = 23/08/2022 23:37:57 }", "{ Id = 35e457ff-d464-45b5-8db5-e9b2c986f40b }"], CallingContext: "{ callerMethodeName = Init, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CLog.cs, callerLineNumer = 128 }"}

[00:00:00.1282032] [Information] Started "Init Program"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.1321988] [Information] Started "Init Language"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.2024075] [Information] Finished "Init Language" successfully in 69.71ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.2024075] [Information] Started "Init Config"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.2312933] [Information] Finished "Init Config" successfully in 29.61ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.3001116] [Information] Started "Init Draw"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.1326024] [Information] Finished "Init Draw" successfully in 833.16ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.1335992] [Information] Started "Init Playback"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.1824302] [Information] Finished "Init Playback" successfully in 48.30ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.1824302] [Information] Started "Init Record"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.4870693] [Information] Finished "Init Record" successfully in 304.93ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.4870693] [Information] Started "Init Videodecoder"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.4880660] [Information] Finished "Init Videodecoder" successfully in 1.06ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.4880660] [Information] Started "Init Database"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.7442770] [Information] Finished "Init Database" successfully in 256.10ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.7442770] [Information] Started "Init Webcam"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:02.2309736] [Information] Finished "Init Webcam" successfully in 486.58ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:02.2309736] [Information] Finished "Init Program" successfully in 2,103.47ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:02.2329684] [Error] Error on start up: "O tipo do objeto deve ser __ComObject ou derivado de __ComObject.

Nome do parâmetro: o"

{ThreadId: 1, CallingContext: "{ callerMethodeName = _Run, callerFilePath = C:\projects\vocaluxe\Vocaluxe\Program.cs, callerLineNumer = 287 }"}

System.ArgumentException: O tipo do objeto deve ser __ComObject ou derivado de __ComObject.

Nome do parâmetro: o

   em System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)

   em AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread(Boolean runGraph)

   em AForge.Video.DirectShow.VideoCaptureDevice.get_VideoCapabilities()

   em Vocaluxe.Lib.Webcam.CAForgeNet.Init() na C:\projects\vocaluxe\Vocaluxe\Lib\Webcam\CAForgeNet.cs:linha 47

   em Vocaluxe.Base.CWebcam.Init() na C:\projects\vocaluxe\Vocaluxe\Base\CWebcam.cs:linha 43

   em Vocaluxe.CMainProgram._Run(String[] args) na C:\projects\vocaluxe\Vocaluxe\Program.cs:linha 183

**Comment by lukeIam** [comment]
I think this has something to do with WebcamLib.
Can you try to disable yout webcam (if you have one)

**Comment by EsExpComp** [comment]
> I think this has something to do with WebcamLib. Can you try to disable yout webcam (if you have one)

thanks for attenttion,

we ve tried and not workin

same error

[00:00:00.0239980] [Information] Starting to log

{ThreadId: 1, AdditionalData: ["{ Version = Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-591-gf00e1d7) }", "{ StartDate = 19/10/2022 20:41:01 }", "{ Id = 3e2c9ec4-0c21-4e7b-a909-26201331a111 }"], CallingContext: "{ callerMethodeName = Init, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CLog.cs, callerLineNumer = 128 }"}

[00:00:00.0487026] [Information] Started "Init Program"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.0527037] [Information] Started "Init Language"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.0695141] [Information] Finished "Init Language" successfully in 18.51ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.0695141] [Information] Started "Init Config"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.1063291] [Information] Finished "Init Config" successfully in 35.10ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.1825545] [Information] Started "Init Draw"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.4326228] [Information] Finished "Init Draw" successfully in 251.09ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.4326228] [Information] Started "Init Playback"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.4735761] [Information] Finished "Init Playback" successfully in 41.94ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.4735761] [Information] Started "Init Record"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.6866556] [Information] Finished "Init Record" successfully in 213.75ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.6906543] [Information] Started "Init Videodecoder"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.6906543] [Information] Finished "Init Videodecoder" successfully in 1.48ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.6906543] [Information] Started "Init Database"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:00.8068272] [Information] Finished "Init Database" successfully in 114.66ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:00.8068272] [Information] Started "Init Webcam"

{ThreadId: 1, CallingContext: "{ callerMethodeName = Start, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 57 }"}

[00:00:01.2696638] [Information] Finished "Init Webcam" successfully in 463.12ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.2696638] [Information] Finished "Init Program" successfully in 1,221.43ms

{ThreadId: 1, CallingContext: "{ callerMethodeName = Stop, callerFilePath = C:\projects\vocaluxe\VocaluxeLib\Log\CBenchmark.cs, callerLineNumer = 74 }"}

[00:00:01.2707026] [Error] Error on start up: "O tipo do objeto deve ser __ComObject ou derivado de __ComObject.

Nome do parâmetro: o"

{ThreadId: 1, CallingContext: "{ callerMethodeName = _Run, callerFilePath = C:\projects\vocaluxe\Vocaluxe\Program.cs, callerLineNumer = 287 }"}

System.ArgumentException: O tipo do objeto deve ser __ComObject ou derivado de __ComObject.

Nome do parâmetro: o

   em System.Runtime.InteropServices.Marshal.ReleaseComObject(Object o)

   em AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread(Boolean runGraph)

   em AForge.Video.DirectShow.VideoCaptureDevice.get_VideoCapabilities()

   em Vocaluxe.Lib.Webcam.CAForgeNet.Init() na C:\projects\vocaluxe\Vocaluxe\Lib\Webcam\CAForgeNet.cs:linha 47

   em Vocaluxe.Base.CWebcam.Init() na C:\projects\vocaluxe\Vocaluxe\Base\CWebcam.cs:linha 43

   em Vocaluxe.CMainProgram._Run(String[] args) na C:\projects\vocaluxe\Vocaluxe\Program.cs:linha 183
