### ISSUE TITLE
Tutorial link on homepage leads to scam website

### ISSUE THREAD

**Issue by RumovZ** [Vocaluxe/Vocaluxe#587]
https://www.vocaluxe.org/ links to `ultraguide.net` for a song creation tutorial, but this site now seems to be in the hands of scammers.

**Comment by Stefan1200-de** [comment]
Thanks @lukeIam

**Comment by lukeIam** [comment]
@RumovZ thanks for reporting!

I removed the link from the site and cleared the caches of cloudflare -> the change should be live now/soon.

**Comment by lukeIam** [comment]
For me it's already live (linking to vocaluxe now - seems to be the default for no url).
@Stefan1200-de we might should find another tutorial sometime in the future.

**Comment by Stefan1200-de** [comment]
@lukeIam I only know this German "howto": https://www2.informatik.uni-hamburg.de/fachschaft/wiki/index.php/HOWTO:UltraStar_Songs_erstellen

**Comment by Stefan1200-de** [comment]
And I found some English public YouTube videos from @daggeg: How to create songs for Ultrastar
part 1 the tapping: https://www.youtube.com/watch?v=Khs6YVwKtr0
part 2 the finetuning/fixing the sync: https://www.youtube.com/watch?v=-lVwIn03xME
part 3 setting the pitches/notes: https://www.youtube.com/watch?v=OQZfu6ynQu0

Don't know, if we can use this somehow.
