### ISSUE TITLE
when i try to use my mic it says at least one player is assigned to two mics

### ISSUE THREAD

**Issue by Cxsmo-ai** [Vocaluxe/Vocaluxe#591]
when i try to use my mic it says at least one player is assigned to two mics 
![image](https://user-images.githubusercontent.com/74084396/200446331-7204f8c3-0935-4b79-a478-fecc87a4931a.png)

**Comment by Stefan1200-de** [comment]
Check out the other devices, maybe player 1 has another device selected too.
