### ISSUE TITLE
how does someone join my server so that they can play with me with their mic

### ISSUE THREAD

**Issue by Cxsmo-ai** [Vocaluxe/Vocaluxe#592]
how does someone join my server so that they can play with me with their mic

**Comment by marwin89** [comment]
- there is **no online multiplayer for vocaluxe.** Melody Mania will introduce that in the end of 2023.
- If you mean the vocaluxe webbrowser app: you can't use smartphone as a microphone.

For more help go to **help desk** of [UltraStar Vocaluxe Performous Community](https://discord.gg/tNEXZw2QJX) or read [common FAQ](https://www.open-music-games.org/help/frequently-asked-questions).
