### ISSUE TITLE
"Vocaluxe 2024" Theme for Nightly Builds

### ISSUE THREAD

**Issue by marwin89** [Vocaluxe/Vocaluxe#602]
Hi @Vocaluxe, @flokuep , hi @Stefan1200-de , hi @lukeIam ,

schöne Grüße! Könnt ihr euch mein **Theme** anschauen und prüfen? Vielleicht könnt ihr es als optionales Design integrieren oder auf der Website verlinken?

Es heißt **Vocaluxe 2024** und basiert auf Genius (Stand: 2022-10-29). ScreenConfigs sind identisch. Geändert sind Button und Slide Colors, einige Texturen und alle Backgroundvideos. Designmaterialien für Videos sind rechtlich alle freigegeben und ohne Attribution. Die Videos habe ich mit MS Climpchamp gemacht.

**Comment by marwin89** [comment]
@Vocaluxe 
Ich habe noch eine separate Avatar Sammlung erstellt: https://github.com/marwin89/inspire-profile-expansion/ - was denkt ihr?

**Comment by Stefan1200-de** [comment]
Bisher habe ich mir nur die Bilder angeschaut, aber soweit gefällt mir, was ich sehe.
Wann ich zeitlich dazu komme, mir das Theme direkt anzuschauen, weiß ich noch nicht.
So oder so, danke für deine Arbeit.

**Comment by marwin89** [comment]
Danke, freue mich da beizutragen.

Übrigens möchte ich auch eine **neue Background Music** ins Theme integrieren und für Vocaluxe lizensieren. 
Schaut mal hier: https://donorbox.org/bgm-license-for-vocaluxe - vielleicht klappts ja mit ner gemeinsamen Mini-Spendenaktion?

**Comment by marwin89** [comment]
@Vocaluxe
Ich habe die separate [Avatar Sammlung](https://github.com/marwin89/Vocaluxe-Ultrastar-Profile-Add-On) komplett überholt und auf 100 Avatare erweitert - was denkt ihr?

![Preview2](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/4f6a2395-6627-40db-bdcb-f3f98efc17f1)

**Comment by marwin89** [comment]
Hi @Stefan1200-de 👋 , 

I've updated the Icons for smartphone control - could you merge it into nightly eventually? Can't make pull-requests.
Icons are from [flaticons.net](https://flaticons.net/) (free for commercial use).

Here are the files [img.zip](https://github.com/Vocaluxe/Vocaluxe/files/12358194/img.zip)

![smartphone-control--new](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/1b12921f-fdce-4f59-af38-e3d9e4dce255)

**Comment by lukeIam** [comment]
@marwin89 everybody should be able to open a pull request (only merging them is restricted)
Just fork the repo, make a branch with your change there and open a pullrequest marwin89/Vocaluxe -> Vocaluxe/Vocaluxe
