### ISSUE TITLE
[Community] Activate GitHub Discussion

### ISSUE THREAD

**Issue by marwin89** [Vocaluxe/Vocaluxe#604]
Hi @Vocaluxe, hi @Stefan1200-de ,

it would be cool if you activate the [GitHub discussion section](https://github.com/features/discussions) in the vocaluxe repository. 

Its a good alternative to discord and gitter. It's an easy way to manage the vocaluxe community and provide contact to devs/maintainers. Non-Logged-In-Users can view the content as well.

Regards

![github-discussions](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/e6a3ab28-7ba5-4bf2-b52a-514d3d409745)

**Comment by lukeIam** [comment]
Hi @marwin89 👋

I just enabled Discussions.
But the main problem with Vocaluxe is in my point of view that nobody has much time to develop...
Anyhow an central forum is a good idea (we had a bulletin board in the past)

**Comment by marwin89** [comment]
@lukeIam : sorry if I ask too much recently, but can you link the discussion section in vocaluxe.org eventually? there's a dead link to the forum. Thank you

**Comment by Stefan1200-de** [comment]
> @lukeIam : sorry if I ask too much recently, but can you link the discussion section in vocaluxe.org eventually? there's a dead link to the forum. Thank you

done

**Comment by marwin89** [comment]
thanks!
