### ISSUE TITLE
[Question] Autor metadata key

### ISSUE THREAD

**Issue by Baklap4** [Vocaluxe/Vocaluxe#618]
Hey,
I'm wondering why there is a key called `AUTOR` withing the songloader: <https://github.com/Vocaluxe/Vocaluxe/blob/develop/VocaluxeLib/Songs/CSongLoader.cs#L167>

Are there any actual txt files out there in the wild using this field? I'd love to know more about it :)

**Comment by Stefan1200-de** [comment]
CREATOR will be used quite often, just check out the USDB.
AUTOR & AUTHOR are just aliases.

**Comment by marwin89** [comment]
@Vocaluxe FYI: in case you don't know there is a new upcoming project for standardizing and versioning the ultrastar txt-format. 🎵 

- It's meant to be a common standard for all games. It comes up from the ultrastar creator community.
- Initiative from: Asgard Sings, Bohning, Rakuri
- Here is the repository: https://github.com/UltraStar-Deluxe/format

**Comment by Baklap4** [comment]
Aight thanks for clarifying @Stefan1200-de :)

Did you guys find any text files out there using the aliases? If no, would it be a problem to deprecate these?
As Marwin said we're trying to unify, standardize and versionise the format so we don't have custom stuff laying around

**Comment by Stefan1200-de** [comment]
@Baklap4 so you want to use AUTOR & AUTHOR for another values?

**Comment by marwin89** [comment]
This issue is also adressed by
- #626 

I'm in exchange with flokeup for official song format implementation v1.1.0
