### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [Vocaluxe/Vocaluxe#620]
Dear @Vocaluxe team, @brunzel, @flokuep, @Stefan1200-de,

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/vocaluxe/

To disable/delete tabs, go here: https://sourceforge.net/projects/vocaluxe/
To add a new tab, go here: https://sourceforge.net/projects/vocaluxe/
To change informations, go here: https://sourceforge.net/p/vocaluxe/admin/overview
To export, go here: https://sourceforge.net/p/vocaluxe/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/vocaluxe/admin/overview
- A new tab, go here: https://sourceforge.net/projects/vocaluxe/

Thanks in advance.

**Comment by flokuep** [comment]
I've added the GitHub URL to the "Moved Project to". Thanks for proposing that change!
