### ISSUE TITLE
#AUDIO as successor for #MP3

### ISSUE THREAD

**Issue by marwin89** [Vocaluxe/Vocaluxe#622]
## Suggestion

- [x] Implement #AUDIO as successor for #MP3 in Song Parser
- [ ] #MP3 as deprecated (will be removed in v2.0.0 ~ end of 2025)

(according to [official common Song format Specification](https://usdx.eu/format/) v1.1.0 - release on: 1th Dec 2023)

**Comment by flokuep** [comment]
If this is only reading the AUDIO tag, than it's easiy, as it could be just added next to the MP3-tag reading :)

Complexity: XS

**Comment by Stefan1200-de** [comment]
> If this is only reading the AUDIO tag, than it's easiy, as it could be just added next to the MP3-tag reading :)

Yeah, this is how I will implement it, as soon as I open my Visual Studio again -> just adding one "case" line to the song loader :)

**Comment by marwin89** [comment]
@damienlaguerre: do you have some time to implement the #AUDIO? I guess It's just one line but important to keep up with the new songformat standards. 🙂 BTW: I added you to the credit section in our wiki.
