### ISSUE TITLE
Introduce #TAGS Attribute

### ISSUE THREAD

**Issue by marwin89** [Vocaluxe/Vocaluxe#624]
##Suggestion
- Introduce `#TAGS` Attribute in Song Parser
- should have multiple entries see #623
- This field is for any reasonable keyword that fits to the song
- Songs should be categorized by #TAGS like #GENRE

(according to [official common Song format Specification](https://usdx.eu/format/) v1.1.0 - release on: 1th Dec 2023)

**Comment by flokuep** [comment]
Implementation isn't that complicated, most of the code can be duplicated from the Editions and Genre tag loading. Vocaluxe already support multiple Edition and Genre tags, so multiple values isn't a big problem.

- Add new entries for Tags to ESongSorting and ECoverGeneratorType
- Add list of tags to the main song class
- Enhance SongLoader and SongWriter
- Take care of adjusting the Sorter and Categorizer classes - Just have a look where e.g. the Editions field is used.

Complexity: S
