### ISSUE TITLE
update credit screen

### ISSUE THREAD

**Issue by marwin89** [Vocaluxe/Vocaluxe#676]
### What

- [x] update and improve the credit screen for all the working developers of the last 12 years.
- [x] Just a scrolling screen
- [ ] Reachable via options (best practice in many games).
- [x] Text is hardcoded and has to be updated.
- [x] Graphics need an update

### Why
- To show love
- to give references
- to motivate new developers to join
- credit screen is hard to find right now (only via pressing C on MainScreen)

### Additional info
We got all [credit infos in Wiki](https://github.com/Vocaluxe/Vocaluxe/wiki/Credits)

### Skills needed
Graphics, Coder

**Comment by marwin89** [comment]
There seems to be a c#-file in vocaluxe code for that named CreditScreen. Is it used?

**Comment by flokuep** [comment]
Yes, just press C when your on main screen.

**Comment by marwin89** [comment]
Oh, good to know! I never discovered this in 6 years! 🙂
We should really make a button in options menu for that. 😮 
Reminder for me:
- Text is hardcoded and has to be updated.
- Graphics need an update
- Add Background music for credits

![VocaluxeCreditScreen2012](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/fcbef64e-4188-4f88-b335-623363049d16)
![VocaluxeCreditScreen2012-2](https://github.com/Vocaluxe/Vocaluxe/assets/63517874/2f9b9e30-8660-4a0f-8291-d51c2522bd82)
