### ISSUE TITLE
Add key modifiers

### ISSUE THREAD

**Issue by Lithmariel** [Vocaluxe/Vocaluxe#679]
People have "vocal ranges", and some musics will always be outside them. It'd be really nice to have a built-in shifter.

As fun as it might be to try to sing some songs you just can't (you might even expand your range even if slightly eventually!) it's not even very good to force yourself so much.

Would be absolutely amazing to have this!!

**Comment by marwin89** [comment]
Hi @Lithmariel , thanks for your idea, I put this on our idea list ticket: 
- #680 

Other players can show interest by adding 👍🏻 reaction to the comment
