### ISSUE TITLE
Problem with ANSI encoded txts in current version

### ISSUE THREAD

**Issue by JPGsProfil** [Vocaluxe/Vocaluxe#687]
I don't know which version it happened because it's a few months ago (2023-11-30) I downloaded the newest version of  Vocaluxe but in the current build ANSI / windows-coded textfiles aren't working as before. If I convert them to UTF8, all letters all displayed correct. Is this a bug or are you forcing the users to switch to utf8 coded files?
![Screenshot 2024-02-29 223231](https://github.com/Vocaluxe/Vocaluxe/assets/4520514/3908468e-396f-46b1-91fb-2eaf4e5d07f8)

**Comment by flokuep** [comment]
The developers of allmost every singstar-like game decided to use utf8 as a default for song files. As a proper automatic detection is a bit complex, and there is currently no active developer working on vocaluxe, we simply changed the default in the latest nightly. (Read more about it here: https://usdx.eu/format/

Glad that you found out fixing it by yourself, we should do a blog post or something else for that, but also here: no developer and not enough time to do it by myself.

Sorry for the inconvenience.
