### ISSUE TITLE
Vocaluxe won't start on Windows 7 SP1 x86

### ISSUE THREAD

**Issue by Cratopea** [Vocaluxe/Vocaluxe#688]
Stable version will not start on Windows 7 SP1 x86 that's completely up to date and with nothing else installed on the system. Produces the following error message: "Error on start up: Security error." No antivirus or other security software is installed on the system. No errors are recorded in Event Viewer. Firewall is also disabled just in case the system was trying to connect to the internet for some reason. 

Edit: noticed the error.log file. It reads as follows:

ï»¿Error-Log Vocaluxe 'Blue Sunrise' 0.4.0 (x86) (0.4.0-61-g81c3233) 3/28/2024 12:16:53 AM
----------------------------------------

1) Error on start up: System.Security.SecurityException: Security error.
   at Vocaluxe.CProgrammHelper._CheckUninstallKey(String name, String key)
   at Vocaluxe.CProgrammHelper._IsProgramInstalled(String name)
   at Vocaluxe.CProgrammHelper.CheckRequirements()
   at Vocaluxe.CMainProgram._Run(String[] args)
The Zone of the assembly that failed was:
MyComputer
2) Error during shutdown! (CBackgroundMusic): System.TypeInitializationException: The type initializer for 'Vocaluxe.Base.CBackgroundMusic' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VocaluxeLib.Utils.Player.CSongPlayer..ctor(Boolean loop)
   at Vocaluxe.Base.CBackgroundMusic..cctor()
   --- End of inner exception stack trace ---
   at Vocaluxe.Base.CBackgroundMusic.Close()
   at Vocaluxe.CMainProgram._CloseProgram()

Also downloaded the latest nightly, it produces the same security error and what appears to be the same on-screen error. When I try to upload the displayed error from the nightly I get an error and the program says it can't upload the log file. Again, firewall is disabled and internet on that system is working fine so there's no reason the error log shouldn't upload. 

Thank you.

**Comment by flokuep** [comment]
Sounds strange. Vocaluxe tries to check if all necessary software is installed on your system. We're doing that by checking some registry keys. Having a plain system here could be the reason, why that fails.

You could try to install some vocaluxe dependencies as .NET 4.0, DirectX and a C++ lib, described here: https://github.com/Vocaluxe/Vocaluxe/wiki/Prerequisites

You could also try to run vocaluxe with admin privileges, just to make sure that this isn't the problem.

**Comment by Cratopea** [comment]
Yep, installing the prerequisites worked. Thank you for the help.

**Comment by flokuep** [comment]
You're welcome :) I've created a new issue to improve the error logging.
