### ISSUE TITLE
Add ability to search by #TAGS

### ISSUE THREAD

**Issue by RastislavTuranyi** [Vocaluxe/Vocaluxe#690]
Hi,

I was excited to find out that Vocaluxe already has the support for the #TAGS attribute, but I was not able to figure out how to search using tags. Please correct me if I'm wrong, but searching through the source code, the capability does not seem to exist at present in the `develop` branch. Therefore, I would like to ask whether you are interested in adding the ability to search using the #TAGS attribute.

I'm new to the repo (and C#), but I'm willing to look into implementing it myself if you are OK with this feature (and you wouldn't prefer to do it yourself). Looking at the code, it should be fairly simple to implement as I believe all that is needed is to add a new case for the [`switch`](https://github.com/Vocaluxe/Vocaluxe/blob/cd0e5223cd320f12222ac703a6de0ce53bb4b5ed/Vocaluxe/Base/CSongFilter.cs#L118) statement in [CSongFilter.cs](https://github.com/Vocaluxe/Vocaluxe/blob/develop/Vocaluxe/Base/CSongFilter.cs) and then add a corresponding check similar to [that for genre](https://github.com/Vocaluxe/Vocaluxe/blob/cd0e5223cd320f12222ac703a6de0ce53bb4b5ed/Vocaluxe/Base/CSongFilter.cs#L207) in the for loop below.

**Comment by flokuep** [comment]
Sure, go for it :) Your codepointers should be the right way to solve that issue. If you struggle with some things, just ask within this issue or create a pull request with your changes. I'll try to help you out.

**Comment by RastislavTuranyi** [comment]
Cool, thanks! Do you have any preference for the search pattern? I was thinking that `ta` or `tg` would make sense, or perhaps even the whole 3-letter word `tag`, though personally I would prefer some 1-letter code.

**Comment by flokuep** [comment]
1-letter code could maybe also `#`? Not sure if this works in the current implementation, but could be the most common code?
