### ISSUE TITLE
Error on start up: The type initializer for 'Gst.Application' threw an exception.

### ISSUE THREAD

**Issue by TYTheBeast** [Vocaluxe/Vocaluxe#700]
Describe your issue here.
On opening of the game, I get the error "Error on start up: The type initializer for 'Gst.Application' threw an exception."

### Steps to reproduce
Start up the game on Windows 11.

### Vocaluxe version and logfile
Vocaluxe 'Blue Sunrise' 0.4.0 (x64) (0.4.0-750-g88c1ba5)
[Vocaluxe.log](https://github.com/Vocaluxe/Vocaluxe/files/15417711/Vocaluxe.log)

**Comment by flokuep** [comment]
Looks like that a dll file is missing. Could you please check if you can find a `libgstreamer-1.0-0.dll` file within the Vocaluxe/libs/unmanaged/gstreamer/bin folder? If not, please re-download and unzip and verify that there is no antivirus-software moving or blocking these dll-files.

**Comment by marwin89** [comment]
I close this issue due inactivity. Please re-open if needed.
