### ISSUE TITLE
Change Players' In-Game Colours

### ISSUE THREAD

**Issue by daggeg** [Vocaluxe/Vocaluxe#701]
It would be a real nice feature to be able to change the players' in-game colours.

**Comment by flokuep** [comment]
Hi! This is a duplicate to #681

**Comment by daggeg** [comment]
Sorry, I forgot that I had already made a post about this :) Anyway, can someone help me find the file/files where I get to change the text colour and the colour filling the lyrics while singing?

* never mind, I found it.

**Comment by flokuep** [comment]
Great :) Still interested in your use case about that. Is it just visual? Or do some players prefer specific colours?

**Comment by daggeg** [comment]
I think it would be a nice feature to let the user change colours if they'd like to.

**Comment by marwin89** [comment]
I close this issue cause this is a duplicate to https://github.com/Vocaluxe/Vocaluxe/issues/681
