### ISSUE TITLE
Song folder not created by default

### ISSUE THREAD

**Issue by vinch100** [Vocaluxe/Vocaluxe#77]
Hello,

Vocaluxe Installer 0.3r81 doesn't comes with the "songs folder"m which lead to an "Error on Startup".
Tested on x64

Thanks

**Comment by lukeIam** [comment]
There should be no error anymore but atm can't whether the folder is created automatically or not.

**Comment by lukeIam** [comment]
> There should be no error anymore but atm can't whether the folder is created automatically or not.

It is created but not used - We'll fix that

**Comment by derivator** [comment]
Please also make sure we're not trying to write to install dir on linux, see https://github.com/lukeIam/Vocaluxe/commit/acd89bc2d3701a012b88f2f9e3e318105f27d5d3

**Comment by flokuep** [comment]
I've changed it to have for WIN-Builds relative folders, INSTALLER-Builds relative folders and Data-Folder, LINUX-Builds data-folder.
